import { api } from './api'
import { puterGateway } from './puter'

export interface ResearchProgress{stage:string;message:string;completed:number;total:number}
export async function runResearchSwarm(query:string,modelCount=4,onProgress?:(progress:ResearchProgress)=>void){
  const plan=await api.researchPlan(query,modelCount);if(!await puterGateway.user())await puterGateway.signIn();await puterGateway.discover();const perspectives=['fontes primárias e documentação oficial','literatura técnica/acadêmica e metodologia','informação recente, datas e freshness','contraevidências, limitações e contradições','dados quantitativos e comparações','impactos práticos e contexto amplo','fontes internacionais e perspectivas divergentes','verificação independente dos principais claims'];onProgress?.({stage:'research',message:`Executando ${plan.researchers.length} pesquisadores elegíveis em paralelo`,completed:0,total:plan.researchers.length})
  let completed=0;const settled=await Promise.allSettled(plan.researchers.map(async(model,index)=>{const startedAt=new Date().toISOString(),started=performance.now();try{const result=await puterGateway.webSearch(model.provider,model.id,`Pesquise na web sobre: ${query}\nFoco desta investigação: ${perspectives[index%perspectives.length]}.\nSepare fatos, evidências, incertezas e contradições. Inclua citações e URLs reais.`);return{...result,startedAt,durationMs:Math.round(performance.now()-started)}}catch(error){throw{provider:model.provider,modelId:model.id,error:error instanceof Error?error.message:'Falha de pesquisa'}}finally{completed++;onProgress?.({stage:'research',message:`Pesquisador concluído (${completed}/${plan.researchers.length})`,completed,total:plan.researchers.length})}}))
  const successes=settled.flatMap(result=>result.status==='fulfilled'?[result.value]:[]),failures=settled.filter((result):result is PromiseRejectedResult=>result.status==='rejected').map(result=>{const reason=result.reason as {provider?:string;modelId?:string;error?:string};return{provider:reason.provider??'unknown',modelId:reason.modelId??'unknown',error:reason.error??'Falha de pesquisa'}});if(successes.length<2)throw new Error(`Research Swarm insuficiente: ${successes.length} sucesso(s), ${failures.length} falha(s).`)
  let conversationId:string|undefined;for(const research of successes){const recorded=await api.recordPuterExecution({conversationId,prompt:`RESEARCH: ${query}`,response:research.content,provider:research.provider,modelId:research.modelId,durationMs:research.durationMs,startedAt:research.startedAt,fallbackChain:[]});conversationId=recorded.conversationId}
  const sources=new Map<string,{url:string;title?:string}>();for(const result of successes)for(const citation of result.citations)sources.set(citation.url,citation)
  const evidence=successes.map((result,index)=>`PESQUISADOR ${index+1} (${result.provider}/${result.modelId}):\n${result.content.slice(0,7000)}`).join('\n\n---\n\n'),startedAt=new Date().toISOString(),started=performance.now();onProgress?.({stage:'synthesis',message:'Comparando claims, evidências, freshness e divergências',completed:successes.length,total:successes.length})
  const synthesis=await puterGateway.webSearch(plan.synthesizer.provider,plan.synthesizer.id,`Você é o sintetizador crítico da SNB. Pergunta: ${query}\n\nCompare as pesquisas abaixo. Não escolha por maioria. Identifique convergências, conflitos, lacunas e nível de certeza. Preserve URLs reais e não invente fontes.\n\n${evidence}`)
  await api.recordPuterExecution({conversationId,prompt:`SYNTHESIS: ${query}`,response:synthesis.content,provider:plan.synthesizer.provider,modelId:plan.synthesizer.id,durationMs:Math.round(performance.now()-started),startedAt,fallbackChain:failures.slice(0,8)})
  for(const citation of [...sources.values(),...synthesis.citations])if(!sources.has(citation.url))sources.set(citation.url,citation)
  const sourceRecords:{id:string}[]=[];for(const citation of sources.values()){const source=await api.addSource({url:citation.url,title:citation.title??new URL(citation.url).hostname}).catch(()=>undefined);if(source)sourceRecords.push(source)}
  const claim=await api.addClaim(query);for(const source of sourceRecords)await api.linkEvidence({claimId:claim.id,sourceId:source.id,relation:'context',strength:.5}).catch(()=>undefined)
  return{query,answer:synthesis.content,sources:[...sources.values()],researchers:successes.map(result=>({provider:result.provider,modelId:result.modelId,citations:result.citations.length})),synthesizer:plan.synthesizer,failures,claimId:claim.id,trust:{execution:'client-reported',providerAttested:false,verification:'evidence-comparison-not-deterministic'},policy:plan.policy,eligibleTotal:plan.eligibleTotal}
}
