import type { GisSource } from './types.js'

export const gisSources: GisSource[] = [
  {
    id: 'internal-fixture',
    name: 'UES licensed internal spatial fixture',
    family: 'internal',
    homepage: 'https://github.com/devEb209/-Singularity-AI-',
    kinds: ['height', 'hydro', 'climate', 'biome', 'geology'],
    licenseHint: 'CC0',
    auth: 'none',
    status: 'IMPLEMENTED',
    vendorLock: false,
    fetchedRemote: false,
  },
  {
    id: 'ogc-3d-tiles',
    name: 'OGC 3D Tiles',
    family: 'ogc-3d-tiles',
    homepage: 'https://www.ogc.org/standards/3dtiles/',
    kinds: ['height', 'geology'],
    licenseHint: 'dataset-specific',
    auth: 'none',
    status: 'ADAPTER_AVAILABLE',
    vendorLock: false,
    fetchedRemote: false,
  },
  {
    id: 'google-photorealistic',
    name: 'Google Photorealistic 3D Tiles',
    family: 'photorealistic-tiles',
    homepage: 'https://developers.google.com/maps/documentation/tile/3d-tiles',
    kinds: ['height'],
    licenseHint: 'Google Maps Platform terms',
    auth: 'api-key',
    status: 'ADAPTER_AVAILABLE',
    vendorLock: false,
    fetchedRemote: false,
  },
  {
    id: 'cesium-native',
    name: 'Cesium ecosystem / ion',
    family: 'cesium',
    homepage: 'https://github.com/CesiumGS/cesium-native',
    kinds: ['height'],
    licenseHint: 'Cesium ion / dataset-specific',
    auth: 'api-key',
    status: 'ADAPTER_AVAILABLE',
    vendorLock: false,
    fetchedRemote: false,
  },
  {
    id: 'nasa-earthdata',
    name: 'NASA Earthdata',
    family: 'nasa-earthdata',
    homepage: 'https://www.earthdata.nasa.gov/',
    kinds: ['height', 'climate', 'hydro'],
    licenseHint: 'NASA Earthdata terms',
    auth: 'earthdata-token',
    status: 'ADAPTER_AVAILABLE',
    vendorLock: false,
    fetchedRemote: false,
  },
  {
    id: 'usgs',
    name: 'USGS',
    family: 'usgs',
    homepage: 'https://www.usgs.gov/',
    kinds: ['height', 'geology', 'hydro'],
    licenseHint: 'USGS public-domain / dataset-specific',
    auth: 'none',
    status: 'ADAPTER_AVAILABLE',
    vendorLock: false,
    fetchedRemote: false,
  },
  {
    id: 'opentopography',
    name: 'OpenTopography',
    family: 'opentopography',
    homepage: 'https://opentopography.org/',
    kinds: ['height'],
    licenseHint: 'dataset-specific',
    auth: 'api-key',
    status: 'ADAPTER_AVAILABLE',
    vendorLock: false,
    fetchedRemote: false,
  },
]

export const sourceById = (id: string) => gisSources.find(item => item.id === id)

export const operationalSources = () => gisSources.filter(item => item.status === 'IMPLEMENTED')
