import Database from 'better-sqlite3'
import type { ApprovalRequest, ArtifactRecord, DivineEngineCommand, DivineEngineSettings, BenchmarkCampaign, BenchmarkJob, CapabilityManifest, CircuitState, Conversation, DivineOsModule, DivineOsProject, DivineProject, EvidenceLink, EvidenceSource, ExternalModel, FileAsset, KnowledgeClaim, Memory, Message, Mission, MissionContract, MissionEvent, MissionTask, ModelEvaluation, ModelHealthSample, Project, ProjectCheckpoint, PuterExecutionReport, TaskLease, ToolExecution, WorkerRecord } from '../domain.js'
import { id, now } from '../lib/id.js'
import { NotFoundError, AppError } from '../lib/errors.js'
import type { AuditEvent, Store, StoredPasswordResetToken, StoredRefreshToken, StoredUser } from './store.js'
import type { HsdsSession } from '../services/hsds.js'

type Row = Record<string, string | number | null>
const json = <T>(value: string | null) => value ? JSON.parse(value) as T : undefined

export class SQLiteStore implements Store {
  private db: Database.Database
  constructor(path: string) {
    this.db = new Database(path)
    this.db.pragma('journal_mode = WAL')
    this.db.pragma('foreign_keys = ON')
    this.db.pragma('busy_timeout = 5000')
    this.migrate()
  }

  private migrate() {
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL, password_hash TEXT NOT NULL, created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS refresh_tokens (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, token_hash TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, revoked_at TEXT, created_at TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS idx_refresh_user ON refresh_tokens(user_id);
      CREATE TABLE IF NOT EXISTS password_reset_tokens (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,used_at TEXT,created_at TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS idx_password_reset_hash ON password_reset_tokens(token_hash);
      CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'active', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS idx_projects_user ON projects(user_id, updated_at DESC);
      CREATE TABLE IF NOT EXISTS conversations (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, title TEXT NOT NULL, project_id TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS idx_conversations_user ON conversations(user_id, updated_at DESC);
      CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL, role TEXT NOT NULL, content TEXT NOT NULL, metadata TEXT, created_at TEXT NOT NULL, FOREIGN KEY(conversation_id) REFERENCES conversations(id) ON DELETE CASCADE);
      CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id, created_at);
      CREATE TABLE IF NOT EXISTS memories (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, project_id TEXT, content TEXT NOT NULL, kind TEXT NOT NULL, importance REAL NOT NULL, created_at TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS idx_memories_user ON memories(user_id, project_id);
      CREATE TABLE IF NOT EXISTS files (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, project_id TEXT, name TEXT NOT NULL, mime_type TEXT NOT NULL, size INTEGER NOT NULL, checksum TEXT NOT NULL, storage_path TEXT NOT NULL, created_at TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS idx_files_user ON files(user_id, project_id, created_at DESC);
      CREATE TABLE IF NOT EXISTS missions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, project_id TEXT, goal TEXT NOT NULL, status TEXT NOT NULL, progress REAL NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS idx_missions_user ON missions(user_id, updated_at DESC);
      CREATE TABLE IF NOT EXISTS mission_contracts (mission_id TEXT PRIMARY KEY, objective TEXT NOT NULL, user_intent TEXT NOT NULL, constraints TEXT NOT NULL, required_capabilities TEXT NOT NULL, available_resources TEXT NOT NULL, risks TEXT NOT NULL, success_criteria TEXT NOT NULL, verification_requirements TEXT NOT NULL, final_deliverable TEXT NOT NULL, autonomy TEXT NOT NULL, phase TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(mission_id) REFERENCES missions(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS mission_tasks (id TEXT PRIMARY KEY, mission_id TEXT NOT NULL, task_key TEXT NOT NULL, title TEXT NOT NULL, kind TEXT NOT NULL, status TEXT NOT NULL, depends_on TEXT NOT NULL, input TEXT NOT NULL, output TEXT, error TEXT, progress REAL NOT NULL, attempts INTEGER NOT NULL, max_attempts INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(mission_id, task_key), FOREIGN KEY(mission_id) REFERENCES missions(id) ON DELETE CASCADE);
      CREATE INDEX IF NOT EXISTS idx_mission_tasks_ready ON mission_tasks(mission_id, status);
      CREATE TABLE IF NOT EXISTS mission_events (id TEXT PRIMARY KEY, mission_id TEXT NOT NULL, task_id TEXT, type TEXT NOT NULL, payload TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(mission_id) REFERENCES missions(id) ON DELETE CASCADE);
      CREATE INDEX IF NOT EXISTS idx_mission_events ON mission_events(mission_id, created_at);
      CREATE TABLE IF NOT EXISTS project_checkpoints (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, project_id TEXT NOT NULL, label TEXT NOT NULL, snapshot TEXT NOT NULL, created_at TEXT NOT NULL, restored_at TEXT);
      CREATE INDEX IF NOT EXISTS idx_checkpoints_project ON project_checkpoints(user_id, project_id, created_at DESC);
      CREATE TABLE IF NOT EXISTS external_models (model_key TEXT PRIMARY KEY, source TEXT NOT NULL, model_id TEXT NOT NULL, provider TEXT NOT NULL, name TEXT, aliases TEXT NOT NULL, context_window INTEGER, max_tokens INTEGER, input_cost REAL, output_cost REAL, raw_metadata TEXT NOT NULL, first_seen_at TEXT NOT NULL, last_seen_at TEXT NOT NULL, available INTEGER NOT NULL DEFAULT 1);
      CREATE INDEX IF NOT EXISTS idx_external_models_source ON external_models(source, available, provider);
      CREATE TABLE IF NOT EXISTS model_evaluations (id TEXT PRIMARY KEY, model_key TEXT NOT NULL, capability TEXT NOT NULL, score REAL NOT NULL, latency_ms INTEGER, success INTEGER NOT NULL, benchmark TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(model_key) REFERENCES external_models(model_key) ON DELETE CASCADE);
      CREATE INDEX IF NOT EXISTS idx_model_eval_capability ON model_evaluations(capability, model_key, created_at DESC);
      CREATE TABLE IF NOT EXISTS benchmark_campaigns (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, capability TEXT NOT NULL, benchmark_version TEXT NOT NULL, status TEXT NOT NULL, total_jobs INTEGER NOT NULL, submitted_jobs INTEGER NOT NULL, verified_jobs INTEGER NOT NULL, failed_jobs INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS idx_benchmark_campaign_user ON benchmark_campaigns(user_id, updated_at DESC);
      CREATE TABLE IF NOT EXISTS benchmark_jobs (id TEXT PRIMARY KEY, campaign_id TEXT NOT NULL, model_key TEXT NOT NULL, status TEXT NOT NULL, claim_token_hash TEXT, claim_expires_at TEXT, submitted_by TEXT, output TEXT, latency_ms INTEGER, error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(campaign_id, model_key), FOREIGN KEY(campaign_id) REFERENCES benchmark_campaigns(id) ON DELETE CASCADE, FOREIGN KEY(model_key) REFERENCES external_models(model_key) ON DELETE CASCADE);
      CREATE INDEX IF NOT EXISTS idx_benchmark_jobs_queue ON benchmark_jobs(campaign_id, status, created_at);
      CREATE TABLE IF NOT EXISTS tool_executions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, tool_id TEXT NOT NULL, tool_version TEXT NOT NULL, mission_id TEXT, task_id TEXT, status TEXT NOT NULL, input TEXT NOT NULL, output TEXT, error TEXT, policy TEXT NOT NULL, verification TEXT, receipt TEXT, started_at TEXT NOT NULL, completed_at TEXT);
      CREATE INDEX IF NOT EXISTS idx_tool_execution_user ON tool_executions(user_id, started_at DESC);
      CREATE TABLE IF NOT EXISTS circuit_states (resource_key TEXT PRIMARY KEY, state TEXT NOT NULL, failure_count INTEGER NOT NULL, success_count INTEGER NOT NULL, opened_at TEXT, cooldown_until TEXT, last_error TEXT, updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS model_health_samples (id TEXT PRIMARY KEY, model_key TEXT NOT NULL, success INTEGER NOT NULL, latency_ms INTEGER NOT NULL, error TEXT, source TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(model_key) REFERENCES external_models(model_key) ON DELETE CASCADE);
      CREATE INDEX IF NOT EXISTS idx_model_health_samples ON model_health_samples(model_key, created_at DESC);
      CREATE TABLE IF NOT EXISTS workers (id TEXT PRIMARY KEY, name TEXT NOT NULL, capabilities TEXT NOT NULL, status TEXT NOT NULL, last_heartbeat_at TEXT NOT NULL, created_at TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS idx_workers_status ON workers(status, last_heartbeat_at);
      CREATE TABLE IF NOT EXISTS task_leases (task_id TEXT PRIMARY KEY, mission_id TEXT NOT NULL, worker_id TEXT NOT NULL, token_hash TEXT NOT NULL, expires_at TEXT NOT NULL, heartbeat_at TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(task_id) REFERENCES mission_tasks(id) ON DELETE CASCADE, FOREIGN KEY(mission_id) REFERENCES missions(id) ON DELETE CASCADE, FOREIGN KEY(worker_id) REFERENCES workers(id) ON DELETE CASCADE);
      CREATE INDEX IF NOT EXISTS idx_task_leases_expiry ON task_leases(expires_at);
      CREATE TABLE IF NOT EXISTS puter_execution_reports (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, conversation_id TEXT NOT NULL, model_key TEXT NOT NULL, provider TEXT NOT NULL, model_id TEXT NOT NULL, prompt_hash TEXT NOT NULL, response_hash TEXT NOT NULL, duration_ms INTEGER NOT NULL, fallback_chain TEXT NOT NULL, trust TEXT NOT NULL, receipt TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(conversation_id) REFERENCES conversations(id) ON DELETE CASCADE, FOREIGN KEY(model_key) REFERENCES external_models(model_key));
      CREATE INDEX IF NOT EXISTS idx_puter_reports_user ON puter_execution_reports(user_id,created_at DESC);
      CREATE TABLE IF NOT EXISTS approvals (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, mission_id TEXT, task_id TEXT, action TEXT NOT NULL, risk TEXT NOT NULL, rationale TEXT NOT NULL, status TEXT NOT NULL, expires_at TEXT NOT NULL, requested_at TEXT NOT NULL, decided_at TEXT, consumed_at TEXT);
      CREATE INDEX IF NOT EXISTS idx_approvals_user ON approvals(user_id,status,requested_at DESC);
      CREATE TABLE IF NOT EXISTS user_settings (user_id TEXT PRIMARY KEY, data TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS evidence_sources (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,project_id TEXT,url TEXT NOT NULL,title TEXT NOT NULL,publisher TEXT,published_at TEXT,retrieved_at TEXT NOT NULL,content_hash TEXT,status TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS idx_evidence_sources_user ON evidence_sources(user_id,project_id,retrieved_at DESC);
      CREATE TABLE IF NOT EXISTS knowledge_claims (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,project_id TEXT,statement TEXT NOT NULL,state TEXT NOT NULL,confidence REAL NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS idx_claims_user ON knowledge_claims(user_id,project_id,state);
      CREATE TABLE IF NOT EXISTS evidence_links (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,claim_id TEXT NOT NULL,source_id TEXT NOT NULL,relation TEXT NOT NULL,quote TEXT,strength REAL NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(claim_id) REFERENCES knowledge_claims(id) ON DELETE CASCADE,FOREIGN KEY(source_id) REFERENCES evidence_sources(id) ON DELETE CASCADE);
      CREATE INDEX IF NOT EXISTS idx_evidence_links_claim ON evidence_links(user_id,claim_id);
      CREATE TABLE IF NOT EXISTS capability_manifests (id TEXT PRIMARY KEY,name TEXT NOT NULL,version TEXT NOT NULL,vendor TEXT NOT NULL,type TEXT NOT NULL,capabilities TEXT NOT NULL,inputs TEXT NOT NULL,outputs TEXT NOT NULL,execution_methods TEXT NOT NULL,authentication TEXT NOT NULL,permissions TEXT NOT NULL,dependencies TEXT NOT NULL,cost TEXT,latency TEXT,limits TEXT NOT NULL,license TEXT NOT NULL,risk TEXT NOT NULL,compatibility TEXT NOT NULL,status TEXT NOT NULL,reliability REAL NOT NULL,evidence_count INTEGER NOT NULL,metadata TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS idx_capability_manifest ON capability_manifests(status,type);
      CREATE TABLE IF NOT EXISTS divine_projects (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,project_id TEXT NOT NULL,mission_id TEXT NOT NULL,name TEXT NOT NULL,brief TEXT NOT NULL,target TEXT NOT NULL,format TEXT NOT NULL,execution_policy TEXT NOT NULL,device_profile TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,FOREIGN KEY(mission_id) REFERENCES missions(id) ON DELETE CASCADE);
      CREATE INDEX IF NOT EXISTS idx_divine_projects_user ON divine_projects(user_id,updated_at DESC);
      CREATE TABLE IF NOT EXISTS divine_engine_settings (divine_project_id TEXT PRIMARY KEY,user_id TEXT NOT NULL,values_json TEXT NOT NULL,preset TEXT NOT NULL,version INTEGER NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(divine_project_id) REFERENCES divine_projects(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS divine_engine_commands (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,divine_project_id TEXT NOT NULL,message TEXT NOT NULL,attachment_file_ids TEXT NOT NULL,status TEXT NOT NULL,operations TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(divine_project_id) REFERENCES divine_projects(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS hsds_sessions (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,project_id TEXT NOT NULL,divine_project_id TEXT NOT NULL,status TEXT NOT NULL,profile TEXT NOT NULL,state TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,FOREIGN KEY(divine_project_id) REFERENCES divine_projects(id) ON DELETE CASCADE);
      CREATE INDEX IF NOT EXISTS idx_hsds_user_project ON hsds_sessions(user_id,project_id,updated_at DESC);
      CREATE INDEX IF NOT EXISTS idx_divine_commands ON divine_engine_commands(user_id,divine_project_id,created_at);
      CREATE TABLE IF NOT EXISTS artifact_records (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,project_id TEXT NOT NULL,file_id TEXT NOT NULL,type TEXT NOT NULL,version INTEGER NOT NULL,parent_id TEXT,producer TEXT NOT NULL,inputs TEXT NOT NULL,dependencies TEXT NOT NULL,verification TEXT NOT NULL,metadata TEXT NOT NULL,license TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,FOREIGN KEY(file_id) REFERENCES files(id) ON DELETE CASCADE,FOREIGN KEY(parent_id) REFERENCES artifact_records(id));
      CREATE INDEX IF NOT EXISTS idx_artifacts_project ON artifact_records(user_id,project_id,created_at DESC);
      CREATE TABLE IF NOT EXISTS divine_os_projects (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,project_id TEXT NOT NULL,mission_id TEXT NOT NULL,name TEXT NOT NULL,variant TEXT NOT NULL,status TEXT NOT NULL,architecture TEXT NOT NULL,base_manifest TEXT NOT NULL,configuration TEXT NOT NULL,compliance TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,FOREIGN KEY(mission_id) REFERENCES missions(id) ON DELETE CASCADE);
      CREATE INDEX IF NOT EXISTS idx_divine_os_user ON divine_os_projects(user_id,updated_at DESC);
      CREATE TABLE IF NOT EXISTS divine_os_modules (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,divine_os_project_id TEXT NOT NULL,name TEXT NOT NULL,version TEXT NOT NULL,capabilities TEXT NOT NULL,dependencies TEXT NOT NULL,permissions TEXT NOT NULL,status TEXT NOT NULL,manifest TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(divine_os_project_id) REFERENCES divine_os_projects(id) ON DELETE CASCADE);
      CREATE INDEX IF NOT EXISTS idx_divine_os_modules ON divine_os_modules(user_id,divine_os_project_id);
      CREATE TABLE IF NOT EXISTS audit_events (id TEXT PRIMARY KEY, user_id TEXT, action TEXT NOT NULL, resource TEXT, metadata TEXT, created_at TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_events(user_id, created_at DESC);
      INSERT OR IGNORE INTO mission_contracts(mission_id,objective,user_intent,constraints,required_capabilities,available_resources,risks,success_criteria,verification_requirements,final_deliverable,autonomy,phase,created_at,updated_at) SELECT id,goal,goal,'[]','[]','[]','[]','["Todas as tarefas concluídas"]','["Verificação requerida"]','Resultado da missão','SUPERVISED',CASE WHEN status='completed' THEN 'COMPLETED' WHEN status='failed' THEN 'FAILED' WHEN status='cancelled' THEN 'CANCELLED' ELSE 'CREATED' END,created_at,updated_at FROM missions;
      CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);
      INSERT OR IGNORE INTO schema_migrations(version, applied_at) VALUES (1, datetime('now'));
    `)
  }

  createConversation(userId: string, title: string, projectId?: string) {
    const timestamp = now(); const conversation: Conversation = { id: id('conv'), userId, title, projectId, createdAt: timestamp, updatedAt: timestamp }
    this.db.prepare('INSERT INTO conversations VALUES (?, ?, ?, ?, ?, ?)').run(conversation.id, userId, title, projectId ?? null, timestamp, timestamp)
    return conversation
  }
  getConversation(conversationId: string, userId: string) {
    const row = this.db.prepare('SELECT * FROM conversations WHERE id = ? AND user_id = ?').get(conversationId, userId) as Row | undefined
    if (!row) throw new NotFoundError('Conversa'); return this.conversation(row)
  }
  listConversations(userId: string) { return (this.db.prepare('SELECT * FROM conversations WHERE user_id = ? ORDER BY updated_at DESC').all(userId) as Row[]).map(row => this.conversation(row)) }
  addMessage(conversationId: string, userId: string, role: Message['role'], content: string, metadata?: Message['metadata']) {
    this.getConversation(conversationId, userId); const timestamp = now()
    const message: Message = { id: id('msg'), conversationId, role, content, metadata, createdAt: timestamp }
    const transaction = this.db.transaction(() => { this.db.prepare('INSERT INTO messages VALUES (?, ?, ?, ?, ?, ?)').run(message.id, conversationId, role, content, metadata ? JSON.stringify(metadata) : null, timestamp); this.db.prepare('UPDATE conversations SET updated_at = ? WHERE id = ?').run(timestamp, conversationId) })
    transaction(); return message
  }
  listMessages(conversationId: string, userId: string) { this.getConversation(conversationId, userId); return (this.db.prepare('SELECT * FROM messages WHERE conversation_id = ? ORDER BY created_at').all(conversationId) as Row[]).map(row => this.message(row)) }
  createProject(userId: string, name: string, description = '') { const timestamp = now(); const project: Project = { id: id('proj'), userId, name, description, status: 'active', createdAt: timestamp, updatedAt: timestamp }; this.db.prepare('INSERT INTO projects VALUES (?, ?, ?, ?, ?, ?, ?)').run(project.id, userId, name, description, project.status, timestamp, timestamp); return project }
  listProjects(userId: string) { return (this.db.prepare('SELECT * FROM projects WHERE user_id = ? ORDER BY updated_at DESC').all(userId) as Row[]).map(row => this.project(row)) }
  getProject(projectId: string, userId: string) { const row = this.db.prepare('SELECT * FROM projects WHERE id = ? AND user_id = ?').get(projectId, userId) as Row | undefined; if (!row) throw new NotFoundError('Projeto'); return this.project(row) }
  updateProject(projectId: string, userId: string, update: Partial<Pick<Project, 'name' | 'description' | 'status'>>) { const project = this.getProject(projectId, userId); const next = { ...project, ...update, updatedAt: now() }; this.db.prepare('UPDATE projects SET name=?, description=?, status=?, updated_at=? WHERE id=? AND user_id=?').run(next.name, next.description, next.status, next.updatedAt, projectId, userId); return next }
  createMemory(userId: string, content: string, kind: Memory['kind'], importance: number, projectId?: string) { const memory: Memory = { id: id('mem'), userId, projectId, content, kind, importance, createdAt: now() }; this.db.prepare('INSERT INTO memories VALUES (?, ?, ?, ?, ?, ?, ?)').run(memory.id, userId, projectId ?? null, content, kind, importance, memory.createdAt); return memory }
  listMemories(userId: string, projectId?: string) { const rows = projectId ? this.db.prepare('SELECT * FROM memories WHERE user_id=? AND project_id=?').all(userId, projectId) : this.db.prepare('SELECT * FROM memories WHERE user_id=?').all(userId); return (rows as Row[]).map(row => this.memory(row)) }
  deleteMemory(memoryId: string, userId: string) { const result = this.db.prepare('DELETE FROM memories WHERE id=? AND user_id=?').run(memoryId, userId); if (!result.changes) throw new NotFoundError('Memória') }
  createFile(file: FileAsset) { this.db.prepare('INSERT INTO files VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)').run(file.id, file.userId, file.projectId ?? null, file.name, file.mimeType, file.size, file.checksum, file.storagePath, file.createdAt); return file }
  listFiles(userId: string, projectId?: string) { const rows = projectId ? this.db.prepare('SELECT * FROM files WHERE user_id=? AND project_id=? ORDER BY created_at DESC').all(userId, projectId) : this.db.prepare('SELECT * FROM files WHERE user_id=? ORDER BY created_at DESC').all(userId); return (rows as Row[]).map(row => this.file(row)) }
  getFile(fileId: string, userId: string) { const row = this.db.prepare('SELECT * FROM files WHERE id=? AND user_id=?').get(fileId, userId) as Row | undefined; if (!row) throw new NotFoundError('Arquivo'); return this.file(row) }
  deleteFile(fileId: string, userId: string) { const file = this.getFile(fileId, userId); this.db.prepare('DELETE FROM files WHERE id=? AND user_id=?').run(fileId, userId); return file }
  createMission(mission: Mission, contract: MissionContract, tasks: MissionTask[], event: MissionEvent) {
    this.db.transaction(() => {
      this.db.prepare('INSERT INTO missions VALUES (?, ?, ?, ?, ?, ?, ?, ?)').run(mission.id, mission.userId, mission.projectId ?? null, mission.goal, mission.status, mission.progress, mission.createdAt, mission.updatedAt)
      this.db.prepare('INSERT INTO mission_contracts VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(contract.missionId,contract.objective,contract.userIntent,JSON.stringify(contract.constraints),JSON.stringify(contract.requiredCapabilities),JSON.stringify(contract.availableResources),JSON.stringify(contract.risks),JSON.stringify(contract.successCriteria),JSON.stringify(contract.verificationRequirements),contract.finalDeliverable,contract.autonomy,contract.phase,contract.createdAt,contract.updatedAt)
      const insertTask = this.db.prepare('INSERT INTO mission_tasks VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)')
      for (const task of tasks) insertTask.run(task.id, task.missionId, task.key, task.title, task.kind, task.status, JSON.stringify(task.dependsOn), JSON.stringify(task.input), task.output ? JSON.stringify(task.output) : null, task.error ?? null, task.progress, task.attempts, task.maxAttempts, task.createdAt, task.updatedAt)
      this.addMissionEvent(event)
    })(); return mission
  }
  getMission(missionId: string, userId: string) { const row = this.db.prepare('SELECT * FROM missions WHERE id=? AND user_id=?').get(missionId, userId) as Row | undefined; if (!row) throw new NotFoundError('Missão'); return this.mission(row) }
  getMissionContract(missionId:string){const row=this.db.prepare('SELECT * FROM mission_contracts WHERE mission_id=?').get(missionId) as Row|undefined;if(!row)throw new NotFoundError('Contrato da missão');return this.missionContract(row)}
  updateMissionContract(contract:MissionContract){this.db.prepare('UPDATE mission_contracts SET user_intent=?,constraints=?,required_capabilities=?,available_resources=?,risks=?,success_criteria=?,verification_requirements=?,final_deliverable=?,autonomy=?,phase=?,updated_at=? WHERE mission_id=?').run(contract.userIntent,JSON.stringify(contract.constraints),JSON.stringify(contract.requiredCapabilities),JSON.stringify(contract.availableResources),JSON.stringify(contract.risks),JSON.stringify(contract.successCriteria),JSON.stringify(contract.verificationRequirements),contract.finalDeliverable,contract.autonomy,contract.phase,contract.updatedAt,contract.missionId)}
  listMissions(userId: string) { return (this.db.prepare('SELECT * FROM missions WHERE user_id=? ORDER BY updated_at DESC').all(userId) as Row[]).map(row => this.mission(row)) }
  updateMission(mission: Mission) { this.db.prepare('UPDATE missions SET status=?, progress=?, updated_at=? WHERE id=? AND user_id=?').run(mission.status, mission.progress, mission.updatedAt, mission.id, mission.userId) }
  listMissionTasks(missionId: string) { return (this.db.prepare('SELECT * FROM mission_tasks WHERE mission_id=? ORDER BY rowid').all(missionId) as Row[]).map(row => this.missionTask(row)) }
  getMissionTask(taskId: string) { const row = this.db.prepare('SELECT * FROM mission_tasks WHERE id=?').get(taskId) as Row | undefined; return row ? this.missionTask(row) : undefined }
  updateMissionTask(task: MissionTask) { this.db.prepare('UPDATE mission_tasks SET status=?,output=?,error=?,progress=?,attempts=?,updated_at=? WHERE id=?').run(task.status, task.output ? JSON.stringify(task.output) : null, task.error ?? null, task.progress, task.attempts, task.updatedAt, task.id) }
  addMissionEvent(event: MissionEvent) { this.db.prepare('INSERT INTO mission_events VALUES (?, ?, ?, ?, ?, ?)').run(event.id, event.missionId, event.taskId ?? null, event.type, JSON.stringify(event.payload), event.createdAt) }
  listMissionEvents(missionId: string, after?: string) { const rows = after ? this.db.prepare('SELECT * FROM mission_events WHERE mission_id=? AND created_at>? ORDER BY created_at').all(missionId, after) : this.db.prepare('SELECT * FROM mission_events WHERE mission_id=? ORDER BY created_at').all(missionId); return (rows as Row[]).map(row => this.missionEvent(row)) }
  createCheckpoint(checkpoint: ProjectCheckpoint) { this.db.prepare('INSERT INTO project_checkpoints VALUES (?, ?, ?, ?, ?, ?, ?)').run(checkpoint.id, checkpoint.userId, checkpoint.projectId, checkpoint.label, JSON.stringify(checkpoint.snapshot), checkpoint.createdAt, checkpoint.restoredAt ?? null); return checkpoint }
  getCheckpoint(checkpointId: string, userId: string) { const row = this.db.prepare('SELECT * FROM project_checkpoints WHERE id=? AND user_id=?').get(checkpointId, userId) as Row | undefined; if (!row) throw new NotFoundError('Checkpoint'); return this.checkpoint(row) }
  listCheckpoints(projectId: string, userId: string) { return (this.db.prepare('SELECT * FROM project_checkpoints WHERE project_id=? AND user_id=? ORDER BY created_at DESC').all(projectId, userId) as Row[]).map(row => this.checkpoint(row)) }
  markCheckpointRestored(checkpointId: string, restoredAt: string) { this.db.prepare('UPDATE project_checkpoints SET restored_at=? WHERE id=?').run(restoredAt, checkpointId) }
  syncExternalModels(models: ExternalModel[], source: 'puter', seenAt: string) {
    const exists = this.db.prepare('SELECT 1 FROM external_models WHERE model_key=?')
    const upsert = this.db.prepare(`INSERT INTO external_models(model_key,source,model_id,provider,name,aliases,context_window,max_tokens,input_cost,output_cost,raw_metadata,first_seen_at,last_seen_at,available) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,1)
      ON CONFLICT(model_key) DO UPDATE SET provider=excluded.provider,name=excluded.name,aliases=excluded.aliases,context_window=excluded.context_window,max_tokens=excluded.max_tokens,input_cost=excluded.input_cost,output_cost=excluded.output_cost,raw_metadata=excluded.raw_metadata,last_seen_at=excluded.last_seen_at,available=1`)
    let created = 0; let updated = 0
    const transaction = this.db.transaction(() => {
      this.db.prepare('UPDATE external_models SET available=0 WHERE source=?').run(source)
      for (const model of models) { if (exists.get(model.key)) updated++; else created++; upsert.run(model.key, source, model.id, model.provider, model.name ?? null, JSON.stringify(model.aliases), model.contextWindow ?? null, model.maxTokens ?? null, model.inputCost ?? null, model.outputCost ?? null, JSON.stringify(model.rawMetadata), model.firstSeenAt, seenAt) }
    })
    transaction()
    const unavailable = Number((this.db.prepare('SELECT COUNT(*) AS count FROM external_models WHERE source=? AND available=0').get(source) as { count: number }).count)
    return { created, updated, unavailable }
  }
  listExternalModels(source: 'puter', options: { provider?: string; available?: boolean; limit?: number; offset?: number } = {}) {
    const clauses = ['source=?']; const values: (string | number)[] = [source]
    if (options.provider) { clauses.push('provider=?'); values.push(options.provider) }
    if (options.available !== undefined) { clauses.push('available=?'); values.push(options.available ? 1 : 0) }
    values.push(Math.min(options.limit ?? 100, 1000), options.offset ?? 0)
    return (this.db.prepare(`SELECT * FROM external_models WHERE ${clauses.join(' AND ')} ORDER BY provider, model_id LIMIT ? OFFSET ?`).all(...values) as Row[]).map(row => this.externalModel(row))
  }
  countExternalModels(source: 'puter') { return Number((this.db.prepare('SELECT COUNT(*) AS count FROM external_models WHERE source=? AND available=1').get(source) as { count: number }).count) }
  getExternalModel(key: string) { const row = this.db.prepare('SELECT * FROM external_models WHERE model_key=?').get(key) as Row | undefined; return row ? this.externalModel(row) : undefined }
  saveModelEvaluation(evaluation: ModelEvaluation) { this.db.prepare('INSERT INTO model_evaluations VALUES (?, ?, ?, ?, ?, ?, ?, ?)').run(evaluation.id, evaluation.modelKey, evaluation.capability, evaluation.score, evaluation.latencyMs ?? null, evaluation.success ? 1 : 0, evaluation.benchmark, evaluation.createdAt) }
  listModelEvaluations(modelKey?: string) { const rows = modelKey ? this.db.prepare('SELECT * FROM model_evaluations WHERE model_key=? ORDER BY created_at DESC').all(modelKey) : this.db.prepare('SELECT * FROM model_evaluations ORDER BY created_at DESC').all(); return (rows as Row[]).map(row => this.modelEvaluation(row)) }
  createBenchmarkCampaign(campaign: BenchmarkCampaign, jobs: BenchmarkJob[]) { this.db.transaction(() => { this.db.prepare('INSERT INTO benchmark_campaigns VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(campaign.id,campaign.userId,campaign.capability,campaign.benchmarkVersion,campaign.status,campaign.totalJobs,campaign.submittedJobs,campaign.verifiedJobs,campaign.failedJobs,campaign.createdAt,campaign.updatedAt); const statement=this.db.prepare('INSERT INTO benchmark_jobs VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'); for(const job of jobs)statement.run(job.id,job.campaignId,job.modelKey,job.status,null,null,null,null,null,null,job.createdAt,job.updatedAt) })(); return campaign }
  getBenchmarkCampaign(campaignId: string, userId?: string) { const row=(userId?this.db.prepare('SELECT * FROM benchmark_campaigns WHERE id=? AND user_id=?').get(campaignId,userId):this.db.prepare('SELECT * FROM benchmark_campaigns WHERE id=?').get(campaignId)) as Row|undefined; if(!row)throw new NotFoundError('Campanha de benchmark'); return this.benchmarkCampaign(row) }
  listBenchmarkCampaigns(userId: string) { return (this.db.prepare('SELECT * FROM benchmark_campaigns WHERE user_id=? ORDER BY updated_at DESC').all(userId) as Row[]).map(row=>this.benchmarkCampaign(row)) }
  updateBenchmarkCampaign(campaign: BenchmarkCampaign) { this.db.prepare('UPDATE benchmark_campaigns SET status=?,submitted_jobs=?,verified_jobs=?,failed_jobs=?,updated_at=? WHERE id=?').run(campaign.status,campaign.submittedJobs,campaign.verifiedJobs,campaign.failedJobs,campaign.updatedAt,campaign.id) }
  listBenchmarkJobs(campaignId: string, options: { status?: BenchmarkJob['status']; limit?: number; offset?: number }={}) { const limit=Math.min(options.limit??100,1000),offset=options.offset??0; const rows=options.status?this.db.prepare('SELECT * FROM benchmark_jobs WHERE campaign_id=? AND status=? ORDER BY created_at LIMIT ? OFFSET ?').all(campaignId,options.status,limit,offset):this.db.prepare('SELECT * FROM benchmark_jobs WHERE campaign_id=? ORDER BY created_at LIMIT ? OFFSET ?').all(campaignId,limit,offset); return (rows as Row[]).map(row=>this.benchmarkJob(row)) }
  getBenchmarkJob(jobId: string) { const row=this.db.prepare('SELECT * FROM benchmark_jobs WHERE id=?').get(jobId) as Row|undefined; return row?this.benchmarkJob(row):undefined }
  updateBenchmarkJob(job: BenchmarkJob) { this.db.prepare('UPDATE benchmark_jobs SET status=?,claim_token_hash=?,claim_expires_at=?,submitted_by=?,output=?,latency_ms=?,error=?,updated_at=? WHERE id=?').run(job.status,job.claimTokenHash??null,job.claimExpiresAt??null,job.submittedBy??null,job.output?JSON.stringify(job.output):null,job.latencyMs??null,job.error??null,job.updatedAt,job.id) }
  createToolExecution(execution: ToolExecution) { this.db.prepare('INSERT INTO tool_executions VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(execution.id,execution.userId,execution.toolId,execution.toolVersion,execution.missionId??null,execution.taskId??null,execution.status,JSON.stringify(execution.input),execution.output?JSON.stringify(execution.output):null,execution.error??null,JSON.stringify(execution.policy),execution.verification?JSON.stringify(execution.verification):null,execution.receipt??null,execution.startedAt,execution.completedAt??null);return execution }
  updateToolExecution(execution: ToolExecution) { this.db.prepare('UPDATE tool_executions SET status=?,output=?,error=?,policy=?,verification=?,receipt=?,completed_at=? WHERE id=? AND user_id=?').run(execution.status,execution.output?JSON.stringify(execution.output):null,execution.error??null,JSON.stringify(execution.policy),execution.verification?JSON.stringify(execution.verification):null,execution.receipt??null,execution.completedAt??null,execution.id,execution.userId) }
  getToolExecution(executionId:string,userId:string) { const row=this.db.prepare('SELECT * FROM tool_executions WHERE id=? AND user_id=?').get(executionId,userId) as Row|undefined;if(!row)throw new NotFoundError('Execução de ferramenta');return this.toolExecution(row) }
  listToolExecutions(userId:string,limit=100) { return (this.db.prepare('SELECT * FROM tool_executions WHERE user_id=? ORDER BY started_at DESC LIMIT ?').all(userId,Math.min(limit,200)) as Row[]).map(row=>this.toolExecution(row)) }
  getCircuitState(resourceKey:string) { const row=this.db.prepare('SELECT * FROM circuit_states WHERE resource_key=?').get(resourceKey) as Row|undefined;return row?this.circuitState(row):undefined }
  upsertCircuitState(state:CircuitState) { this.db.prepare(`INSERT INTO circuit_states VALUES (?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(resource_key) DO UPDATE SET state=excluded.state,failure_count=excluded.failure_count,success_count=excluded.success_count,opened_at=excluded.opened_at,cooldown_until=excluded.cooldown_until,last_error=excluded.last_error,updated_at=excluded.updated_at`).run(state.resourceKey,state.state,state.failureCount,state.successCount,state.openedAt??null,state.cooldownUntil??null,state.lastError??null,state.updatedAt) }
  saveModelHealthSample(sample:ModelHealthSample){this.db.prepare('INSERT INTO model_health_samples VALUES(?,?,?,?,?,?,?)').run(sample.id,sample.modelKey,sample.success?1:0,sample.latencyMs,sample.error??null,sample.source,sample.createdAt)}
  listModelHealthSamples(modelKey:string,limit=100){return(this.db.prepare('SELECT * FROM model_health_samples WHERE model_key=? ORDER BY created_at DESC LIMIT ?').all(modelKey,Math.min(limit,1000)) as Row[]).map(row=>this.modelHealthSample(row))}
  upsertWorker(worker:WorkerRecord){this.db.prepare(`INSERT INTO workers VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,capabilities=excluded.capabilities,status=excluded.status,last_heartbeat_at=excluded.last_heartbeat_at`).run(worker.id,worker.name,JSON.stringify(worker.capabilities),worker.status,worker.lastHeartbeatAt,worker.createdAt)}
  getWorker(workerId:string){const row=this.db.prepare('SELECT * FROM workers WHERE id=?').get(workerId) as Row|undefined;return row?this.worker(row):undefined}
  listWorkers(){return(this.db.prepare('SELECT * FROM workers ORDER BY created_at').all() as Row[]).map(row=>this.worker(row))}
  claimReadyTask(workerId:string,capabilities:string[],tokenHash:string,expiresAt:string,timestamp:string){return this.db.transaction(()=>{const rows=this.db.prepare(`SELECT t.* FROM mission_tasks t JOIN missions m ON m.id=t.mission_id LEFT JOIN task_leases l ON l.task_id=t.id WHERE t.status='pending' AND m.status IN ('pending','running') AND l.task_id IS NULL ORDER BY m.created_at,t.created_at LIMIT 200`).all() as Row[];for(const row of rows){const candidate=this.missionTask(row);if(!capabilities.includes('*')&&!capabilities.includes(candidate.kind)&&!(candidate.kind.startsWith('tool:')&&capabilities.includes('tool')))continue;const statuses=this.db.prepare('SELECT task_key,status FROM mission_tasks WHERE mission_id=?').all(candidate.missionId) as {task_key:string;status:string}[];const completed=new Set(statuses.filter(item=>item.status==='completed').map(item=>item.task_key));if(!candidate.dependsOn.every(dep=>completed.has(dep)))continue;const lease:TaskLease={taskId:candidate.id,missionId:candidate.missionId,workerId,tokenHash,expiresAt,heartbeatAt:timestamp,createdAt:timestamp};this.db.prepare('INSERT INTO task_leases VALUES(?,?,?,?,?,?,?)').run(lease.taskId,lease.missionId,workerId,tokenHash,expiresAt,timestamp,timestamp);this.db.prepare(`UPDATE mission_tasks SET status='running',attempts=attempts+1,progress=MAX(progress,1),updated_at=? WHERE id=?`).run(timestamp,candidate.id);this.db.prepare(`UPDATE missions SET status='running',updated_at=? WHERE id=?`).run(timestamp,candidate.missionId);const task=this.getMissionTask(candidate.id)!;const missionRow=this.db.prepare('SELECT * FROM missions WHERE id=?').get(candidate.missionId) as Row;return{mission:this.mission(missionRow),task,lease}}return undefined})()}
  getTaskLease(taskId:string){const row=this.db.prepare('SELECT * FROM task_leases WHERE task_id=?').get(taskId) as Row|undefined;return row?this.taskLease(row):undefined}
  heartbeatTaskLease(taskId:string,workerId:string,tokenHash:string,expiresAt:string,timestamp:string){const lease=this.getTaskLease(taskId);if(!lease||lease.workerId!==workerId||lease.tokenHash!==tokenHash)throw new NotFoundError('Lease de tarefa');this.db.prepare('UPDATE task_leases SET expires_at=?,heartbeat_at=? WHERE task_id=?').run(expiresAt,timestamp,taskId);return{...lease,expiresAt,heartbeatAt:timestamp}}
  releaseTaskLease(taskId:string,workerId:string){this.db.prepare('DELETE FROM task_leases WHERE task_id=? AND worker_id=?').run(taskId,workerId)}
  recoverExpiredTaskLeases(timestamp:string){let recovered=0,failed=0;this.db.transaction(()=>{const rows=this.db.prepare('SELECT l.task_id,t.attempts,t.max_attempts,t.mission_id FROM task_leases l JOIN mission_tasks t ON t.id=l.task_id WHERE l.expires_at<=?').all(timestamp) as {task_id:string;attempts:number;max_attempts:number;mission_id:string}[];for(const row of rows){if(row.attempts<row.max_attempts){this.db.prepare(`UPDATE mission_tasks SET status='pending',error='Worker lease expired',updated_at=? WHERE id=?`).run(timestamp,row.task_id);recovered++}else{this.db.prepare(`UPDATE mission_tasks SET status='failed',error='Worker lease expired after maximum attempts',updated_at=? WHERE id=?`).run(timestamp,row.task_id);this.db.prepare(`UPDATE missions SET status='failed',updated_at=? WHERE id=?`).run(timestamp,row.mission_id);failed++}this.db.prepare('DELETE FROM task_leases WHERE task_id=?').run(row.task_id)}})();return{recovered,failed}}
  findCompletedToolExecutionByTask(taskId:string){const row=this.db.prepare(`SELECT * FROM tool_executions WHERE task_id=? AND status='completed' ORDER BY completed_at DESC LIMIT 1`).get(taskId) as Row|undefined;return row?this.toolExecution(row):undefined}
  createPuterExecutionReport(report:PuterExecutionReport){this.db.prepare('INSERT INTO puter_execution_reports VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(report.id,report.userId,report.conversationId,report.modelKey,report.provider,report.modelId,report.promptHash,report.responseHash,report.durationMs,JSON.stringify(report.fallbackChain),report.trust,report.receipt,report.createdAt);return report}
  listPuterExecutionReports(userId:string,limit=100){return(this.db.prepare('SELECT * FROM puter_execution_reports WHERE user_id=? ORDER BY created_at DESC LIMIT ?').all(userId,Math.min(limit,200)) as Row[]).map(row=>this.puterExecutionReport(row))}
  createApproval(request:ApprovalRequest){this.db.prepare('INSERT INTO approvals VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(request.id,request.userId,request.missionId??null,request.taskId??null,request.action,request.risk,request.rationale,request.status,request.expiresAt,request.requestedAt,request.decidedAt??null,request.consumedAt??null);return request}
  getApproval(approvalId:string,userId:string){const row=this.db.prepare('SELECT * FROM approvals WHERE id=? AND user_id=?').get(approvalId,userId) as Row|undefined;if(!row)throw new NotFoundError('Aprovação');return this.approval(row)}
  listApprovals(userId:string,status?:ApprovalRequest['status']){const rows=status?this.db.prepare('SELECT * FROM approvals WHERE user_id=? AND status=? ORDER BY requested_at DESC').all(userId,status):this.db.prepare('SELECT * FROM approvals WHERE user_id=? ORDER BY requested_at DESC').all(userId);return(rows as Row[]).map(row=>this.approval(row))}
  updateApproval(request:ApprovalRequest){this.db.prepare('UPDATE approvals SET status=?,decided_at=?,consumed_at=? WHERE id=? AND user_id=?').run(request.status,request.decidedAt??null,request.consumedAt??null,request.id,request.userId)}
  getUserSettings(userId:string){const row=this.db.prepare('SELECT data FROM user_settings WHERE user_id=?').get(userId) as {data:string}|undefined;return row?json<Record<string,unknown>>(row.data)??{}:{}}
  upsertUserSettings(userId:string,settings:Record<string,unknown>,updatedAt:string){this.db.prepare(`INSERT INTO user_settings VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at`).run(userId,JSON.stringify(settings),updatedAt);return settings}
  createEvidenceSource(source:EvidenceSource){this.db.prepare('INSERT INTO evidence_sources VALUES(?,?,?,?,?,?,?,?,?,?)').run(source.id,source.userId,source.projectId??null,source.url,source.title,source.publisher??null,source.publishedAt??null,source.retrievedAt,source.contentHash??null,source.status);return source}
  listEvidenceSources(userId:string,projectId?:string){const rows=projectId?this.db.prepare('SELECT * FROM evidence_sources WHERE user_id=? AND project_id=? ORDER BY retrieved_at DESC').all(userId,projectId):this.db.prepare('SELECT * FROM evidence_sources WHERE user_id=? ORDER BY retrieved_at DESC').all(userId);return(rows as Row[]).map(row=>this.evidenceSource(row))}
  createKnowledgeClaim(claim:KnowledgeClaim){this.db.prepare('INSERT INTO knowledge_claims VALUES(?,?,?,?,?,?,?,?)').run(claim.id,claim.userId,claim.projectId??null,claim.statement,claim.state,claim.confidence,claim.createdAt,claim.updatedAt);return claim}
  listKnowledgeClaims(userId:string,projectId?:string){const rows=projectId?this.db.prepare('SELECT * FROM knowledge_claims WHERE user_id=? AND project_id=? ORDER BY updated_at DESC').all(userId,projectId):this.db.prepare('SELECT * FROM knowledge_claims WHERE user_id=? ORDER BY updated_at DESC').all(userId);return(rows as Row[]).map(row=>this.knowledgeClaim(row))}
  getKnowledgeClaim(claimId:string,userId:string){const row=this.db.prepare('SELECT * FROM knowledge_claims WHERE id=? AND user_id=?').get(claimId,userId) as Row|undefined;if(!row)throw new NotFoundError('Claim');return this.knowledgeClaim(row)}
  updateKnowledgeClaim(claim:KnowledgeClaim){this.db.prepare('UPDATE knowledge_claims SET state=?,confidence=?,updated_at=? WHERE id=? AND user_id=?').run(claim.state,claim.confidence,claim.updatedAt,claim.id,claim.userId)}
  createEvidenceLink(link:EvidenceLink){this.db.prepare('INSERT INTO evidence_links VALUES(?,?,?,?,?,?,?,?)').run(link.id,link.userId,link.claimId,link.sourceId,link.relation,link.quote??null,link.strength,link.createdAt);return link}
  listEvidenceLinks(userId:string,claimId?:string){const rows=claimId?this.db.prepare('SELECT * FROM evidence_links WHERE user_id=? AND claim_id=? ORDER BY created_at').all(userId,claimId):this.db.prepare('SELECT * FROM evidence_links WHERE user_id=? ORDER BY created_at DESC').all(userId);return(rows as Row[]).map(row=>this.evidenceLink(row))}
  upsertCapabilityManifest(manifest:CapabilityManifest){this.db.prepare(`INSERT INTO capability_manifests VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,version=excluded.version,vendor=excluded.vendor,type=excluded.type,capabilities=excluded.capabilities,inputs=excluded.inputs,outputs=excluded.outputs,execution_methods=excluded.execution_methods,authentication=excluded.authentication,permissions=excluded.permissions,dependencies=excluded.dependencies,cost=excluded.cost,latency=excluded.latency,limits=excluded.limits,license=excluded.license,risk=excluded.risk,compatibility=excluded.compatibility,status=excluded.status,reliability=excluded.reliability,evidence_count=excluded.evidence_count,metadata=excluded.metadata,updated_at=excluded.updated_at`).run(manifest.id,manifest.name,manifest.version,manifest.vendor,manifest.type,JSON.stringify(manifest.capabilities),JSON.stringify(manifest.inputs),JSON.stringify(manifest.outputs),JSON.stringify(manifest.executionMethods),JSON.stringify(manifest.authentication),JSON.stringify(manifest.permissions),JSON.stringify(manifest.dependencies),manifest.cost?JSON.stringify(manifest.cost):null,manifest.latency?JSON.stringify(manifest.latency):null,JSON.stringify(manifest.limits),manifest.license,manifest.risk,JSON.stringify(manifest.compatibility),manifest.status,manifest.reliability,manifest.evidenceCount,JSON.stringify(manifest.metadata),manifest.createdAt,manifest.updatedAt);return manifest}
  getCapabilityManifest(manifestId:string){const row=this.db.prepare('SELECT * FROM capability_manifests WHERE id=?').get(manifestId) as Row|undefined;return row?this.capabilityManifest(row):undefined}
  listCapabilityManifests(options:{status?:CapabilityManifest['status'];type?:CapabilityManifest['type'];capability?:string}={}){const rows=this.db.prepare('SELECT * FROM capability_manifests ORDER BY name,version').all() as Row[];return rows.map(row=>this.capabilityManifest(row)).filter(item=>(!options.status||item.status===options.status)&&(!options.type||item.type===options.type)&&(!options.capability||item.capabilities.includes(options.capability)))}
  createDivineProject(project:DivineProject){this.db.prepare('INSERT INTO divine_projects VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(project.id,project.userId,project.projectId,project.missionId,project.name,project.brief,project.target,project.format,project.executionPolicy,JSON.stringify(project.deviceProfile),project.status,project.createdAt,project.updatedAt);return project}
  getDivineProject(divineId:string,userId:string){const row=this.db.prepare('SELECT * FROM divine_projects WHERE id=? AND user_id=?').get(divineId,userId) as Row|undefined;if(!row)throw new NotFoundError('Projeto Divine Engine');return this.divineProject(row)}
  listDivineProjects(userId:string){return(this.db.prepare('SELECT * FROM divine_projects WHERE user_id=? ORDER BY updated_at DESC').all(userId) as Row[]).map(row=>this.divineProject(row))}
  updateDivineProject(project:DivineProject){this.db.prepare('UPDATE divine_projects SET status=?,device_profile=?,updated_at=? WHERE id=? AND user_id=?').run(project.status,JSON.stringify(project.deviceProfile),project.updatedAt,project.id,project.userId)}
  getDivineEngineSettings(projectId:string,userId:string){const row=this.db.prepare('SELECT * FROM divine_engine_settings WHERE divine_project_id=? AND user_id=?').get(projectId,userId) as Row|undefined;return row?this.divineEngineSettings(row):undefined}
  upsertDivineEngineSettings(settings:DivineEngineSettings){this.db.prepare(`INSERT INTO divine_engine_settings VALUES(?,?,?,?,?,?) ON CONFLICT(divine_project_id) DO UPDATE SET values_json=excluded.values_json,preset=excluded.preset,version=excluded.version,updated_at=excluded.updated_at`).run(settings.divineProjectId,settings.userId,JSON.stringify(settings.values),settings.preset,settings.version,settings.updatedAt);return settings}
  createDivineEngineCommand(command:DivineEngineCommand){this.db.prepare('INSERT INTO divine_engine_commands VALUES(?,?,?,?,?,?,?,?,?)').run(command.id,command.userId,command.divineProjectId,command.message,JSON.stringify(command.attachmentFileIds),command.status,JSON.stringify(command.operations),command.createdAt,command.updatedAt);return command}
  listDivineEngineCommands(projectId:string,userId:string){return(this.db.prepare('SELECT * FROM divine_engine_commands WHERE divine_project_id=? AND user_id=? ORDER BY created_at').all(projectId,userId) as Row[]).map(row=>this.divineEngineCommand(row))}
  createHsdsSession(session:HsdsSession){this.db.prepare('INSERT INTO hsds_sessions VALUES(?,?,?,?,?,?,?,?,?)').run(session.id,session.userId,session.projectId,session.divineProjectId,session.status,JSON.stringify(session.profile),JSON.stringify(session.state),session.createdAt,session.updatedAt);return session}
  getHsdsSession(sessionId:string,userId:string){const row=this.db.prepare('SELECT * FROM hsds_sessions WHERE id=? AND user_id=?').get(sessionId,userId) as Row|undefined;if(!row)throw new NotFoundError('Sessão HSDS');return this.hsdsSession(row)}
  listHsdsSessions(userId:string,projectId?:string){const rows=projectId?this.db.prepare('SELECT * FROM hsds_sessions WHERE user_id=? AND project_id=? ORDER BY updated_at DESC').all(userId,projectId):this.db.prepare('SELECT * FROM hsds_sessions WHERE user_id=? ORDER BY updated_at DESC').all(userId);return(rows as Row[]).map(row=>this.hsdsSession(row))}
  updateHsdsSession(session:HsdsSession){this.db.prepare('UPDATE hsds_sessions SET status=?,profile=?,state=?,updated_at=? WHERE id=? AND user_id=?').run(session.status,JSON.stringify(session.profile),JSON.stringify(session.state),session.updatedAt,session.id,session.userId)}
  createArtifact(record:ArtifactRecord){this.db.prepare('INSERT INTO artifact_records VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(record.id,record.userId,record.projectId,record.fileId,record.type,record.version,record.parentId??null,record.producer,JSON.stringify(record.inputs),JSON.stringify(record.dependencies),JSON.stringify(record.verification),JSON.stringify(record.metadata),record.license,record.status,record.createdAt);return record}
  getArtifact(artifactId:string,userId:string){const row=this.db.prepare('SELECT * FROM artifact_records WHERE id=? AND user_id=?').get(artifactId,userId) as Row|undefined;if(!row)throw new NotFoundError('Artifact');return this.artifact(row)}
  listArtifacts(userId:string,projectId?:string){const rows=projectId?this.db.prepare('SELECT * FROM artifact_records WHERE user_id=? AND project_id=? ORDER BY created_at DESC,rowid DESC').all(userId,projectId):this.db.prepare('SELECT * FROM artifact_records WHERE user_id=? ORDER BY created_at DESC,rowid DESC').all(userId);return(rows as Row[]).map(row=>this.artifact(row))}
  updateArtifact(record:ArtifactRecord){this.db.prepare('UPDATE artifact_records SET status=?,verification=?,metadata=? WHERE id=? AND user_id=?').run(record.status,JSON.stringify(record.verification),JSON.stringify(record.metadata),record.id,record.userId)}
  createDivineOsProject(project:DivineOsProject){this.db.prepare('INSERT INTO divine_os_projects VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(project.id,project.userId,project.projectId,project.missionId,project.name,project.variant,project.status,JSON.stringify(project.architecture),JSON.stringify(project.baseManifest),JSON.stringify(project.configuration),JSON.stringify(project.compliance),project.createdAt,project.updatedAt);return project}
  getDivineOsProject(projectId:string,userId:string){const row=this.db.prepare('SELECT * FROM divine_os_projects WHERE id=? AND user_id=?').get(projectId,userId) as Row|undefined;if(!row)throw new NotFoundError('Projeto Divine OS');return this.divineOsProject(row)}
  listDivineOsProjects(userId:string){return(this.db.prepare('SELECT * FROM divine_os_projects WHERE user_id=? ORDER BY updated_at DESC').all(userId) as Row[]).map(row=>this.divineOsProject(row))}
  updateDivineOsProject(project:DivineOsProject){this.db.prepare('UPDATE divine_os_projects SET status=?,base_manifest=?,configuration=?,compliance=?,updated_at=? WHERE id=? AND user_id=?').run(project.status,JSON.stringify(project.baseManifest),JSON.stringify(project.configuration),JSON.stringify(project.compliance),project.updatedAt,project.id,project.userId)}
  createDivineOsModule(module:DivineOsModule){this.db.prepare('INSERT INTO divine_os_modules VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(module.id,module.userId,module.divineOsProjectId,module.name,module.version,JSON.stringify(module.capabilities),JSON.stringify(module.dependencies),JSON.stringify(module.permissions),module.status,JSON.stringify(module.manifest),module.createdAt,module.updatedAt);return module}
  listDivineOsModules(projectId:string,userId:string){return(this.db.prepare('SELECT * FROM divine_os_modules WHERE divine_os_project_id=? AND user_id=? ORDER BY rowid').all(projectId,userId) as Row[]).map(row=>this.divineOsModule(row))}

  createUser(user: StoredUser) { try { this.db.prepare('INSERT INTO users VALUES (?, ?, ?, ?, ?)').run(user.id, user.email, user.name, user.passwordHash, user.createdAt); return user } catch { throw new AppError('Este e-mail já está cadastrado.', 409, 'EMAIL_EXISTS') } }
  findUserByEmail(email: string) { const row = this.db.prepare('SELECT * FROM users WHERE email=?').get(email) as Row | undefined; return row ? this.user(row) : undefined }
  findUserById(userId: string) { const row = this.db.prepare('SELECT * FROM users WHERE id=?').get(userId) as Row | undefined; return row ? this.user(row) : undefined }
  saveRefreshToken(token: StoredRefreshToken) { this.db.prepare('INSERT INTO refresh_tokens VALUES (?, ?, ?, ?, ?, ?)').run(token.id, token.userId, token.tokenHash, token.expiresAt, token.revokedAt ?? null, token.createdAt) }
  findRefreshToken(tokenHash: string) { const row = this.db.prepare('SELECT * FROM refresh_tokens WHERE token_hash=?').get(tokenHash) as Row | undefined; return row ? this.refresh(row) : undefined }
  revokeRefreshToken(tokenHash: string) { this.db.prepare('UPDATE refresh_tokens SET revoked_at=? WHERE token_hash=?').run(now(), tokenHash) }
  revokeUserRefreshTokens(userId: string) { this.db.prepare('UPDATE refresh_tokens SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL').run(now(), userId) }
  updateUserPassword(userId:string,passwordHash:string){this.db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(passwordHash,userId)}
  savePasswordResetToken(token:StoredPasswordResetToken){this.db.prepare('INSERT INTO password_reset_tokens VALUES(?,?,?,?,?,?)').run(token.id,token.userId,token.tokenHash,token.expiresAt,token.usedAt??null,token.createdAt)}
  findPasswordResetToken(tokenHash:string){const row=this.db.prepare('SELECT * FROM password_reset_tokens WHERE token_hash=?').get(tokenHash) as Row|undefined;return row?this.passwordReset(row):undefined}
  consumePasswordResetToken(tokenHash:string,usedAt:string){this.db.prepare('UPDATE password_reset_tokens SET used_at=? WHERE token_hash=?').run(usedAt,tokenHash)}
  audit(event: AuditEvent) { this.db.prepare('INSERT INTO audit_events VALUES (?, ?, ?, ?, ?, ?)').run(event.id, event.userId ?? null, event.action, event.resource ?? null, event.metadata ? JSON.stringify(event.metadata) : null, event.createdAt) }
  listAudit(userId: string, limit = 100) { return (this.db.prepare('SELECT * FROM audit_events WHERE user_id=? ORDER BY created_at DESC LIMIT ?').all(userId, limit) as Row[]).map(row => ({ id: String(row.id), userId: row.user_id ? String(row.user_id) : undefined, action: String(row.action), resource: row.resource ? String(row.resource) : undefined, metadata: json<Record<string, unknown>>(row.metadata as string | null), createdAt: String(row.created_at) })) }
  close() { this.db.close() }

  private hsdsSession(r:Row):HsdsSession{return{id:String(r.id),userId:String(r.user_id),projectId:String(r.project_id),divineProjectId:String(r.divine_project_id),status:String(r.status) as HsdsSession['status'],profile:json<HsdsSession['profile']>(String(r.profile))!,state:json<HsdsSession['state']>(String(r.state))!,createdAt:String(r.created_at),updatedAt:String(r.updated_at)}}
  private conversation(r: Row): Conversation { return { id: String(r.id), userId: String(r.user_id), title: String(r.title), projectId: r.project_id ? String(r.project_id) : undefined, createdAt: String(r.created_at), updatedAt: String(r.updated_at) } }
  private message(r: Row): Message { return { id: String(r.id), conversationId: String(r.conversation_id), role: String(r.role) as Message['role'], content: String(r.content), metadata: json(r.metadata as string | null), createdAt: String(r.created_at) } }
  private project(r: Row): Project { return { id: String(r.id), userId: String(r.user_id), name: String(r.name), description: String(r.description), status: String(r.status) as Project['status'], createdAt: String(r.created_at), updatedAt: String(r.updated_at) } }
  private memory(r: Row): Memory { return { id: String(r.id), userId: String(r.user_id), projectId: r.project_id ? String(r.project_id) : undefined, content: String(r.content), kind: String(r.kind) as Memory['kind'], importance: Number(r.importance), createdAt: String(r.created_at) } }
  private file(r: Row): FileAsset { return { id: String(r.id), userId: String(r.user_id), projectId: r.project_id ? String(r.project_id) : undefined, name: String(r.name), mimeType: String(r.mime_type), size: Number(r.size), checksum: String(r.checksum), storagePath: String(r.storage_path), createdAt: String(r.created_at) } }
  private mission(r: Row): Mission { return { id: String(r.id), userId: String(r.user_id), projectId: r.project_id ? String(r.project_id) : undefined, goal: String(r.goal), status: String(r.status) as Mission['status'], progress: Number(r.progress), createdAt: String(r.created_at), updatedAt: String(r.updated_at) } }
  private missionContract(r:Row):MissionContract{return{missionId:String(r.mission_id),objective:String(r.objective),userIntent:String(r.user_intent),constraints:json<string[]>(String(r.constraints))??[],requiredCapabilities:json<string[]>(String(r.required_capabilities))??[],availableResources:json<string[]>(String(r.available_resources))??[],risks:json<string[]>(String(r.risks))??[],successCriteria:json<string[]>(String(r.success_criteria))??[],verificationRequirements:json<string[]>(String(r.verification_requirements))??[],finalDeliverable:String(r.final_deliverable),autonomy:String(r.autonomy) as MissionContract['autonomy'],phase:String(r.phase) as MissionContract['phase'],createdAt:String(r.created_at),updatedAt:String(r.updated_at)}}
  private missionTask(r: Row): MissionTask { return { id: String(r.id), missionId: String(r.mission_id), key: String(r.task_key), title: String(r.title), kind: String(r.kind), status: String(r.status) as MissionTask['status'], dependsOn: json<string[]>(String(r.depends_on)) ?? [], input: json<Record<string, unknown>>(String(r.input)) ?? {}, output: json<Record<string, unknown>>(r.output as string | null), error: r.error ? String(r.error) : undefined, progress: Number(r.progress), attempts: Number(r.attempts), maxAttempts: Number(r.max_attempts), createdAt: String(r.created_at), updatedAt: String(r.updated_at) } }
  private missionEvent(r: Row): MissionEvent { return { id: String(r.id), missionId: String(r.mission_id), taskId: r.task_id ? String(r.task_id) : undefined, type: String(r.type), payload: json<Record<string, unknown>>(String(r.payload)) ?? {}, createdAt: String(r.created_at) } }
  private checkpoint(r: Row): ProjectCheckpoint { return { id: String(r.id), userId: String(r.user_id), projectId: String(r.project_id), label: String(r.label), snapshot: json<Record<string, unknown>>(String(r.snapshot)) ?? {}, createdAt: String(r.created_at), restoredAt: r.restored_at ? String(r.restored_at) : undefined } }
  private externalModel(r: Row): ExternalModel { return { key: String(r.model_key), source: 'puter', id: String(r.model_id), provider: String(r.provider), name: r.name ? String(r.name) : undefined, aliases: json<string[]>(String(r.aliases)) ?? [], contextWindow: r.context_window === null ? undefined : Number(r.context_window), maxTokens: r.max_tokens === null ? undefined : Number(r.max_tokens), inputCost: r.input_cost === null ? undefined : Number(r.input_cost), outputCost: r.output_cost === null ? undefined : Number(r.output_cost), rawMetadata: json<Record<string, unknown>>(String(r.raw_metadata)) ?? {}, firstSeenAt: String(r.first_seen_at), lastSeenAt: String(r.last_seen_at), available: Boolean(r.available) } }
  private modelEvaluation(r: Row): ModelEvaluation { return { id: String(r.id), modelKey: String(r.model_key), capability: String(r.capability) as ModelEvaluation['capability'], score: Number(r.score), latencyMs: r.latency_ms === null ? undefined : Number(r.latency_ms), success: Boolean(r.success), benchmark: String(r.benchmark), createdAt: String(r.created_at) } }
  private benchmarkCampaign(r: Row): BenchmarkCampaign { return { id:String(r.id),userId:String(r.user_id),capability:String(r.capability) as BenchmarkCampaign['capability'],benchmarkVersion:String(r.benchmark_version),status:String(r.status) as BenchmarkCampaign['status'],totalJobs:Number(r.total_jobs),submittedJobs:Number(r.submitted_jobs),verifiedJobs:Number(r.verified_jobs),failedJobs:Number(r.failed_jobs),createdAt:String(r.created_at),updatedAt:String(r.updated_at) } }
  private benchmarkJob(r: Row): BenchmarkJob { return { id:String(r.id),campaignId:String(r.campaign_id),modelKey:String(r.model_key),status:String(r.status) as BenchmarkJob['status'],claimTokenHash:r.claim_token_hash?String(r.claim_token_hash):undefined,claimExpiresAt:r.claim_expires_at?String(r.claim_expires_at):undefined,submittedBy:r.submitted_by?String(r.submitted_by):undefined,output:json<Record<string,unknown>>(r.output as string|null),latencyMs:r.latency_ms===null?undefined:Number(r.latency_ms),error:r.error?String(r.error):undefined,createdAt:String(r.created_at),updatedAt:String(r.updated_at) } }
  private toolExecution(r:Row):ToolExecution{return{id:String(r.id),userId:String(r.user_id),toolId:String(r.tool_id),toolVersion:String(r.tool_version),missionId:r.mission_id?String(r.mission_id):undefined,taskId:r.task_id?String(r.task_id):undefined,status:String(r.status) as ToolExecution['status'],input:json<Record<string,unknown>>(String(r.input))??{},output:json<Record<string,unknown>>(r.output as string|null),error:r.error?String(r.error):undefined,policy:json<Record<string,unknown>>(String(r.policy))??{},verification:json<Record<string,unknown>>(r.verification as string|null),receipt:r.receipt?String(r.receipt):undefined,startedAt:String(r.started_at),completedAt:r.completed_at?String(r.completed_at):undefined}}
  private circuitState(r:Row):CircuitState{return{resourceKey:String(r.resource_key),state:String(r.state) as CircuitState['state'],failureCount:Number(r.failure_count),successCount:Number(r.success_count),openedAt:r.opened_at?String(r.opened_at):undefined,cooldownUntil:r.cooldown_until?String(r.cooldown_until):undefined,lastError:r.last_error?String(r.last_error):undefined,updatedAt:String(r.updated_at)}}
  private modelHealthSample(r:Row):ModelHealthSample{return{id:String(r.id),modelKey:String(r.model_key),success:Boolean(r.success),latencyMs:Number(r.latency_ms),error:r.error?String(r.error):undefined,source:String(r.source) as ModelHealthSample['source'],createdAt:String(r.created_at)}}
  private worker(r:Row):WorkerRecord{return{id:String(r.id),name:String(r.name),capabilities:json<string[]>(String(r.capabilities))??[],status:String(r.status) as WorkerRecord['status'],lastHeartbeatAt:String(r.last_heartbeat_at),createdAt:String(r.created_at)}}
  private taskLease(r:Row):TaskLease{return{taskId:String(r.task_id),missionId:String(r.mission_id),workerId:String(r.worker_id),tokenHash:String(r.token_hash),expiresAt:String(r.expires_at),heartbeatAt:String(r.heartbeat_at),createdAt:String(r.created_at)}}
  private puterExecutionReport(r:Row):PuterExecutionReport{return{id:String(r.id),userId:String(r.user_id),conversationId:String(r.conversation_id),modelKey:String(r.model_key),provider:String(r.provider),modelId:String(r.model_id),promptHash:String(r.prompt_hash),responseHash:String(r.response_hash),durationMs:Number(r.duration_ms),fallbackChain:json<PuterExecutionReport['fallbackChain']>(String(r.fallback_chain))??[],trust:'client-reported',receipt:String(r.receipt),createdAt:String(r.created_at)}}
  private approval(r:Row):ApprovalRequest{return{id:String(r.id),userId:String(r.user_id),missionId:r.mission_id?String(r.mission_id):undefined,taskId:r.task_id?String(r.task_id):undefined,action:String(r.action),risk:String(r.risk) as ApprovalRequest['risk'],rationale:String(r.rationale),status:String(r.status) as ApprovalRequest['status'],expiresAt:String(r.expires_at),requestedAt:String(r.requested_at),decidedAt:r.decided_at?String(r.decided_at):undefined,consumedAt:r.consumed_at?String(r.consumed_at):undefined}}
  private evidenceSource(r:Row):EvidenceSource{return{id:String(r.id),userId:String(r.user_id),projectId:r.project_id?String(r.project_id):undefined,url:String(r.url),title:String(r.title),publisher:r.publisher?String(r.publisher):undefined,publishedAt:r.published_at?String(r.published_at):undefined,retrievedAt:String(r.retrieved_at),contentHash:r.content_hash?String(r.content_hash):undefined,status:String(r.status) as EvidenceSource['status']}}
  private knowledgeClaim(r:Row):KnowledgeClaim{return{id:String(r.id),userId:String(r.user_id),projectId:r.project_id?String(r.project_id):undefined,statement:String(r.statement),state:String(r.state) as KnowledgeClaim['state'],confidence:Number(r.confidence),createdAt:String(r.created_at),updatedAt:String(r.updated_at)}}
  private evidenceLink(r:Row):EvidenceLink{return{id:String(r.id),userId:String(r.user_id),claimId:String(r.claim_id),sourceId:String(r.source_id),relation:String(r.relation) as EvidenceLink['relation'],quote:r.quote?String(r.quote):undefined,strength:Number(r.strength),createdAt:String(r.created_at)}}
  private capabilityManifest(r:Row):CapabilityManifest{return{id:String(r.id),name:String(r.name),version:String(r.version),vendor:String(r.vendor),type:String(r.type) as CapabilityManifest['type'],capabilities:json<string[]>(String(r.capabilities))??[],inputs:json<Record<string,unknown>>(String(r.inputs))??{},outputs:json<Record<string,unknown>>(String(r.outputs))??{},executionMethods:json<string[]>(String(r.execution_methods))??[],authentication:json<string[]>(String(r.authentication))??[],permissions:json<string[]>(String(r.permissions))??[],dependencies:json<string[]>(String(r.dependencies))??[],cost:json<Record<string,unknown>>(r.cost as string|null),latency:json<Record<string,unknown>>(r.latency as string|null),limits:json<Record<string,unknown>>(String(r.limits))??{},license:String(r.license),risk:String(r.risk) as CapabilityManifest['risk'],compatibility:json<string[]>(String(r.compatibility))??[],status:String(r.status) as CapabilityManifest['status'],reliability:Number(r.reliability),evidenceCount:Number(r.evidence_count),metadata:json<Record<string,unknown>>(String(r.metadata))??{},createdAt:String(r.created_at),updatedAt:String(r.updated_at)}}
  private divineEngineSettings(r:Row):DivineEngineSettings{return{divineProjectId:String(r.divine_project_id),userId:String(r.user_id),values:json<Record<string,unknown>>(String(r.values_json))??{},preset:String(r.preset),version:Number(r.version),updatedAt:String(r.updated_at)}}
  private divineEngineCommand(r:Row):DivineEngineCommand{return{id:String(r.id),userId:String(r.user_id),divineProjectId:String(r.divine_project_id),message:String(r.message),attachmentFileIds:json<string[]>(String(r.attachment_file_ids))??[],status:String(r.status) as DivineEngineCommand['status'],operations:json<Record<string,unknown>[]>(String(r.operations))??[],createdAt:String(r.created_at),updatedAt:String(r.updated_at)}}
  private artifact(r:Row):ArtifactRecord{return{id:String(r.id),userId:String(r.user_id),projectId:String(r.project_id),fileId:String(r.file_id),type:String(r.type),version:Number(r.version),parentId:r.parent_id?String(r.parent_id):undefined,producer:String(r.producer),inputs:json<string[]>(String(r.inputs))??[],dependencies:json<string[]>(String(r.dependencies))??[],verification:json<Record<string,unknown>>(String(r.verification))??{},metadata:json<Record<string,unknown>>(String(r.metadata))??{},license:String(r.license),status:String(r.status) as ArtifactRecord['status'],createdAt:String(r.created_at)}}
  private divineProject(r:Row):DivineProject{return{id:String(r.id),userId:String(r.user_id),projectId:String(r.project_id),missionId:String(r.mission_id),name:String(r.name),brief:String(r.brief),target:String(r.target) as DivineProject['target'],format:'snb-divine-project-v1',executionPolicy:String(r.execution_policy) as DivineProject['executionPolicy'],deviceProfile:json<Record<string,unknown>>(String(r.device_profile))??{},status:String(r.status) as DivineProject['status'],createdAt:String(r.created_at),updatedAt:String(r.updated_at)}}
  private divineOsProject(r:Row):DivineOsProject{return{id:String(r.id),userId:String(r.user_id),projectId:String(r.project_id),missionId:String(r.mission_id),name:String(r.name),variant:String(r.variant) as DivineOsProject['variant'],status:String(r.status) as DivineOsProject['status'],architecture:json<string[]>(String(r.architecture))??[],baseManifest:json<Record<string,unknown>>(String(r.base_manifest))??{},configuration:json<Record<string,unknown>>(String(r.configuration))??{},compliance:json<Record<string,unknown>>(String(r.compliance))??{},createdAt:String(r.created_at),updatedAt:String(r.updated_at)}}
  private divineOsModule(r:Row):DivineOsModule{return{id:String(r.id),userId:String(r.user_id),divineOsProjectId:String(r.divine_os_project_id),name:String(r.name),version:String(r.version),capabilities:json<string[]>(String(r.capabilities))??[],dependencies:json<string[]>(String(r.dependencies))??[],permissions:json<string[]>(String(r.permissions))??[],status:String(r.status) as DivineOsModule['status'],manifest:json<Record<string,unknown>>(String(r.manifest))??{},createdAt:String(r.created_at),updatedAt:String(r.updated_at)}}
  private user(r: Row): StoredUser { return { id: String(r.id), email: String(r.email), name: String(r.name), passwordHash: String(r.password_hash), createdAt: String(r.created_at) } }
  private refresh(r: Row): StoredRefreshToken { return { id: String(r.id), userId: String(r.user_id), tokenHash: String(r.token_hash), expiresAt: String(r.expires_at), revokedAt: r.revoked_at ? String(r.revoked_at) : undefined, createdAt: String(r.created_at) } }
  private passwordReset(r:Row):StoredPasswordResetToken{return{id:String(r.id),userId:String(r.user_id),tokenHash:String(r.token_hash),expiresAt:String(r.expires_at),usedAt:r.used_at?String(r.used_at):undefined,createdAt:String(r.created_at)}}
}
