import type { ArtifactRecord } from '../domain.js'
import { AppError } from '../lib/errors.js'
import { id, now } from '../lib/id.js'
import type { Store } from '../repositories/store.js'

export class ArtifactGraphService{
 constructor(private store:Store){}
 register(userId:string,input:{projectId:string;fileId:string;type:string;producer:string;parentId?:string;inputs?:string[];dependencies?:string[];verification:Record<string,unknown>;metadata?:Record<string,unknown>;license?:string}){this.store.getProject(input.projectId,userId);const file=this.store.getFile(input.fileId,userId);if(file.projectId!==input.projectId)throw new AppError('Arquivo não pertence ao projeto.',409,'ARTIFACT_PROJECT_MISMATCH');const parent=input.parentId?this.store.getArtifact(input.parentId,userId):undefined;if(parent&&parent.projectId!==input.projectId)throw new AppError('Parent artifact pertence a outro projeto.',409,'ARTIFACT_PARENT_MISMATCH');for(const dependency of input.dependencies??[]){const item=this.store.getArtifact(dependency,userId);if(item.projectId!==input.projectId)throw new AppError('Dependência pertence a outro projeto.',409,'ARTIFACT_DEPENDENCY_MISMATCH')}const siblings=this.store.listArtifacts(userId,input.projectId).filter(item=>item.type===input.type),version=parent?parent.version+1:Math.max(0,...siblings.map(item=>item.version))+1,status=input.verification.valid===true?'verified':input.verification.valid===false?'rejected':'created',record:ArtifactRecord={id:id('artifact'),userId,projectId:input.projectId,fileId:input.fileId,type:input.type,version,parentId:input.parentId,producer:input.producer,inputs:input.inputs??[],dependencies:input.dependencies??[],verification:input.verification,metadata:input.metadata??{},license:input.license??'SNB-Internal',status,createdAt:now()};this.store.createArtifact(record);if(parent&&record.status==='verified'){parent.status='superseded';this.store.updateArtifact(parent)}return record}
 graph(userId:string,projectId:string){this.store.getProject(projectId,userId);const nodes=this.store.listArtifacts(userId,projectId),ids=new Set(nodes.map(item=>item.id)),edges=nodes.flatMap(node=>[...(node.parentId&&ids.has(node.parentId)?[{from:node.parentId,to:node.id,type:'version'}]:[]),...node.dependencies.filter(id=>ids.has(id)).map(from=>({from,to:node.id,type:'dependency'}))]);return{nodes,edges,summary:{total:nodes.length,verified:nodes.filter(item=>item.status==='verified').length,rejected:nodes.filter(item=>item.status==='rejected').length,types:[...new Set(nodes.map(item=>item.type))]}}}
}
