import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import type { CapabilityManifest } from '../domain.js'
import { AppError } from '../lib/errors.js'
import { now } from '../lib/id.js'
import type { Store } from '../repositories/store.js'

const execute=promisify(execFile)
const candidates=[
  {command:'python3',args:['--version'],id:'cli.python',name:'Python CLI',capabilities:['script.python','data.processing','scientific.compute']},
  {command:'ffmpeg',args:['-version'],id:'cli.ffmpeg',name:'FFmpeg CLI',capabilities:['video.transcode','audio.transcode','media.inspect']},
  {command:'blender',args:['--version'],id:'software.blender',name:'Blender',capabilities:['3d.model','3d.retopology','3d.uv','material.pbr','rig.character','animation.motion','3d.export']},
  {command:'godot',args:['--version'],id:'engine.godot',name:'Godot Engine',capabilities:['game.engine','scene.build','game.build','3d.import']},
]
const characterPipeline=[
  ['research','research.web'],['concept','image.concept'],['generation','3d.generate'],['retopology','3d.retopology'],['uv','3d.uv'],['materials','material.pbr'],['rig','rig.character'],['animation','animation.motion'],['optimization','3d.optimize'],['export','3d.export'],['verification','verify.3d'],
]

export class CapabilityFabric{
  constructor(private store:Store){}
  async discoverEnvironment(){const discovered:CapabilityManifest[]=[];for(const candidate of candidates){try{const result=await execute(candidate.command,candidate.args,{timeout:3000,maxBuffer:10000,env:{PATH:process.env.PATH??''}}),timestamp=now(),existing=this.store.getCapabilityManifest(candidate.id);const manifest:CapabilityManifest={id:candidate.id,name:candidate.name,version:this.version(`${result.stdout}${result.stderr}`),vendor:'environment-discovery',type:candidate.id.startsWith('engine.')?'engine':candidate.id.startsWith('software.')?'software':'cli',capabilities:candidate.capabilities,inputs:{},outputs:{artifacts:'tool-specific'},executionMethods:['local-process-adapter-required'],authentication:[],permissions:['execute'],dependencies:[],limits:{discoveryTimeoutMs:3000},license:existing?.license??'UNVERIFIED',risk:'medium',compatibility:[process.platform,process.arch],status:existing?.status==='active'?'active':'testing',reliability:existing?.reliability??0,evidenceCount:existing?.evidenceCount??0,metadata:{command:candidate.command,discoveryOutput:`${result.stdout}${result.stderr}`.slice(0,500)},createdAt:existing?.createdAt??timestamp,updatedAt:timestamp};this.store.upsertCapabilityManifest(manifest);discovered.push(manifest)}catch{/* absence is a capability gap, not an error */}}return{discovered,missing:candidates.filter(candidate=>!discovered.some(item=>item.id===candidate.id)).map(item=>({id:item.id,name:item.name,capabilities:item.capabilities}))}}
  registerInternalVerified(input:{id:string;name:string;version:string;capabilities:string[];outputs:Record<string,unknown>;verifier:string}){const existing=this.store.getCapabilityManifest(input.id),timestamp=now(),manifest:CapabilityManifest={id:input.id,name:input.name,version:input.version,vendor:'SNB Internal',type:'library',capabilities:input.capabilities,inputs:{prompt:'string',projectId:'optional'},outputs:input.outputs,executionMethods:['in-process-deterministic'],authentication:['snb-session'],permissions:['write'],dependencies:[],limits:{timeoutMs:10000},license:'SNB-Internal',risk:'low',compatibility:['snb-api'],status:'active',reliability:95,evidenceCount:Math.max(existing?.evidenceCount??0,3),metadata:{verifier:input.verifier,scope:'procedural-fallback-not-generative-ai'},createdAt:existing?.createdAt??timestamp,updatedAt:timestamp};return this.store.upsertCapabilityManifest(manifest)}
  register(input:Omit<CapabilityManifest,'createdAt'|'updatedAt'|'reliability'|'evidenceCount'>){if(input.status==='active')throw new AppError('Novas capabilities devem iniciar como discovered/testing.',400,'CAPABILITY_REQUIRES_VALIDATION');const existing=this.store.getCapabilityManifest(input.id),timestamp=now(),manifest:CapabilityManifest={...input,reliability:existing?.reliability??0,evidenceCount:existing?.evidenceCount??0,createdAt:existing?.createdAt??timestamp,updatedAt:timestamp};return this.store.upsertCapabilityManifest(manifest)}
  validate(manifestId:string,input:{license:string;reliability:number;evidenceCount:number;activate:boolean}){const manifest=this.store.getCapabilityManifest(manifestId);if(!manifest)throw new AppError('Capability manifest não encontrado.',404,'CAPABILITY_NOT_FOUND');if(input.activate&&(input.license==='UNVERIFIED'||input.evidenceCount<3))throw new AppError('Ativação exige licença verificada e pelo menos 3 evidências.',409,'CAPABILITY_VALIDATION_REQUIRED');manifest.license=input.license;manifest.reliability=input.reliability;manifest.evidenceCount=input.evidenceCount;manifest.status=input.activate?'active':'testing';manifest.updatedAt=now();return this.store.upsertCapabilityManifest(manifest)}
  list(options?:Parameters<Store['listCapabilityManifests']>[0]){return this.store.listCapabilityManifests(options)}
  synthesize3D(goal:string){const manifests=this.store.listCapabilityManifests(),stages=characterPipeline.map(([id,capability],index)=>{const active=manifests.filter(item=>item.status==='active'&&item.capabilities.includes(capability)).sort((a,b)=>b.reliability-a.reliability)[0],testing=manifests.filter(item=>item.status==='testing'&&item.capabilities.includes(capability));return{id,capability,dependsOn:index?[characterPipeline[index-1][0]]:[],status:active?'ready':'gap',selected:active?{id:active.id,name:active.name,version:active.version,reliability:active.reliability}:undefined,candidates:testing.map(item=>({id:item.id,name:item.name,status:item.status})),verification:capability.startsWith('3d.')||capability.startsWith('rig.')||capability.startsWith('animation.')?'artifact-validator':'stage-specific'}});return{goal,pipeline:'universal-3d-character-v1',executable:stages.every(stage=>stage.status==='ready'),stages,gaps:stages.filter(stage=>stage.status==='gap').map(stage=>stage.capability),rule:'Nenhuma etapa é declarada executável sem capability ativa, adapter e evidência.'}}
  private version(output:string){return output.match(/\d+(?:\.\d+){1,3}/)?.[0]??'detected-unknown'}
}
