import { createHmac } from 'node:crypto'
import { AppError } from '../lib/errors.js'
import { id, now } from '../lib/id.js'
import type { Store,CognitiveHandoff,CognitiveReview } from '../repositories/store.js'
import type { MissionEngine } from './mission-engine.js'
const stable=(value:unknown):string=>Array.isArray(value)?`[${value.map(stable).join(',')}]`:value&&typeof value==='object'?`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stable(item)}`).join(',')}}`:JSON.stringify(value)
export class CognitiveCollaborationService{
 constructor(private store:Store,private missions:MissionEngine,private secret:string){}
 submit(userId:string,input:{missionId:string;taskId:string;modelKey:string;inputArtifactIds:string[];output:Record<string,unknown>;findings:CognitiveHandoff['findings']}){const mission=this.store.getMission(input.missionId,userId),task=this.store.getMissionTask(input.taskId);if(!task||task.missionId!==mission.id)throw new AppError('Tarefa especialista não pertence à missão.',404,'SPECIALIST_TASK_NOT_FOUND');if(!task.kind.startsWith('specialist:'))throw new AppError('Somente tarefas de especialista produzem handoffs.',409,'NOT_SPECIALIST_TASK');if(task.status!=='running')throw new AppError('A tarefa especialista deve estar em execução.',409,'SPECIALIST_TASK_NOT_RUNNING');const model=this.store.getExternalModel(input.modelKey);if(!model||model.source!=='puter'||!model.available)throw new AppError('Modelo Puter não é canônico ou está indisponível.',400,'PUTER_MODEL_NOT_CANONICAL');for(const artifactId of input.inputArtifactIds){const artifact=this.store.getArtifact(artifactId,userId);if(artifact.projectId!==mission.projectId)throw new AppError('Artifact de entrada não pertence ao projeto da missão.',409,'HANDOFF_ARTIFACT_SCOPE')}const timestamp=now(),handoffId=id('handoff'),payload={handoffId,userId,missionId:mission.id,taskId:task.id,modelKey:model.key,output:input.output,findings:input.findings,createdAt:timestamp},handoff:CognitiveHandoff={id:handoffId,userId,missionId:mission.id,taskId:task.id,specialistRole:task.kind.slice('specialist:'.length),modelKey:model.key,inputArtifactIds:[...new Set(input.inputArtifactIds)],output:input.output,findings:input.findings,status:'submitted',trust:'client-reported',receipt:this.sign('snb-specialist-handoff-hmac',payload),createdAt:timestamp};this.store.createCognitiveHandoff(handoff);this.missions.completeTask(userId,mission.id,task.id,{handoffId:handoff.id,modelKey:model.key,trust:'client-reported',findingCount:handoff.findings.length,receipt:handoff.receipt});this.store.audit({id:id('audit'),userId,action:'cognitive.handoff.submitted',resource:handoff.id,metadata:{missionId:mission.id,taskId:task.id,modelKey:model.key,trust:handoff.trust},createdAt:timestamp});return{handoff,model:{key:model.key,id:model.id,provider:model.provider},trust:{execution:'client-reported',providerAttested:false,verification:'pending-independent-review'}}}
 review(userId:string,handoffId:string,input:{reviewerTaskId:string;reviewerModelKey:string;verdict:CognitiveReview['verdict'];findings:CognitiveReview['findings']}){const handoff=this.store.getCognitiveHandoff(handoffId,userId),task=this.store.getMissionTask(input.reviewerTaskId);this.store.getMission(handoff.missionId,userId);if(!task||task.missionId!==handoff.missionId||!task.kind.startsWith('critic:'))throw new AppError('Review exige tarefa critic da mesma missão.',409,'INVALID_CRITIC_TASK');if(task.status!=='running')throw new AppError('A tarefa critic deve estar em execução.',409,'CRITIC_TASK_NOT_RUNNING');const model=this.store.getExternalModel(input.reviewerModelKey);if(!model||!model.available)throw new AppError('Modelo crítico não é canônico.',400,'PUTER_MODEL_NOT_CANONICAL');if(model.key===handoff.modelKey)throw new AppError('O mesmo modelo não pode revisar o próprio handoff.',409,'SELF_REVIEW_FORBIDDEN');if(this.store.listCognitiveReviews(handoff.id,userId).some(review=>review.reviewerModelKey===model.key))throw new AppError('Este modelo já revisou o handoff.',409,'DUPLICATE_COGNITIVE_REVIEW');const timestamp=now(),reviewId=id('review'),payload={reviewId,handoffId,reviewerTaskId:task.id,reviewerModelKey:model.key,verdict:input.verdict,findings:input.findings,createdAt:timestamp},review:CognitiveReview={id:reviewId,handoffId,userId,reviewerTaskId:task.id,reviewerModelKey:model.key,verdict:input.verdict,findings:input.findings,receipt:this.sign('snb-cognitive-review-hmac',payload),createdAt:timestamp};this.store.createCognitiveReview(review);handoff.status=input.verdict==='accept'?'accepted':input.verdict==='revise'?'revision-required':'rejected';handoff.reviewedAt=timestamp;this.store.updateCognitiveHandoff(handoff);this.store.audit({id:id('audit'),userId,action:'cognitive.handoff.reviewed',resource:handoff.id,metadata:{reviewId:review.id,verdict:review.verdict,reviewerModelKey:model.key},createdAt:timestamp});return{handoff,review,trust:{execution:'client-reported',independentModel:model.key!==handoff.modelKey,providerAttested:false}}}
 list(userId:string,missionId:string){this.store.getMission(missionId,userId);return this.store.listCognitiveHandoffs(userId,missionId).map(handoff=>({...handoff,reviews:this.store.listCognitiveReviews(handoff.id,userId)}))}
 private sign(prefix:string,payload:unknown){return`${prefix}:${createHmac('sha256',this.secret).update(stable(payload)).digest('hex')}`}
}
