import { createHash } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import type { DivineOsModule, DivineOsProject, FileAsset } from '../domain.js'
import { AppError } from '../lib/errors.js'
import { id, now } from '../lib/id.js'
import type { Store } from '../repositories/store.js'
import type { CapabilityFabric } from './capability-fabric.js'
import type { MissionEngine, TaskDefinition } from './mission-engine.js'

const architecture=['Divine Capability Framework','Divine Privileges of Singularity','Divine Module System','Divine Permission Engine','Divine Runtime','Divine Hardware Abstraction','Divine Performance Engine','Divine UI Framework','Divine Security Layer','Divine Recovery/Snapshot','Divine Package System','Divine Developer System','Divine Gaming System','Divine Resource Manager','Divine Configuration System','Divine Compatibility Layer']
const agentTasks:TaskDefinition[]=[{key:'base-analysis',title:'Analyze selected base and source',kind:'agent:systems-architect'},{key:'compliance',title:'License and compliance review',kind:'agent:compliance',dependsOn:['base-analysis']},{key:'dependencies',title:'Dependency graph',kind:'agent:dependency',dependsOn:['base-analysis']},{key:'architecture',title:'Divine architecture overlay',kind:'agent:systems-architect',dependsOn:['compliance','dependencies']},{key:'runtime',title:'Kernel/runtime configuration',kind:'agent:kernel-runtime',dependsOn:['architecture']},{key:'hardware',title:'Hardware and driver compatibility',kind:'agent:driver',dependsOn:['architecture']},{key:'security',title:'Security policy and threat analysis',kind:'agent:security',dependsOn:['runtime','hardware']},{key:'ui',title:'Divine UI and interaction layer',kind:'agent:ui',dependsOn:['runtime']},{key:'performance',title:'Resource and performance profile',kind:'agent:performance',dependsOn:['runtime']},{key:'build',title:'Reproducible image build',kind:'agent:build',dependsOn:['security','ui','performance']},{key:'test',title:'Boot/runtime compatibility tests',kind:'agent:testing',dependsOn:['build']},{key:'verify',title:'Artifact and compliance verification',kind:'agent:verification',dependsOn:['test']},{key:'release',title:'Versioned release artifact',kind:'agent:release',dependsOn:['verify']},{key:'documentation',title:'Source, license and operator documentation',kind:'agent:documentation',dependsOn:['verify']}]
const requiredByVariant:Record<DivineOsProject['variant'],string[]>={core:['source.fetch','dependency.analyze','license.analyze','os.build','os.test','security.scan','image.package'],droid:['android.source','android.build','boot.image','android.emulator','image.sign','license.analyze'],linux:['linux.source','linux.toolchain','kernel.configure','rootfs.build','qemu.test','image.package','license.analyze'],'win-compat':['compatibility.runtime','win32.test','prefix.package','license.analyze','security.scan']}

export class DivineOsService{
 constructor(private store:Store,private missions:MissionEngine,private fabric:CapabilityFabric,private root=resolve('./data/uploads')){}
 async create(userId:string,input:{name:string;variant:DivineOsProject['variant'];baseManifest?:Record<string,unknown>;configuration?:Record<string,unknown>}){const base=input.baseManifest??{},compliance=this.analyzeCompliance(input.variant,base),project=this.store.createProject(userId,input.name,`Divine Singularity OS · ${input.variant}`),active=this.fabric.list({status:'active'}),required=requiredByVariant[input.variant],gaps=required.filter(capability=>!active.some(item=>item.capabilities.includes(capability))),mission=this.missions.create(userId,`Divine OS ${input.variant}: ${input.name}`,agentTasks,project.id,{userIntent:`Build a verified ${input.variant} system using legally reusable foundations`,constraints:['Never modify host silently','No proprietary redistribution without authorization','Load components on demand'],requiredCapabilities:required,availableResources:active.map(item=>item.id),risks:['License incompatibility','Unbootable image','Driver incompatibility','Privilege boundary failure'],successCriteria:['Bootable/testable artifact exists','Compliance review completed','Security and performance gates pass'],verificationRequirements:['Source checksum','License manifest','Dependency graph','Build log','Boot test','Artifact hash'],finalDeliverable:`Versioned Divine ${input.variant} artifact and documentation`,autonomy:'SUPERVISED'}),timestamp=now(),osProject:DivineOsProject={id:id('divineos'),userId,projectId:project.id,missionId:mission.mission.id,name:input.name,variant:input.variant,status:gaps.length||compliance.status!=='pass'?'blocked':'configured',architecture,baseManifest:base,configuration:input.configuration??{loadPolicy:'on-demand',resourcePriority:['RAM','CPU','energy','latency']},compliance:{...compliance,capabilityGaps:gaps},createdAt:timestamp,updatedAt:timestamp};this.store.createDivineOsProject(osProject);await this.writeManifest(osProject);this.store.audit({id:id('audit'),userId,action:'divine-os.project.created',resource:osProject.id,metadata:{variant:input.variant,gaps,compliance:compliance.status},createdAt:timestamp});return this.detail(userId,osProject.id)}
 list(userId:string){return this.store.listDivineOsProjects(userId).map(item=>{const mission=this.store.getMission(item.missionId,userId);return{...item,progress:mission.progress,missionStatus:mission.status,moduleCount:this.store.listDivineOsModules(item.id,userId).length,artifactCount:this.store.listFiles(userId,item.projectId).length}})}
 detail(userId:string,id:string){const os=this.store.getDivineOsProject(id,userId),mission=this.missions.detail(userId,os.missionId),modules=this.store.listDivineOsModules(id,userId),artifacts=this.store.listFiles(userId,os.projectId).map(({storagePath:_,...file})=>file),required=requiredByVariant[os.variant],active=this.fabric.list({status:'active'}),gaps=required.filter(capability=>!active.some(item=>item.capabilities.includes(capability)));return{os,project:this.store.getProject(os.projectId,userId),mission:mission.mission,contract:mission.contract,tasks:mission.tasks,events:mission.events,modules,artifacts,capabilities:{required,gaps,ready:required.filter(item=>!gaps.includes(item))},build:{executable:gaps.length===0&&os.compliance.status==='pass',reason:gaps.length?'Missing executable capabilities':os.compliance.status!=='pass'?'Compliance review required':'Ready for build worker'}}}
 async setBase(userId:string,id:string,baseManifest:Record<string,unknown>){const project=this.store.getDivineOsProject(id,userId);project.baseManifest=baseManifest;project.compliance={...this.analyzeCompliance(project.variant,baseManifest),capabilityGaps:project.compliance.capabilityGaps};project.status=project.compliance.status==='pass'&&!((project.compliance.capabilityGaps as unknown[])?.length)?'configured':'blocked';project.updatedAt=now();this.store.updateDivineOsProject(project);await this.writeManifest(project);return this.detail(userId,id)}
 analyzeModules(userId:string,projectId:string){this.store.getDivineOsProject(projectId,userId);const modules=this.store.listDivineOsModules(projectId,userId),byName=new Map(modules.map(item=>[item.name,item])),missing=modules.flatMap(item=>item.dependencies.filter(dependency=>!byName.has(dependency)).map(dependency=>({module:item.name,dependency}))),cycles:string[][]=[],visiting=new Set<string>(),visited=new Set<string>(),path:string[]=[];const visit=(name:string)=>{if(visiting.has(name)){const index=path.indexOf(name);cycles.push([...path.slice(index),name]);return}if(visited.has(name))return;visiting.add(name);path.push(name);for(const dependency of byName.get(name)?.dependencies??[])if(byName.has(dependency))visit(dependency);path.pop();visiting.delete(name);visited.add(name)};for(const name of byName.keys())visit(name);const blocked=modules.filter(item=>item.status==='blocked');return{valid:!missing.length&&!cycles.length&&!blocked.length,modules,missing,cycles,blocked:blocked.map(item=>({id:item.id,name:item.name,permissions:item.permissions})),loadOrder:[...visited],rule:'No concurrent critical modification without dependency order, approval and verification.'}}
 addModule(userId:string,projectId:string,input:{name:string;version:string;capabilities:string[];dependencies:string[];permissions:string[];manifest:Record<string,unknown>}){this.store.getDivineOsProject(projectId,userId);const timestamp=now(),module:DivineOsModule={id:id('osmodule'),userId,divineOsProjectId:projectId,name:input.name,version:input.version,capabilities:input.capabilities,dependencies:[...new Set(input.dependencies)],permissions:[...new Set(input.permissions)],status:input.permissions.some(item=>['host-root','silent-host-modification'].includes(item))?'blocked':'declared',manifest:input.manifest,createdAt:timestamp,updatedAt:timestamp};return this.store.createDivineOsModule(module)}
 private analyzeCompliance(variant:DivineOsProject['variant'],base:Record<string,unknown>){const issues:string[]=[],source=typeof base.sourceUrl==='string'?base.sourceUrl:'',license=typeof base.license==='string'?base.license:'UNVERIFIED',checksum=typeof base.checksum==='string'?base.checksum:'';if(!source.startsWith('https://'))issues.push('HTTPS source URL required');if(license==='UNVERIFIED'||!license)issues.push('License declaration and human/legal review required');if(!checksum)issues.push('Source SHA-256 checksum required');else if(!/^[a-f0-9]{64}$/i.test(checksum))issues.push('Checksum must be SHA-256');if(variant==='win-compat'&&String(base.redistributesProprietaryWindows??false)==='true')issues.push('Redistributing proprietary Windows components is forbidden');return{status:issues.length?'review-required':'pass',issues,license,sourceUrl:source,checksum:checksum||null,reviewNote:'Automated checks are not legal advice; release requires human compliance approval.'}}
 private async writeManifest(project:DivineOsProject){const payload={format:'snb-divine-os-project-v1',project:{id:project.id,name:project.name,variant:project.variant,status:project.status},architecture:project.architecture,base:project.baseManifest,configuration:project.configuration,compliance:project.compliance,generatedAt:now()},buffer=Buffer.from(JSON.stringify(payload,null,2)),directory=join(this.root,project.userId);await mkdir(directory,{recursive:true});const existing=this.store.listFiles(project.userId,project.projectId).find(item=>item.name==='divine-os-project.json');if(existing)return existing;const fileId=id('file'),storagePath=join(directory,`${fileId}-divine-os-project.json`),checksum=createHash('sha256').update(buffer).digest('hex');await writeFile(storagePath,buffer,{flag:'wx'});const file:FileAsset={id:fileId,userId:project.userId,projectId:project.projectId,name:'divine-os-project.json',mimeType:'application/json',size:buffer.length,checksum,storagePath,createdAt:now()};return this.store.createFile(file)}
}
