import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { SQLiteStore } from '../repositories/sqlite-store.js'
import { DivineEngineSettingsService, divinePresets, divineSettings } from './divine-engine-settings.js'

let store:SQLiteStore,service:DivineEngineSettingsService,divineId:string
beforeEach(()=>{store=new SQLiteStore(':memory:');service=new DivineEngineSettingsService(store);const project=store.createProject('user','Divine','settings'),mission={id:'mission-settings',userId:'user',goal:'settings',status:'pending' as const,progress:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},contract={missionId:mission.id,objective:'settings',userIntent:'settings',constraints:[],requiredCapabilities:[],availableResources:[],risks:[],successCriteria:[],verificationRequirements:[],finalDeliverable:'settings',autonomy:'SUPERVISED' as const,phase:'CREATED' as const,createdAt:mission.createdAt,updatedAt:mission.updatedAt};store.createMission(mission,contract,[],{id:'event-settings',missionId:mission.id,type:'created',payload:{},createdAt:mission.createdAt});divineId='divine-settings';store.createDivineProject({id:divineId,userId:'user',projectId:project.id,missionId:mission.id,name:'Settings',brief:'settings test',target:'web',format:'snb-divine-project-v1',executionPolicy:'remote-first',deviceProfile:{tier:'low'},status:'created',createdAt:mission.createdAt,updatedAt:mission.updatedAt})})
afterEach(()=>store.close())

describe('Divine Engine customization registry',()=>{
 it('contains exactly 220 typed options and 10 presets',()=>{expect(divineSettings).toHaveLength(220);expect(new Set(divineSettings.map(item=>item.key)).size).toBe(220);expect(divinePresets).toHaveLength(10);expect(service.registry().summary.active).toBeGreaterThan(0)})
 it('validates settings and applies versioned presets',()=>{const preset=service.applyPreset('user',divineId,'mobile-ultra-lite');expect(preset.preset).toBe('mobile-ultra-lite');expect(preset.values['optimization.target-fps']).toBe(30);const changed=service.update('user',divineId,{'rendering.rotation-speed':.02});expect(changed.version).toBeGreaterThan(preset.version);expect(()=>service.update('user',divineId,{'unknown.option':1})).toThrow()})
 it('applies native /set commands and preserves normal commands for planning',()=>{const applied=service.command('user',divineId,{message:'/set rendering.rotation-speed=0.03',attachmentFileIds:[]});expect(applied.status).toBe('applied');expect(applied.operations[0]).toMatchObject({type:'setting.update',status:'active'});const planned=service.command('user',divineId,{message:'Create a dynamic weather system',attachmentFileIds:[]});expect(planned.status).toBe('received')})
})
