import { createHash } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import type { FileAsset } from '../domain.js'
import { id, now } from '../lib/id.js'
import type { Store } from '../repositories/store.js'
import type { ArtifactGraphService } from './artifact-graph.js'
import type { Procedural3DProvider } from './procedural-3d.js'
import type { ProceduralPbrProvider } from './procedural-pbr.js'

export class DivinePrototypePipeline{
 constructor(private store:Store,private artifacts:ArtifactGraphService,private provider3d:Procedural3DProvider,private pbr:ProceduralPbrProvider,private root=resolve('./data/uploads')){}
 async build(userId:string,input:{projectId:string;prompt:string;name:string}){this.store.getProject(input.projectId,userId);const mesh=await this.provider3d.generate(userId,{prompt:input.prompt,projectId:input.projectId,name:`${input.name}-mesh`}),meshArtifact=this.artifacts.register(userId,{projectId:input.projectId,fileId:mesh.artifact.id,type:'model.glb',producer:mesh.provider.id,verification:mesh.verification,metadata:{limitations:mesh.limitations}}),material=await this.pbr.generate(userId,{prompt:input.prompt,projectId:input.projectId,name:`${input.name}-pbr`,resolution:64}),textureArtifacts=material.maps.map(file=>this.artifacts.register(userId,{projectId:input.projectId,fileId:file.id,type:`texture.${file.name.split('-').at(-1)?.replace('.png','')}`,producer:'snb.procedural-pbr',verification:{valid:true,format:'PNG',resolution:64},metadata:{lightweight:true}})),materialArtifact=this.artifacts.register(userId,{projectId:input.projectId,fileId:material.material.id,type:'material.pbr',producer:'snb.procedural-pbr',dependencies:textureArtifacts.map(item=>item.id),verification:material.verification}),scene=await this.writeJson(userId,input.projectId,`${input.name}-scene.json`,{format:'snb-scene-v1',name:input.name,nodes:[{id:'prototype-object',meshArtifactId:meshArtifact.id,materialArtifactId:materialArtifact.id,transform:{position:[0,0,0],rotation:[0,0,0,1],scale:[1,1,1]}}],camera:{position:[0,1.5,5],target:[0,0,0]},lighting:[{type:'directional',intensity:2},{type:'ambient',intensity:.35}],generatedAt:now()}),sceneArtifact=this.artifacts.register(userId,{projectId:input.projectId,fileId:scene.id,type:'scene.snb',producer:'snb.scene-builder',dependencies:[meshArtifact.id,materialArtifact.id],verification:{valid:true,nodeCount:1,allDependenciesExist:true}}),build=await this.writeHtml(userId,input.projectId,`${input.name}-playable.html`,input.name),buildArtifact=this.artifacts.register(userId,{projectId:input.projectId,fileId:build.id,type:'build.web',producer:'snb.webgl-prototype-builder',dependencies:[sceneArtifact.id],verification:{valid:true,selfContained:true,networkRequests:0,interactive:true}}),graph=this.artifacts.graph(userId,input.projectId);return{mesh,material,scene:{file:scene,artifact:sceneArtifact},build:{file:build,artifact:buildArtifact},graph,verification:{valid:mesh.verification.valid&&material.verification.valid&&buildArtifact.status==='verified',stages:{mesh:mesh.verification,material:material.verification,scene:sceneArtifact.verification,build:buildArtifact.verification}},limitations:['Primitive cube gameplay prototype','No external engine runtime','No semantic world generation','No character controller']}}
 private async writeJson(userId:string,projectId:string,name:string,data:Record<string,unknown>){return this.write(userId,projectId,name,'application/json',Buffer.from(JSON.stringify(data,null,2)))}
 private async writeHtml(userId:string,projectId:string,name:string,title:string){const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${this.escape(title)}</title><style>html,body,canvas{margin:0;width:100%;height:100%;overflow:hidden;background:#080b12}aside{position:fixed;color:#c9d0df;font:12px system-ui;padding:10px}</style></head><body><aside>SNB verified WebGL prototype · arrows rotate · no network</aside><canvas id="c"></canvas><script>const c=document.getElementById('c'),g=c.getContext('webgl');if(!g)throw Error('WebGL unavailable');const V='attribute vec3 p;uniform vec2 r;void main(){float a=r.x,b=r.y;mat3 y=mat3(cos(a),0.,sin(a),0.,1.,0.,-sin(a),0.,cos(a));mat3 x=mat3(1.,0.,0.,0.,cos(b),-sin(b),0.,sin(b),cos(b));gl_Position=vec4(x*y*p*.45,1.);}',F='precision mediump float;uniform vec3 color;void main(){gl_FragColor=vec4(color,1.);}';function sh(t,s){let h=g.createShader(t);g.shaderSource(h,s);g.compileShader(h);if(!g.getShaderParameter(h,g.COMPILE_STATUS))throw Error(g.getShaderInfoLog(h));return h}let p=g.createProgram();g.attachShader(p,sh(g.VERTEX_SHADER,V));g.attachShader(p,sh(g.FRAGMENT_SHADER,F));g.linkProgram(p);g.useProgram(p);const q=[-1,-1,1,1,-1,1,1,1,1,-1,-1,1,1,1,1,-1,1,1,-1,-1,-1,-1,1,-1,1,1,-1,-1,-1,-1,-1,-1,1,-1,-1,1,-1,1,1,-1,1,-1,1,-1,1,1,-1,1,-1,-1,-1,-1,-1,1,-1,1,1,1,1,-1,1,-1,1,1,1,1,1,1,1,-1,-1,-1,-1,1,-1,-1,1,-1,1,1,-1,-1,1,-1,1,1,-1,1,1,1,1,1,1,-1,1];let b=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,new Float32Array(q),g.STATIC_DRAW);let l=g.getAttribLocation(p,'p');g.enableVertexAttribArray(l);g.vertexAttribPointer(l,3,g.FLOAT,false,0,0);let u=g.getUniformLocation(p,'r'),uc=g.getUniformLocation(p,'color'),rx=.5,ry=.4,speed=.005,color=[.25,.55,.95],auto=true,arrows=true,reduced=false;onkeydown=e=>{if(!arrows)return;if(e.key==='ArrowLeft')rx-=.1;if(e.key==='ArrowRight')rx+=.1;if(e.key==='ArrowUp')ry-=.1;if(e.key==='ArrowDown')ry+=.1};onmessage=e=>{let d=e.data;if(!d||d.type!=='snb-runtime-patch')return;if(Number.isFinite(d.rotationSpeed))speed=Math.max(0,Math.min(.1,d.rotationSpeed));if(Array.isArray(d.color)&&d.color.length===3)color=d.color.map(v=>Math.max(0,Math.min(1,Number(v)||0)));if(typeof d.autoRotate==='boolean')auto=d.autoRotate;if(typeof d.arrowControl==='boolean')arrows=d.arrowControl;if(typeof d.reducedMotion==='boolean')reduced=d.reducedMotion};function draw(){c.width=innerWidth;c.height=innerHeight;g.viewport(0,0,c.width,c.height);g.clear(g.COLOR_BUFFER_BIT);if(auto&&!reduced)rx+=speed;g.uniform2f(u,rx,ry);g.uniform3fv(uc,color);g.drawArrays(g.TRIANGLES,0,q.length/3);requestAnimationFrame(draw)}draw();</script></body></html>`;return this.write(userId,projectId,name,'text/html',Buffer.from(html))}
 private async write(userId:string,projectId:string,name:string,mimeType:string,data:Buffer){const directory=join(this.root,userId);await mkdir(directory,{recursive:true});const fileId=id('file'),storagePath=join(directory,`${fileId}-${name}`);await writeFile(storagePath,data,{flag:'wx'});const file:FileAsset={id:fileId,userId,projectId,name,mimeType,size:data.length,checksum:createHash('sha256').update(data).digest('hex'),storagePath,createdAt:now()};this.store.createFile(file);return{...file,storagePath:undefined}}
 private escape(value:string){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!))}
}
