import { createHash } from 'node:crypto'
import type { EvidenceLink, KnowledgeClaim } from '../domain.js'
import { AppError } from '../lib/errors.js'
import { id, now } from '../lib/id.js'
import type { Store } from '../repositories/store.js'

export class EvidenceEngine{
  constructor(private store:Store){}
  addSource(userId:string,input:{url:string;title:string;publisher?:string;publishedAt?:string;projectId?:string;content?:string}){if(input.projectId)this.store.getProject(input.projectId,userId);return this.store.createEvidenceSource({id:id('source'),userId,projectId:input.projectId,url:input.url,title:input.title,publisher:input.publisher,publishedAt:input.publishedAt,retrievedAt:now(),contentHash:input.content?createHash('sha256').update(input.content).digest('hex'):undefined,status:'active'})}
  addClaim(userId:string,input:{statement:string;state?:KnowledgeClaim['state'];confidence?:number;projectId?:string}){if(input.projectId)this.store.getProject(input.projectId,userId);const timestamp=now();return this.store.createKnowledgeClaim({id:id('claim'),userId,projectId:input.projectId,statement:input.statement,state:input.state??'UNKNOWN',confidence:input.confidence??0,createdAt:timestamp,updatedAt:timestamp})}
  link(userId:string,input:{claimId:string;sourceId:string;relation:EvidenceLink['relation'];quote?:string;strength:number}){const claim=this.store.getKnowledgeClaim(input.claimId,userId),source=this.store.listEvidenceSources(userId).find(item=>item.id===input.sourceId);if(!source)throw new AppError('Fonte não encontrada ou isolada em outro usuário.',404,'SOURCE_NOT_FOUND');const link=this.store.createEvidenceLink({id:id('evidence'),userId,claimId:claim.id,sourceId:source.id,relation:input.relation,quote:input.quote,strength:input.strength,createdAt:now()});this.recompute(claim);return{link,claim:this.store.getKnowledgeClaim(claim.id,userId)}}
  graph(userId:string,projectId?:string){const claims=this.store.listKnowledgeClaims(userId,projectId),sources=this.store.listEvidenceSources(userId,projectId),links=this.store.listEvidenceLinks(userId).filter(link=>claims.some(claim=>claim.id===link.claimId)&&sources.some(source=>source.id===link.sourceId));return{claims,sources,links,summary:{known:claims.filter(item=>item.state==='KNOWN').length,likely:claims.filter(item=>item.state==='LIKELY').length,uncertain:claims.filter(item=>item.state==='UNCERTAIN').length,unknown:claims.filter(item=>item.state==='UNKNOWN').length,conflicting:claims.filter(item=>item.state==='CONFLICTING').length,activeSources:sources.filter(item=>item.status==='active').length}}}
  private recompute(claim:KnowledgeClaim){const links=this.store.listEvidenceLinks(claim.userId,claim.id),supports=links.filter(item=>item.relation==='supports').reduce((sum,item)=>sum+item.strength,0),contradicts=links.filter(item=>item.relation==='contradicts').reduce((sum,item)=>sum+item.strength,0),total=supports+contradicts;claim.confidence=total?Math.round((supports>0&&contradicts>0?Math.abs(supports-contradicts)/total:Math.min(1,Math.max(supports,contradicts)))*100):0;claim.state=supports>0&&contradicts>0?'CONFLICTING':supports>=1.5?'KNOWN':supports>0?'LIKELY':contradicts>0?'UNCERTAIN':'UNKNOWN';claim.updatedAt=now();this.store.updateKnowledgeClaim(claim)}
}
