import { createHash } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import type { FileAsset } from '../domain.js'
import { id, now } from '../lib/id.js'
import type { Store } from '../repositories/store.js'
import type { ArtifactGraphService } from './artifact-graph.js'

const vertices=(size:number)=>Array.from({length:16},(_,index)=>[index&1?size:-size,index&2?size:-size,index&4?size:-size,index&8?size:-size])
const edges=()=>{const result:[number,number][]=[];for(let i=0;i<16;i++)for(let axis=0;axis<4;axis++){const j=i^(1<<axis);if(i<j)result.push([i,j])}return result}
export class Experimental4DService{
 constructor(private store:Store,private artifacts:ArtifactGraphService,private root=resolve('./data/uploads')){}
 async create(userId:string,input:{projectId:string;name:string;size?:number;projectionDistance?:number}){this.store.getProject(input.projectId,userId);const size=Math.max(.1,Math.min(input.size??1,10)),distance=Math.max(size+0.1,Math.min(input.projectionDistance??4,100)),geometry={format:'snb-4d-geometry-v1',classification:'Experimental 4D / Mathematical & Computational Simulation',coordinateSystem:['X','Y','Z','W'],vertices:vertices(size),edges:edges(),projection:{type:'4D perspective to 3D then 3D perspective to 2D',distance},rotationPlanes:['XY','XZ','XW','YZ','YW','ZW'],physicalClaim:false,createdAt:now()},json=await this.write(userId,input.projectId,`${this.safe(input.name)}-tesseract-4d.json`,'application/json',Buffer.from(JSON.stringify(geometry,null,2))),jsonArtifact=this.artifacts.register(userId,{projectId:input.projectId,fileId:json.id,type:'geometry.4d',producer:'snb.experimental-4d',verification:this.verify(geometry),metadata:{classification:geometry.classification,physicalClaim:false}}),html=await this.write(userId,input.projectId,`${this.safe(input.name)}-4d-lab.html`,'text/html',Buffer.from(this.html(input.name,geometry))),htmlArtifact=this.artifacts.register(userId,{projectId:input.projectId,fileId:html.id,type:'build.4d-web',producer:'snb.experimental-4d',dependencies:[jsonArtifact.id],verification:{valid:true,selfContained:true,networkRequests:0,interactive:true,mathematicalProjection:true}});return{geometry:{file:json,artifact:jsonArtifact},build:{file:html,artifact:htmlArtifact},verification:this.verify(geometry),explanation:{what:'A tesseract represented by 16 vertices in X,Y,Z,W and 32 edges.',not:'Evidence of a physical fourth spatial dimension.',observable:'Animated 4D rotations projected into 3D and then onto a 2D canvas.'}}}
 verify(data:{vertices:number[][];edges:[number,number][];coordinateSystem:string[]}){const errors:string[]=[];if(data.vertices.length!==16)errors.push('Tesseract must contain 16 vertices');if(data.edges.length!==32)errors.push('Tesseract must contain 32 edges');if(data.vertices.some(vertex=>vertex.length!==4||vertex.some(value=>!Number.isFinite(value))))errors.push('Every vertex must have four finite coordinates');for(const[a,b]of data.edges){if(a<0||b>=data.vertices.length){errors.push('Edge index out of range');break}const differences=data.vertices[a].filter((value,index)=>value!==data.vertices[b][index]).length;if(differences!==1){errors.push('Tesseract edge must differ on exactly one axis');break}}return{valid:errors.length===0,errors,dimensions:4,vertices:data.vertices.length,edges:data.edges.length,projection:'4D→3D→2D',physicalClaim:false}}
 private html(name:string,data:Record<string,unknown>){const payload=JSON.stringify(data);return`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${this.escape(name)} · SNB 4D</title><style>html,body{margin:0;background:#080a10;color:#d6d9e3;font:12px system-ui;height:100%;overflow:hidden}canvas{width:100%;height:100%}aside{position:fixed;padding:10px;background:#0b0e16cc}b{color:#9a8be8}</style></head><body><aside><b>Experimental 4D</b> · 4D→3D→2D mathematical projection<br>Move pointer: rotate XW/YW · wheel: W slice</aside><canvas id="c"></canvas><script>const G=${payload},c=document.getElementById('c'),x=c.getContext('2d');let a=.3,b=.2,slice=0;onpointermove=e=>{a=e.clientX/innerWidth*6.28;b=e.clientY/innerHeight*6.28};onwheel=e=>slice=Math.max(-2,Math.min(2,slice+Math.sign(e.deltaY)*.1));function rot(v,i,j,t){let q=[...v],A=q[i],B=q[j];q[i]=A*Math.cos(t)-B*Math.sin(t);q[j]=A*Math.sin(t)+B*Math.cos(t);return q}function project(v){v=rot(rot(v,0,3,a),1,3,b);let k=G.projection.distance/(G.projection.distance-v[3]),X=v[0]*k,Y=v[1]*k,Z=v[2]*k,m=3/(4-Z);return[X*m,Y*m,v[3]]}function draw(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);x.clearRect(0,0,innerWidth,innerHeight);let P=G.vertices.map(project),scale=Math.min(innerWidth,innerHeight)*.18;x.strokeStyle='#8979df';for(let e of G.edges){let A=P[e[0]],B=P[e[1]],alpha=Math.max(.15,1-Math.abs((A[2]+B[2])/2-slice)/4);x.globalAlpha=alpha;x.beginPath();x.moveTo(innerWidth/2+A[0]*scale,innerHeight/2+A[1]*scale);x.lineTo(innerWidth/2+B[0]*scale,innerHeight/2+B[1]*scale);x.stroke()}x.globalAlpha=1;requestAnimationFrame(draw)}draw();</script></body></html>`}
 private async write(userId:string,projectId:string,name:string,mimeType:string,data:Buffer){const directory=join(this.root,userId);await mkdir(directory,{recursive:true});const fileId=id('file'),storagePath=join(directory,`${fileId}-${name}`);await writeFile(storagePath,data,{flag:'wx'});const file:FileAsset={id:fileId,userId,projectId,name,mimeType,size:data.length,checksum:createHash('sha256').update(data).digest('hex'),storagePath,createdAt:now()};this.store.createFile(file);return{...file,storagePath:undefined}}
 private safe(value:string){return value.replace(/[^a-zA-Z0-9_-]/g,'-').slice(0,80)||'experiment'}private escape(value:string){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!))}
}
