import { createServer,type Server } from 'node:http'
import { afterEach,beforeEach,describe,expect,it } from 'vitest'
import { mkdir,rm,writeFile } from 'node:fs/promises'
import { SQLiteStore } from '../repositories/sqlite-store.js'
import { ArtifactGraphService } from './artifact-graph.js'
import { ExternalJobAdapterRegistry } from './external-job-adapter.js'
const root='./data/test-external',configPath=`${root}/providers.json`;let server:Server,store:SQLiteStore,registry:ExternalJobAdapterRegistry,port:number
beforeEach(async()=>{const bytes=Buffer.from('real external artifact');server=createServer((req,res)=>{res.setHeader('content-type','application/json');if(req.url==='/health')return res.end('{"ok":true}');if(req.url==='/jobs'&&req.method==='POST')return res.end('{"id":"job-1","status":"queued"}');if(req.url==='/jobs/job-1')return res.end(JSON.stringify({id:'job-1',status:'completed',artifacts:[{url:`http://127.0.0.1:${port}/artifact.bin`,name:'artifact.bin',mimeType:'application/octet-stream'}]}));if(req.url==='/artifact.bin'){res.setHeader('content-type','application/octet-stream');return res.end(bytes)}res.statusCode=404;res.end('{}')});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',()=>resolve()));port=(server.address() as any).port;await mkdir(root,{recursive:true});await writeFile(configPath,JSON.stringify([{id:'test-provider',baseUrl:`http://127.0.0.1:${port}`,capabilities:['3d.generate'],timeoutMs:5000,maxAttempts:2,license:'Test',artifactType:'model.external'}]));store=new SQLiteStore(':memory:');registry=new ExternalJobAdapterRegistry(store,new ArtifactGraphService(store),configPath,`${root}/uploads`);await registry.load()})
afterEach(async()=>{store.close();await new Promise<void>(resolve=>server.close(()=>resolve()));await rm(root,{recursive:true,force:true})})
describe('External job adapter',()=>{it('health-checks, submits, polls, downloads and registers a verified artifact',async()=>{const project=store.createProject('user','External','provider'),result=await registry.execute('user',{providerId:'test-provider',capability:'3d.generate',projectId:project.id,payload:{prompt:'test'}});expect(result.health.healthy).toBe(true);expect(result.artifacts).toHaveLength(1);expect(result.records[0].status).toBe('verified');expect(result.receipt.providerAttested).toBe(false);expect(result.receipt.artifactHashes[0]).toMatch(/^[a-f0-9]{64}$/)});it('refuses unconfigured providers and undeclared capabilities',async()=>{const project=store.createProject('user','External','provider');await expect(registry.execute('user',{providerId:'missing',capability:'3d.generate',projectId:project.id,payload:{}})).rejects.toThrow();await expect(registry.execute('user',{providerId:'test-provider',capability:'audio.generate',projectId:project.id,payload:{}})).rejects.toThrow()})})
