import { createHash } from 'node:crypto'
import { AppError } from '../lib/errors.js'
import { id, now } from '../lib/id.js'
import type { Store } from '../repositories/store.js'

export type HsdsSessionStatus='active'|'paused'|'closed'
export interface HsdsProfile{width:number;height:number;fps:number;bitrateKbps:number;codec:'svg-sequence';transport:'sse';quality:number;reason:string[]}
export interface HsdsSession{id:string;userId:string;projectId:string;divineProjectId:string;status:HsdsSessionStatus;profile:HsdsProfile;state:{sequence:number;yaw:number;pitch:number;zoom:number;artifactCount:number;lastInput?:string};createdAt:string;updatedAt:string}
export interface HsdsRepository{createHsdsSession(session:HsdsSession):HsdsSession;getHsdsSession(sessionId:string,userId:string):HsdsSession;listHsdsSessions(userId:string,projectId?:string):HsdsSession[];updateHsdsSession(session:HsdsSession):void}

const clamp=(value:number,min:number,max:number)=>Math.max(min,Math.min(max,value))
const esc=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!))

/**
 * Hardware Streaming with Divine Singularity local baseline.
 * It is intentionally honest: verified SVG visual-state frames over SSE are operational;
 * GPU capture, video/audio codecs and WebRTC require an external render worker.
 */
export class HsdsService{
 constructor(private store:Store&HsdsRepository){}
 capabilities(){return{status:'operational-local-baseline',pipeline:['artifact/process','visual-state','capture','encode','transport','client-playback','input','feedback','next-visual-state'],operational:{capture:'server visual-state renderer',codec:'svg-sequence',transport:'SSE',input:['touch','mouse','keyboard','gamepad'],adaptiveQuality:true,persistence:true,checksums:true},adapterRequired:{capture:['GPU framebuffer','audio mixer'],codecs:['AV1','VP9','H.264','Opus'],transports:['WebRTC'],requirements:['render worker','encoder binaries or hardware encoder','TURN/STUN for WebRTC']},truthBoundary:'The local codec streams generated SVG visual states. It does not claim GPU framebuffer capture or audiovisual cloud gaming.'}}
 create(userId:string,input:{divineProjectId:string;device:{viewportWidth:number;viewportHeight:number;bandwidthMbps?:number;latencyMs?:number;decodeTier?:'low'|'balanced'|'high';saveData?:boolean}}){
  const divine=this.store.getDivineProject(input.divineProjectId,userId),profile=this.adapt(input.device),timestamp=now(),session:HsdsSession={id:id('hsds'),userId,projectId:divine.projectId,divineProjectId:divine.id,status:'active',profile,state:{sequence:0,yaw:.45,pitch:.25,zoom:1,artifactCount:this.store.listArtifacts(userId,divine.projectId).length},createdAt:timestamp,updatedAt:timestamp};this.store.createHsdsSession(session);this.store.audit({id:id('audit'),userId,action:'hsds.session.created',resource:session.id,metadata:{projectId:session.projectId,profile,codec:'svg-sequence',transport:'sse'},createdAt:timestamp});return{session,capabilities:this.capabilities()}
 }
 list(userId:string,projectId?:string){return this.store.listHsdsSessions(userId,projectId)}
 close(userId:string,sessionId:string){const session=this.store.getHsdsSession(sessionId,userId);session.status='closed';session.updatedAt=now();this.store.updateHsdsSession(session);return session}
 input(userId:string,sessionId:string,input:{type:'pointer'|'keyboard'|'gamepad'|'touch';dx?:number;dy?:number;zoom?:number;key?:string}){const session=this.store.getHsdsSession(sessionId,userId);if(session.status!=='active')throw new AppError('HSDS session is not active.',409,'HSDS_SESSION_INACTIVE');const dx=clamp(Number(input.dx??0),-100,100),dy=clamp(Number(input.dy??0),-100,100);session.state.yaw+=dx*.01;session.state.pitch=clamp(session.state.pitch+dy*.01,-1.4,1.4);session.state.zoom=clamp(session.state.zoom*Number(input.zoom??1),.5,2.5);if(input.key==='ArrowLeft')session.state.yaw-=.12;if(input.key==='ArrowRight')session.state.yaw+=.12;if(input.key==='ArrowUp')session.state.pitch=clamp(session.state.pitch-.12,-1.4,1.4);if(input.key==='ArrowDown')session.state.pitch=clamp(session.state.pitch+.12,-1.4,1.4);session.state.lastInput=input.type;session.state.sequence++;session.updatedAt=now();this.store.updateHsdsSession(session);const frame=this.frame(userId,sessionId);return{accepted:true,inputSequence:session.state.sequence,feedbackFrame:frame.meta}
 }
 frame(userId:string,sessionId:string){const session=this.store.getHsdsSession(sessionId,userId);if(session.status!=='active')throw new AppError('HSDS session is not active.',409,'HSDS_SESSION_INACTIVE');session.state.artifactCount=this.store.listArtifacts(userId,session.projectId).length;session.state.sequence++;session.updatedAt=now();this.store.updateHsdsSession(session);const project=this.store.getDivineProject(session.divineProjectId,userId),svg=this.render(project.name,session),bytes=Buffer.from(svg),checksum=createHash('sha256').update(bytes).digest('hex');return{meta:{sessionId:session.id,sequence:session.state.sequence,capturedAt:session.updatedAt,codec:'svg-sequence',transport:'sse',mimeType:'image/svg+xml',width:session.profile.width,height:session.profile.height,bytes:bytes.length,checksum,artifactCount:session.state.artifactCount,inputAcknowledged:session.state.lastInput??null,verified:true},data:bytes.toString('base64')}}
 private adapt(device:{viewportWidth:number;viewportHeight:number;bandwidthMbps?:number;latencyMs?:number;decodeTier?:'low'|'balanced'|'high';saveData?:boolean}):HsdsProfile{const width=clamp(Math.round(device.viewportWidth),256,2048),height=clamp(Math.round(device.viewportHeight),256,2048),bandwidth=clamp(device.bandwidthMbps??5,.1,1000),latency=clamp(device.latencyMs??80,0,5000),low=device.decodeTier==='low'||device.saveData||bandwidth<2,high=device.decodeTier==='high'&&bandwidth>=12&&latency<80,scale=low ? .5 : high ? 1 : .75,w=Math.max(256,Math.round(width*scale/2)*2),h=Math.max(256,Math.round(height*scale/2)*2),fps=low?4:high?15:8,bitrateKbps=Math.round(clamp(w*h*fps*.012,128,high?12000:4000));return{width:w,height:h,fps,bitrateKbps,codec:'svg-sequence',transport:'sse',quality:low?70:high?95:85,reason:[`viewport ${width}x${height}`,`bandwidth ${bandwidth} Mbps`,`latency ${latency} ms`,low?'low-bandwidth/decode profile':high?'high-quality sustainable profile':'balanced sustainable profile']}}
 private render(name:string,session:HsdsSession){const{width:w,height:h}=session.profile,{yaw,pitch,zoom,artifactCount,sequence}=session.state,cx=w/2+Math.sin(yaw)*w*.12,cy=h/2+Math.sin(pitch)*h*.1,size=Math.min(w,h)*.2*zoom,accent=`hsl(${Math.round((yaw*40+250)%360)} 75% 65%)`;return`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><defs><radialGradient id="b"><stop stop-color="#24234a"/><stop offset="1" stop-color="#070a12"/></radialGradient><filter id="g"><feGaussianBlur stdDeviation="8"/></filter></defs><rect width="100%" height="100%" fill="url(#b)"/><circle cx="${cx}" cy="${cy}" r="${size*1.3}" fill="${accent}" opacity=".15" filter="url(#g)"/><g transform="translate(${cx} ${cy}) rotate(${yaw*20}) scale(${zoom})"><path d="M0 ${-size} L${size*.86} ${size*.5} L${-size*.86} ${size*.5}Z" fill="none" stroke="${accent}" stroke-width="3"/><circle r="${size*.45}" fill="none" stroke="#88d9c0" stroke-width="2"/><path d="M${-size*.8} 0H${size*.8}M0 ${-size*.8}V${size*.8}" stroke="#fff" opacity=".25"/></g><g fill="#e8eaf2" font-family="system-ui"><text x="24" y="36" font-size="18" font-weight="700">HSDS · ${esc(name)}</text><text x="24" y="58" font-size="11" opacity=".65">LIVE VISUAL STATE · SVG/SSE · FRAME ${sequence}</text><text x="24" y="${h-26}" font-size="11" opacity=".7">${artifactCount} verified/registered artifact records · ${session.profile.width}×${session.profile.height} · quality ${session.profile.quality}</text></g></svg>`}
}
