import { createHash } from 'node:crypto'
import { AppError } from '../lib/errors.js'
import { id, now } from '../lib/id.js'
import type { KnowledgeMemoryVersion,Store } from '../repositories/store.js'
import type { Memory } from '../domain.js'
const normalize=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()
const terms=(value:string)=>{const words=normalize(value).split(/\s+/).filter(word=>word.length>1),set=new Set(words);for(let i=0;i<words.length-1;i++)set.add(`${words[i]} ${words[i+1]}`);return set}
const similarity=(a:string,b:string)=>{const left=terms(a),right=terms(b),intersection=[...left].filter(term=>right.has(term)).length,union=new Set([...left,...right]).size;return union?intersection/union:0}
export class KnowledgeMemoryService{
 constructor(private store:Store){}
 create(userId:string,input:{content:string;kind:Memory['kind'];importance:number;projectId?:string;retentionDays?:number;reason?:string}){if(input.projectId)this.store.getProject(input.projectId,userId);const memory=this.store.createMemory(userId,input.content,input.kind,input.importance,input.projectId),timestamp=now(),version:KnowledgeMemoryVersion={id:id('memver'),userId,memoryId:memory.id,projectId:input.projectId,version:1,content:input.content,contentHash:createHash('sha256').update(input.content).digest('hex'),state:'active',reason:input.reason??'created',validFrom:timestamp,validUntil:input.retentionDays?new Date(Date.now()+input.retentionDays*86400000).toISOString():undefined,createdAt:timestamp};this.store.createKnowledgeMemoryVersion(version);return{memory,version}}
 revise(userId:string,memoryId:string,input:{content:string;reason:string;retentionDays?:number}){const memory=this.store.listMemories(userId).find(item=>item.id===memoryId);if(!memory)throw new AppError('Memória não encontrada ou isolada.',404,'MEMORY_NOT_FOUND');const versions=this.store.listKnowledgeMemoryVersions(userId,memoryId),previous=versions.find(item=>item.state==='active');if(!previous)throw new AppError('Memória não possui versão ativa.',409,'MEMORY_NO_ACTIVE_VERSION');if(previous.contentHash===createHash('sha256').update(input.content).digest('hex'))throw new AppError('Nova versão é idêntica à versão ativa.',409,'MEMORY_VERSION_UNCHANGED');const timestamp=now(),next:KnowledgeMemoryVersion={id:id('memver'),userId,memoryId,projectId:memory.projectId,version:Math.max(...versions.map(item=>item.version))+1,content:input.content,contentHash:createHash('sha256').update(input.content).digest('hex'),state:'active',reason:input.reason,previousId:previous.id,validFrom:timestamp,validUntil:input.retentionDays?new Date(Date.now()+input.retentionDays*86400000).toISOString():previous.validUntil,createdAt:timestamp};previous.state='superseded';previous.reason=`superseded:${input.reason}`;this.store.replaceKnowledgeMemoryVersion(previous,next);return{memory:this.store.listMemories(userId).find(item=>item.id===memoryId)!,previous,next,semanticChange:Number((1-similarity(previous.content,next.content)).toFixed(4))}}
 invalidate(userId:string,versionId:string,reason:string){const version=this.store.getKnowledgeMemoryVersion(versionId,userId);if(version.state!=='active')throw new AppError('Somente versão ativa pode ser invalidada.',409,'MEMORY_VERSION_NOT_ACTIVE');version.state='invalidated';version.reason=reason;version.validUntil=now();this.store.updateKnowledgeMemoryVersion(version);return version}
 expire(timestamp=now()){return{expired:this.store.expireKnowledgeMemoryVersions(timestamp),timestamp}}
 lineage(userId:string,memoryId:string){const memory=this.store.listMemories(userId).find(item=>item.id===memoryId);if(!memory)throw new AppError('Memória não encontrada ou isolada.',404,'MEMORY_NOT_FOUND');const versions=this.store.listKnowledgeMemoryVersions(userId,memoryId).sort((a,b)=>a.version-b.version);return{memory,versions,valid:versions.every((item,index)=>index===0?!item.previousId:item.previousId===versions[index-1].id),active:versions.find(item=>item.state==='active')}}
 search(userId:string,query:string,input:{projectId?:string;limit?:number;includeGlobal?:boolean}={}){this.expire();const limit=Math.max(1,Math.min(input.limit??10,50)),memories=this.store.listMemories(userId),byId=new Map(memories.map(memory=>[memory.id,memory])),versions=this.store.listKnowledgeMemoryVersions(userId).filter(version=>version.state==='active'&&(!version.validUntil||version.validUntil>now())).filter(version=>!input.projectId||version.projectId===input.projectId||(input.includeGlobal&&version.projectId===undefined)),results=versions.map(version=>{const memory=byId.get(version.memoryId)!,semantic=similarity(query,version.content),importance=(memory?.importance??0)/100,scope=input.projectId&&version.projectId===input.projectId?.15:0,score=semantic*.7+importance*.2+scope;return{memory,version,score:Number(score.toFixed(4)),signals:{semantic:Number(semantic.toFixed(4)),importance,scope}}}).filter(item=>item.score>0).sort((a,b)=>b.score-a.score).slice(0,limit);return{query,results,trust:{method:'deterministic lexical unigram+bigram similarity',embeddings:false,tenantIsolated:true},summary:{activeCandidates:versions.length,returned:results.length}}}
}
