import type { ModelHealthSample } from '../domain.js'
import { AppError } from '../lib/errors.js'
import { id, now } from '../lib/id.js'
import type { Store } from '../repositories/store.js'

export class ModelHealthService {
  constructor(private store:Store,private failureThreshold=5,private cooldownMs=120_000){}
  record(modelKey:string,success:boolean,latencyMs:number,source:ModelHealthSample['source'],error?:string){if(!this.store.getExternalModel(modelKey))throw new AppError('Modelo não existe no catálogo canônico.',404,'MODEL_NOT_FOUND');const sample:ModelHealthSample={id:id('health'),modelKey,success,latencyMs,error,source,createdAt:now()};this.store.saveModelHealthSample(sample);const key=`model:${modelKey}`,previous=this.store.getCircuitState(key);if(success){this.store.upsertCircuitState({resourceKey:key,state:'closed',failureCount:0,successCount:(previous?.successCount??0)+1,updatedAt:now()})}else{const failures=(previous?.failureCount??0)+1,open=failures>=this.failureThreshold;this.store.upsertCircuitState({resourceKey:key,state:open?'open':previous?.state??'closed',failureCount:failures,successCount:previous?.successCount??0,openedAt:open?now():previous?.openedAt,cooldownUntil:open?new Date(Date.now()+this.cooldownMs).toISOString():previous?.cooldownUntil,lastError:error??'Model execution failed',updatedAt:now()})}return{sample,health:this.summary(modelKey)}}
  summary(modelKey:string){const model=this.store.getExternalModel(modelKey);if(!model)throw new AppError('Modelo não existe no catálogo canônico.',404,'MODEL_NOT_FOUND');const samples=this.store.listModelHealthSamples(modelKey,100),latencies=samples.filter(item=>item.success).map(item=>item.latencyMs).sort((a,b)=>a-b),failures=samples.filter(item=>!item.success).length,circuit=this.store.getCircuitState(`model:${modelKey}`);return{modelKey,provider:model.provider,modelId:model.id,samples:samples.length,successRate:samples.length?(samples.length-failures)/samples.length:null,averageLatencyMs:latencies.length?Math.round(latencies.reduce((a,b)=>a+b,0)/latencies.length):null,p95LatencyMs:latencies.length?latencies[Math.min(latencies.length-1,Math.floor(latencies.length*.95))]:null,circuit:circuit??{state:'closed',failureCount:0,successCount:0},available:model.available}}
  routingAllowed(modelKey:string){const circuit=this.store.getCircuitState(`model:${modelKey}`);if(!circuit||circuit.state==='closed')return true;if(circuit.state==='half-open')return true;if(circuit.cooldownUntil&&new Date(circuit.cooldownUntil)<=new Date()){circuit.state='half-open';circuit.updatedAt=now();this.store.upsertCircuitState(circuit);return true}return false}
}
