import { createHash } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { deflateSync } from 'node:zlib'
import type { FileAsset } from '../domain.js'
import { id, now } from '../lib/id.js'
import type { Store } from '../repositories/store.js'

const crcTable=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0})
const crc32=(buffer:Buffer)=>{let c=0xffffffff;for(const byte of buffer)c=crcTable[(c^byte)&255]^(c>>>8);return(c^0xffffffff)>>>0}
const chunk=(type:string,data:Buffer)=>{const name=Buffer.from(type),out=Buffer.alloc(12+data.length);out.writeUInt32BE(data.length,0);name.copy(out,4);data.copy(out,8);out.writeUInt32BE(crc32(Buffer.concat([name,data])),8+data.length);return out}
const png=(width:number,height:number,pixel:(x:number,y:number)=>[number,number,number,number])=>{const raw=Buffer.alloc((width*4+1)*height);for(let y=0;y<height;y++){const row=y*(width*4+1);raw[row]=0;for(let x=0;x<width;x++){const value=pixel(x,y),offset=row+1+x*4;raw[offset]=value[0];raw[offset+1]=value[1];raw[offset+2]=value[2];raw[offset+3]=value[3]}}const header=Buffer.alloc(13);header.writeUInt32BE(width,0);header.writeUInt32BE(height,4);header[8]=8;header[9]=6;return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',deflateSync(raw,{level:9})),chunk('IEND',Buffer.alloc(0))])}

export class ProceduralPbrProvider{
 constructor(private store:Store,private root=resolve('./data/uploads')){}
 async generate(userId:string,input:{prompt:string;projectId:string;name?:string;resolution?:number}){this.store.getProject(input.projectId,userId);const resolution=Math.max(16,Math.min(input.resolution??64,256)),hash=createHash('sha256').update(input.prompt).digest(),base=[40+hash[0]%180,40+hash[1]%180,40+hash[2]%180],rough=80+hash[3]%150,metal=hash[4]%3===0?210:20,name=(input.name??'procedural-material').replace(/[^a-zA-Z0-9_-]/g,'-').slice(0,80),maps=[['albedo',(x:number,y:number)=>{const d=((x>>3)+(y>>3))%2?10:-10;return[base[0]+d,base[1]+d,base[2]+d,255] as [number,number,number,number]}],['normal',()=>[128,128,255,255] as [number,number,number,number]],['roughness',()=>[rough,rough,rough,255] as [number,number,number,number]],['metallic',()=>[metal,metal,metal,255] as [number,number,number,number]],['ao',()=>[255,255,255,255] as [number,number,number,number]],['height',(x:number,y:number)=>{const value=128+Math.round(24*Math.sin(x/6)*Math.cos(y/6));return[value,value,value,255] as [number,number,number,number]}]] as const,directory=join(this.root,userId);await mkdir(directory,{recursive:true});const files:Omit<FileAsset,'storagePath'>[]=[];for(const[map,fn]of maps){const data=png(resolution,resolution,fn),fileId=id('file'),fileName=`${name}-${map}.png`,storagePath=join(directory,`${fileId}-${fileName}`);await writeFile(storagePath,data,{flag:'wx'});const file:FileAsset={id:fileId,userId,projectId:input.projectId,name:fileName,mimeType:'image/png',size:data.length,checksum:createHash('sha256').update(data).digest('hex'),storagePath,createdAt:now()};this.store.createFile(file);const{storagePath:_,...publicFile}=file;files.push(publicFile)}const manifest={format:'snb-pbr-material-v1',name,prompt:input.prompt,resolution,maps:Object.fromEntries(files.map(file=>[file.name.split('-').at(-1)?.replace('.png',''),{fileId:file.id,checksum:file.checksum}])),parameters:{metallicFactor:metal/255,roughnessFactor:rough/255}},buffer=Buffer.from(JSON.stringify(manifest,null,2)),manifestId=id('file'),manifestName=`${name}-material.json`,storagePath=join(directory,`${manifestId}-${manifestName}`),manifestFile:FileAsset={id:manifestId,userId,projectId:input.projectId,name:manifestName,mimeType:'application/json',size:buffer.length,checksum:createHash('sha256').update(buffer).digest('hex'),storagePath,createdAt:now()};await writeFile(storagePath,buffer,{flag:'wx'});this.store.createFile(manifestFile);return{material:{...manifestFile,storagePath:undefined},maps:files,verification:{valid:files.length===6&&files.every(file=>file.size>60),format:'PNG RGBA 8-bit',resolution,mapCount:files.length,requiredMaps:['albedo','normal','roughness','metallic','ao','height']},limitations:['Procedural textures','No semantic image synthesis','No seam-aware projection to arbitrary meshes']}}
}
