import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import type { FileAsset } from '../domain.js'
import { AppError } from '../lib/errors.js'
import { id, now } from '../lib/id.js'
import type { Store } from '../repositories/store.js'

const align4=(value:number)=>(value+3)&~3
const f32=(values:number[])=>Buffer.from(new Float32Array(values).buffer)
const u16=(values:number[])=>Buffer.from(new Uint16Array(values).buffer)
const cube={
 positions:[-1,-1,1,1,-1,1,1,1,1,-1,1,1,1,-1,-1,-1,-1,-1,-1,1,-1,1,1,-1,-1,1,-1,-1,1,1,1,1,1,1,1,-1,-1,-1,-1,1,-1,-1,1,-1,1,1,-1,-1,1,-1,1,1,-1,1,1,1,1,1,1,-1,1,-1,-1,-1,-1,-1,-1,1,1,-1,1,1,-1],
 normals:[0,0,1,0,0,1,0,0,1,0,0,1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,1,0,0,1,0,0,1,0,0,1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,1,0,0,1,0,0,1,0,0,1,0,-1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0],
 uvs:[0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1],
 indices:[0,1,2,0,2,3,4,5,6,4,6,7,8,9,10,8,10,11,12,13,14,12,14,15,16,17,18,16,18,19,20,21,22,20,22,23],
}

export class Procedural3DProvider{
 constructor(private store:Store,private root=resolve('./data/uploads')){}
 async generate(userId:string,input:{prompt:string;projectId?:string;name?:string}){if(input.projectId)this.store.getProject(input.projectId,userId);const color=this.color(input.prompt),parts=[f32(cube.positions),f32(cube.normals),f32(cube.uvs),u16(cube.indices),f32([0,1,2]),f32([0,0,0,1,0,.7071068,0,.7071068,0,1,0,0])],offsets:number[]=[];let cursor=0;for(const part of parts){offsets.push(cursor);cursor=align4(cursor+part.length)}const binary=Buffer.alloc(cursor);parts.forEach((part,index)=>part.copy(binary,offsets[index]));const views=parts.map((part,index)=>({buffer:0,byteOffset:offsets[index],byteLength:part.length,...(index<3?{target:34962}:index===3?{target:34963}:{})}));const gltf={asset:{version:'2.0',generator:'SNB Procedural 3D Provider 1.0'},scene:0,scenes:[{nodes:[0]}],nodes:[{name:this.safeName(input.name??input.prompt),mesh:0}],meshes:[{name:'ProceduralCube',primitives:[{attributes:{POSITION:0,NORMAL:1,TEXCOORD_0:2},indices:3,material:0}]}],materials:[{name:'PromptDerivedPBR',pbrMetallicRoughness:{baseColorFactor:[...color,1],metallicFactor:.15,roughnessFactor:.65}}],buffers:[{byteLength:binary.length}],bufferViews:views,accessors:[{bufferView:0,componentType:5126,count:24,type:'VEC3',min:[-1,-1,-1],max:[1,1,1]},{bufferView:1,componentType:5126,count:24,type:'VEC3'},{bufferView:2,componentType:5126,count:24,type:'VEC2'},{bufferView:3,componentType:5123,count:36,type:'SCALAR',min:[0],max:[23]},{bufferView:4,componentType:5126,count:3,type:'SCALAR',min:[0],max:[2]},{bufferView:5,componentType:5126,count:3,type:'VEC4'}],animations:[{name:'TurntablePreview',samplers:[{input:4,output:5,interpolation:'LINEAR'}],channels:[{sampler:0,target:{node:0,path:'rotation'}}]}]};const glb=this.pack(gltf,binary),verification=this.verifyBuffer(glb);if(!verification.valid)throw new AppError('GLB procedural falhou na verificação.',500,'PROCEDURAL_GLB_INVALID',verification);const directory=join(this.root,userId);await mkdir(directory,{recursive:true});const fileId=id('file'),name=`${this.safeName(input.name??'procedural-asset')}.glb`,storagePath=join(directory,`${fileId}-${name}`);await writeFile(storagePath,glb,{flag:'wx'});const file:FileAsset={id:fileId,userId,projectId:input.projectId,name,mimeType:'model/gltf-binary',size:glb.length,checksum:createHash('sha256').update(glb).digest('hex'),storagePath,createdAt:now()};this.store.createFile(file);return{artifact:{...file,storagePath:undefined},verification,provider:{id:'snb.procedural-3d',version:'1.0.0',mode:'local-deterministic-fallback'},limitations:['Primitive cube geometry','No semantic prompt-to-shape generation','No character rig','Turntable animation only'],promptUsedFor:['artifact name','deterministic PBR color']}}
 async verifyFile(userId:string,fileId:string){const file=this.store.getFile(fileId,userId);return this.verifyBuffer(await readFile(file.storagePath))}
 private pack(gltf:Record<string,unknown>,binary:Buffer){const json=Buffer.from(JSON.stringify(gltf)),jsonLength=align4(json.length),binLength=align4(binary.length),total=12+8+jsonLength+8+binLength,out=Buffer.alloc(total);out.writeUInt32LE(0x46546c67,0);out.writeUInt32LE(2,4);out.writeUInt32LE(total,8);out.writeUInt32LE(jsonLength,12);out.writeUInt32LE(0x4e4f534a,16);json.copy(out,20);out.fill(0x20,20+json.length,20+jsonLength);const binHeader=20+jsonLength;out.writeUInt32LE(binLength,binHeader);out.writeUInt32LE(0x004e4942,binHeader+4);binary.copy(out,binHeader+8);return out}
 private verifyBuffer(buffer:Buffer){try{if(buffer.length<28||buffer.readUInt32LE(0)!==0x46546c67||buffer.readUInt32LE(4)!==2||buffer.readUInt32LE(8)!==buffer.length)return{valid:false,errors:['Invalid GLB header/length']};const jsonLength=buffer.readUInt32LE(12);if(buffer.readUInt32LE(16)!==0x4e4f534a)return{valid:false,errors:['Missing JSON chunk']};const json=JSON.parse(buffer.subarray(20,20+jsonLength).toString('utf8').trim()) as any,errors:string[]=[];if(json.asset?.version!=='2.0')errors.push('Not glTF 2.0');if(!json.meshes?.[0]?.primitives?.[0])errors.push('Missing mesh primitive');if(json.accessors?.[0]?.count!==24||json.accessors?.[3]?.count!==36)errors.push('Unexpected geometry statistics');if(!json.materials?.[0]?.pbrMetallicRoughness)errors.push('Missing PBR material');if(!json.animations?.[0])errors.push('Missing animation');const indices=json.accessors?.[3]?.max?.[0];if(indices>=json.accessors?.[0]?.count)errors.push('Index out of bounds');return{valid:errors.length===0,errors,format:'GLB',gltfVersion:json.asset?.version,vertices:json.accessors?.[0]?.count,triangles:(json.accessors?.[3]?.count??0)/3,hasUV:Boolean(json.meshes?.[0]?.primitives?.[0]?.attributes?.TEXCOORD_0!==undefined),hasNormals:Boolean(json.meshes?.[0]?.primitives?.[0]?.attributes?.NORMAL!==undefined),hasPBR:Boolean(json.materials?.[0]),animations:json.animations?.length??0,bounds:json.accessors?.[0]?.max}}catch(error){return{valid:false,errors:[error instanceof Error?error.message:'Parse failure']}}}
 private color(prompt:string){const hash=createHash('sha256').update(prompt).digest();return[.15+hash[0]/255*.7,.15+hash[1]/255*.7,.15+hash[2]/255*.7]}
 private safeName(value:string){return value.normalize('NFKD').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80)||'snb-asset'}
}
