import { createHash, createHmac, timingSafeEqual } from 'node:crypto'
import { readFile } from 'node:fs/promises'
import { z } from 'zod'
import type { CircuitState, ToolExecution } from '../domain.js'
import { AppError } from '../lib/errors.js'
import { id, now } from '../lib/id.js'
import type { Store } from '../repositories/store.js'
import { ApprovalService } from './approvals.js'

export type ToolAction='read'|'write'|'execute'|'external'|'physical'|'irreversible'
export interface ToolManifest { id:string;name:string;version:string;description:string;category:string;capabilities:string[];inputSchema:Record<string,unknown>;outputSchema:Record<string,unknown>;permissions:ToolAction[];risk:'low'|'medium'|'high'|'critical';dependencies:string[];limits:{timeoutMs:number;maxInputBytes:number};environments:string[];hardware:string[];authentication:string[];verifier:string;status:'active'|'future-disabled' }
type Handler={schema:z.ZodType<Record<string,unknown>>;run:(input:Record<string,unknown>,userId:string)=>Promise<Record<string,unknown>>;verify:(input:Record<string,unknown>,output:Record<string,unknown>,userId:string)=>Promise<Record<string,unknown>>}

const common={version:'1.0.0',dependencies:[],environments:['singularity-api'],hardware:[],authentication:['singularity-session'],status:'active' as const}

export class ToolEcosystem {
  private manifests=new Map<string,ToolManifest>();private handlers=new Map<string,Handler>()
  constructor(private store:Store,private receiptSecret:string,private physicalEnabled=false,private approvals=new ApprovalService(store)){this.registerBuiltins()}
  list(){return [...this.manifests.values()]}
  manifest(toolId:string){const tool=this.manifests.get(toolId);if(!tool)throw new AppError('Ferramenta não registrada.',404,'TOOL_NOT_FOUND');return tool}

  async execute(userId:string,toolId:string,input:Record<string,unknown>,context:{missionId?:string;taskId?:string;approvalId?:string}={}){
    const tool=this.manifest(toolId);let policy:{allowed:boolean;approvalRequired:boolean;reason:string;physicalEnabled:boolean;approvalId?:string;approvedAt?:string}=this.policy(tool,false);if(policy.approvalRequired&&context.approvalId){const approval=this.approvals.consume(userId,context.approvalId,`tool:${tool.id}`);policy={...this.policy(tool,true),approvalId:approval.id,approvedAt:approval.decidedAt}}const startedAt=now();const execution:ToolExecution={id:id('toolrun'),userId,toolId:tool.id,toolVersion:tool.version,missionId:context.missionId,taskId:context.taskId,status:policy.allowed?'running':'denied',input,policy,startedAt}
    this.store.createToolExecution(execution)
    if(!policy.allowed){execution.completedAt=now();execution.error=policy.reason;execution.receipt=this.receipt(execution);this.store.updateToolExecution(execution);throw new AppError(policy.reason,policy.approvalRequired?409:403,policy.approvalRequired?'TOOL_APPROVAL_REQUIRED':'TOOL_POLICY_DENIED',{executionId:execution.id,policy})}
    if(Buffer.byteLength(JSON.stringify(input))>tool.limits.maxInputBytes){execution.status='denied';execution.completedAt=now();execution.error='Tool input exceeds limit';execution.receipt=this.receipt(execution);this.store.updateToolExecution(execution);throw new AppError('Entrada excede o limite da ferramenta.',413,'TOOL_INPUT_TOO_LARGE',{executionId:execution.id})}
    try{this.beforeCircuit(tool.id)}catch(error){execution.status='denied';execution.completedAt=now();execution.error=error instanceof Error?error.message:'Circuit open';execution.receipt=this.receipt(execution);this.store.updateToolExecution(execution);throw error}
    const handler=this.handlers.get(tool.id);if(!handler)throw new AppError('Ferramenta não possui executor ativo.',409,'TOOL_EXECUTOR_UNAVAILABLE')
    try{
      const parsed=handler.schema.parse(input);const result=await Promise.race([handler.run(parsed,userId),new Promise<never>((_,reject)=>setTimeout(()=>reject(new Error('Tool timeout')),tool.limits.timeoutMs))])
      if(JSON.stringify(result).length>1_000_000)throw new Error('Tool output exceeds limit')
      const verification=await handler.verify(parsed,result,userId);if(verification.verified!==true)throw new Error('Deterministic verifier rejected output')
      execution.status='completed';execution.output=result;execution.verification=verification;execution.completedAt=now();execution.receipt=this.receipt(execution);this.store.updateToolExecution(execution);this.circuitSuccess(tool.id)
      this.store.audit({id:id('audit'),userId,action:'tool.execute.completed',resource:execution.id,metadata:{toolId,verified:true},createdAt:execution.completedAt});return this.publicExecution(execution)
    }catch(error){execution.status='failed';execution.error=error instanceof Error?error.message:'Tool failure';execution.completedAt=now();execution.receipt=this.receipt(execution);this.store.updateToolExecution(execution);this.circuitFailure(tool.id,execution.error);throw new AppError('Execução da ferramenta falhou.',502,'TOOL_EXECUTION_FAILED',{executionId:execution.id,reason:execution.error})}
  }
  history(userId:string,limit=100){return this.store.listToolExecutions(userId,limit).map(item=>this.publicExecution(item))}
  get(userId:string,executionId:string){return this.publicExecution(this.store.getToolExecution(executionId,userId))}
  verifyReceipt(userId:string,executionId:string,receipt:string){const execution=this.store.getToolExecution(executionId,userId);const expected=this.receipt({...execution,receipt:undefined});const a=Buffer.from(expected),b=Buffer.from(receipt);return{valid:a.length===b.length&&timingSafeEqual(a,b),algorithm:'HMAC-SHA256',executionId}}

  private policy(tool:ToolManifest,approved:boolean){if(tool.status!=='active')return{allowed:false,approvalRequired:false,reason:'Ferramenta reservada para versão futura e sem executor ativo.',physicalEnabled:this.physicalEnabled};if(tool.permissions.includes('physical')&&!this.physicalEnabled)return{allowed:false,approvalRequired:false,reason:'Execução física está desativada por feature gate.',physicalEnabled:false};const approvalRequired=tool.risk!=='low'||tool.permissions.some(value=>['write','external','irreversible','physical'].includes(value));if(approvalRequired&&!approved)return{allowed:false,approvalRequired:true,reason:'A operação exige aprovação humana explícita.',physicalEnabled:this.physicalEnabled};return{allowed:true,approvalRequired,reason:'Policy checks passed.',physicalEnabled:this.physicalEnabled}}
  private beforeCircuit(toolId:string){const key=`tool:${toolId}`,state=this.store.getCircuitState(key);if(!state)return;if(state.state==='open'&&state.cooldownUntil&&new Date(state.cooldownUntil)>new Date())throw new AppError('Circuit breaker da ferramenta está aberto.',503,'TOOL_CIRCUIT_OPEN',{cooldownUntil:state.cooldownUntil});if(state.state==='open'){state.state='half-open';state.updatedAt=now();this.store.upsertCircuitState(state)}}
  private circuitSuccess(toolId:string){const key=`tool:${toolId}`,previous=this.store.getCircuitState(key);this.store.upsertCircuitState({resourceKey:key,state:'closed',failureCount:0,successCount:(previous?.successCount??0)+1,updatedAt:now()})}
  private circuitFailure(toolId:string,error:string){const key=`tool:${toolId}`,previous=this.store.getCircuitState(key);const failures=(previous?.failureCount??0)+1,open=failures>=3;const state:CircuitState={resourceKey:key,state:open?'open':'closed',failureCount:failures,successCount:previous?.successCount??0,openedAt:open?now():previous?.openedAt,cooldownUntil:open?new Date(Date.now()+60_000).toISOString():previous?.cooldownUntil,lastError:error,updatedAt:now()};this.store.upsertCircuitState(state)}
  private receipt(execution:ToolExecution){const canonical=JSON.stringify({id:execution.id,userId:execution.userId,toolId:execution.toolId,toolVersion:execution.toolVersion,status:execution.status,input:execution.input,output:execution.output,error:execution.error,policy:execution.policy,verification:execution.verification,startedAt:execution.startedAt,completedAt:execution.completedAt});return`hmac-sha256:${createHmac('sha256',this.receiptSecret).update(canonical).digest('hex')}`}
  private publicExecution(execution:ToolExecution){return execution}
  private register(manifest:ToolManifest,handler?:Handler){this.manifests.set(manifest.id,manifest);if(handler)this.handlers.set(manifest.id,handler)}
  private registerBuiltins(){
    const values=z.array(z.number().finite()).min(1).max(1000);const mathSchema=z.object({operation:z.enum(['sum','product','average','min','max']),values}).strict();const calculate=(x:{operation:string;values:number[]})=>x.operation==='sum'?x.values.reduce((a,b)=>a+b,0):x.operation==='product'?x.values.reduce((a,b)=>a*b,1):x.operation==='average'?x.values.reduce((a,b)=>a+b,0)/x.values.length:x.operation==='min'?Math.min(...x.values):Math.max(...x.values)
    this.register({...common,id:'core.math.aggregate',name:'Deterministic Math Aggregate',description:'Agregações numéricas sem LLM.',category:'science',capabilities:['calculation','verification'],inputSchema:{operation:'sum|product|average|min|max',values:'number[]'},outputSchema:{result:'number'},permissions:['execute'],risk:'low',limits:{timeoutMs:1000,maxInputBytes:50000},verifier:'recompute-v1'}, {schema:mathSchema as unknown as Handler['schema'],run:async input=>({result:calculate(input as {operation:string;values:number[]})}),verify:async(input,output)=>({verified:Object.is(output.result,calculate(input as {operation:string;values:number[]})),method:'independent-recompute'})})
    const textSchema=z.object({text:z.string().max(500000)}).strict();const metrics=(text:string)=>({characters:[...text].length,bytes:Buffer.byteLength(text),words:text.trim()?text.trim().split(/\s+/).length:0,lines:text?text.split(/\r?\n/).length:0,sha256:createHash('sha256').update(text).digest('hex')})
    this.register({...common,id:'core.text.metrics',name:'Text Metrics',description:'Métricas e checksum determinísticos.',category:'information',capabilities:['text-analysis','checksum'],inputSchema:{text:'string'},outputSchema:{characters:'number',bytes:'number',words:'number',lines:'number',sha256:'string'},permissions:['execute'],risk:'low',limits:{timeoutMs:1000,maxInputBytes:600000},verifier:'recompute-v1'},{schema:textSchema as unknown as Handler['schema'],run:async input=>metrics(String(input.text)),verify:async(input,output)=>({verified:JSON.stringify(output)===JSON.stringify(metrics(String(input.text))),method:'independent-recompute'})})
    const jsonSchema=z.object({data:z.record(z.string(),z.unknown()),required:z.array(z.string()).max(200).default([])}).strict();this.register({...common,id:'core.json.inspect',name:'JSON Structure Inspector',description:'Validação estrutural determinística de JSON.',category:'software',capabilities:['schema-validation'],inputSchema:{data:'object',required:'string[]'},outputSchema:{valid:'boolean',missing:'string[]'},permissions:['execute'],risk:'low',limits:{timeoutMs:1000,maxInputBytes:1000000},verifier:'schema-recheck-v1'},{schema:jsonSchema as unknown as Handler['schema'],run:async input=>{const required=input.required as string[],data=input.data as Record<string,unknown>,missing=required.filter(key=>!(key in data));return{valid:missing.length===0,missing,keys:Object.keys(data).sort()}},verify:async(input,output)=>{const missing=(input.required as string[]).filter(key=>!(key in(input.data as Record<string,unknown>)));return{verified:output.valid===(missing.length===0)&&JSON.stringify(output.missing)===JSON.stringify(missing),method:'schema-recheck'}}})
    const fileSchema=z.object({fileId:z.string().min(1)}).strict();this.register({...common,id:'core.file.verify',name:'File Integrity Verifier',description:'Recalcula SHA-256 de arquivo autorizado.',category:'files',capabilities:['file-integrity','checksum'],inputSchema:{fileId:'string'},outputSchema:{valid:'boolean',sha256:'string',size:'number'},permissions:['read','execute'],risk:'low',limits:{timeoutMs:5000,maxInputBytes:1000},verifier:'sha256-v1'},{schema:fileSchema as unknown as Handler['schema'],run:async(input,userId)=>{const file=this.store.getFile(String(input.fileId),userId),buffer=await readFile(file.storagePath),sha256=createHash('sha256').update(buffer).digest('hex');return{valid:sha256===file.checksum,sha256,size:buffer.length}},verify:async(input,output,userId)=>{const file=this.store.getFile(String(input.fileId),userId);return{verified:output.sha256===file.checksum&&output.size===file.size,method:'stored-manifest-compare'}}})
    const noteSchema=z.object({note:z.string().min(1).max(2000)}).strict();this.register({...common,id:'core.audit.note',name:'Audited Workspace Note',description:'Grava uma nota auditável após aprovação humana persistente.',category:'productivity',capabilities:['audit-write'],inputSchema:{note:'string'},outputSchema:{auditId:'string'},permissions:['write'],risk:'medium',limits:{timeoutMs:1000,maxInputBytes:3000},verifier:'audit-presence-v1'},{schema:noteSchema as unknown as Handler['schema'],run:async(input,userId)=>{const auditId=id('audit'),createdAt=now();this.store.audit({id:auditId,userId,action:'workspace.note',resource:auditId,metadata:{note:input.note},createdAt});return{auditId,createdAt}},verify:async(_input,output,userId)=>({verified:this.store.listAudit(userId,200).some(event=>event.id===output.auditId),method:'persistent-audit-presence'})})
    this.register({...common,id:'physical.robot.execute',name:'Robot Physical Execution',description:'Reservado para versões avançadas com Digital Twin, simulator, E-stop e hardware certificado.',category:'robotics',capabilities:['physical-motion'],inputSchema:{objective:'string'},outputSchema:{},permissions:['physical','external','irreversible'],risk:'critical',limits:{timeoutMs:0,maxInputBytes:0},environments:['certified-robot-runtime'],hardware:['compatible-certified-robot','emergency-stop'],authentication:['operator','safety-controller'],verifier:'digital-twin-and-sensor-safety',status:'future-disabled'})
  }
}
