import { createHash } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import type { FileAsset } from '../domain.js'
import { id, now } from '../lib/id.js'
import type { Store } from '../repositories/store.js'
import type { ArtifactGraphService } from './artifact-graph.js'

type V3=[number,number,number]
type Q4=[number,number,number,number]
const add=(a:V3,b:V3):V3=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]]
const sub=(a:V3,b:V3):V3=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]]
const scale=(v:V3,s:number):V3=>[v[0]*s,v[1]*s,v[2]*s]
const dot=(a:V3,b:V3)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2]
const length=(v:V3)=>Math.hypot(...v)
const normalize=(v:V3):V3=>{const n=length(v);return n>1e-10?scale(v,1/n):[0,0,0]}
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v))
const quatNormalize=(q:Q4):Q4=>{const n=Math.hypot(...q)||1;return q.map(v=>v/n) as Q4}

export interface AdvancedBody{id:string;position:V3;velocity:V3;rotation:Q4;angularVelocity:V3;halfExtents:V3;mass:number;friction:number;restitution:number;static?:boolean;trigger?:boolean}
export interface SkeletonBone{id:string;parent:string|null;position:V3;rotation:Q4;length:number}

export class UesAdvancedPipeline{
 constructor(private store:Store,private artifacts:ArtifactGraphService,private root=resolve('./data/uploads')){}
 capabilities(){return{owner:'UES',status:'operational-advanced-cpu-v1',systems:{semantic3d:'part hierarchy and parametric geometry',physics:'sweep-and-prune broadphase, AABB narrowphase, impulses, friction, angular integration, distance joints, triggers, raycast',animation:'FK, CCD IK, skeleton-name retargeting, continuity/contact critics',optimization:'multi-LOD vertex clustering and budget selection',quality:'structured critics and bounded correction loop'},limitations:['CPU reference implementation','AABB narrowphase does not support arbitrary convex hulls','Procedural semantics are rule-driven unless specialist parameters are supplied','No GPU raster output']}}
 semanticObject(prompt:string){const lower=prompt.toLowerCase(),kind=/urso|bear/.test(lower)?'quadruped-bear':/humano|human|personagem/.test(lower)?'humanoid':/veículo|vehicle|carro/.test(lower)?'vehicle':'generic-prop',parts:Array<[string,string|null,V3,V3]>=kind==='quadruped-bear'?[['torso',null,[0,1.2,0],[1.4,.75,.65]],['head','torso',[1.35,1.65,0],[.55,.5,.5]],['muzzle','head',[1.82,1.48,0],[.35,.25,.3]],['leg-fl','torso',[.75,.45,-.42],[.25,.8,.25]],['leg-fr','torso',[.75,.45,.42],[.25,.8,.25]],['leg-bl','torso',[-.75,.45,-.42],[.28,.8,.28]],['leg-br','torso',[-.75,.45,.42],[.28,.8,.28]]]:[['body',null,[0,0,0],[1,1,1]]];return{format:'ues-semantic-object-v1',identity:{kind,prompt},parts:parts.map(([name,parent,position,radius])=>({name,parent,position,radius,material:name==='muzzle'?'skin':'primary',function:String(name).startsWith('leg')?'locomotion':'structure'})),relations:parts.filter(part=>part[1]).map(part=>({type:'attached-to',from:part[0],to:part[1]})),verification:{uniqueParts:new Set(parts.map(part=>part[0])).size===parts.length,allParentsExist:parts.every(part=>!part[1]||parts.some(candidate=>candidate[0]===part[1]))}}}
 parametricMesh(semantic:ReturnType<UesAdvancedPipeline['semanticObject']>,segments=8){const vertices:V3[]=[],triangles:[number,number,number][]=[],partRanges:Record<string,[number,number]>={};for(const part of semantic.parts){const start=vertices.length,p=part.position as V3,r=part.radius as V3;for(let y=0;y<=segments;y++){const v=y/segments,phi=v*Math.PI;for(let x=0;x<segments;x++){const theta=x/segments*Math.PI*2;vertices.push([p[0]+r[0]*Math.sin(phi)*Math.cos(theta),p[1]+r[1]*Math.cos(phi),p[2]+r[2]*Math.sin(phi)*Math.sin(theta)])}}for(let y=0;y<segments;y++)for(let x=0;x<segments;x++){const a=start+y*segments+x,b=start+y*segments+(x+1)%segments,c=start+(y+1)*segments+x,d=start+(y+1)*segments+(x+1)%segments;triangles.push([a,c,b],[b,c,d])}partRanges[part.name]=[start,vertices.length-1]}return{format:'ues-semantic-mesh-v1',vertices,triangles,partRanges,verification:this.inspectMesh(vertices,triangles)}}
 inspectMesh(vertices:V3[],triangles:[number,number,number][]){const invalid=triangles.filter(face=>face.some(i=>!Number.isInteger(i)||i<0||i>=vertices.length)),degenerate=triangles.filter(([a,b,c])=>a===b||b===c||a===c||length(sub(vertices[b]??[0,0,0],vertices[a]??[0,0,0]))<1e-8);return{finite:vertices.flat().every(Number.isFinite),invalidIndices:invalid.length,degenerateFaces:degenerate.length,vertexCount:vertices.length,triangleCount:triangles.length,valid:vertices.length>0&&triangles.length>0&&!invalid.length&&!degenerate.length}}
 broadphase(bodies:AdvancedBody[]){const sorted=bodies.map((body,index)=>({index,min:body.position[0]-body.halfExtents[0],max:body.position[0]+body.halfExtents[0]})).sort((a,b)=>a.min-b.min),pairs:[number,number][]=[];for(let i=0;i<sorted.length;i++)for(let j=i+1;j<sorted.length&&sorted[j].min<=sorted[i].max;j++)pairs.push([sorted[i].index,sorted[j].index]);return pairs}
 private overlap(a:AdvancedBody,b:AdvancedBody){const depths:[number,number,number]=[0,1,2].map(axis=>a.halfExtents[axis]+b.halfExtents[axis]-Math.abs(a.position[axis]-b.position[axis])) as V3;if(depths.some(v=>v<=0))return null;const axis=depths.indexOf(Math.min(...depths)),normal:[number,number,number]=[0,0,0];normal[axis]=a.position[axis]<b.position[axis]?-1:1;return{depth:depths[axis],normal:normal as V3}}
 simulate(bodies:AdvancedBody[],steps=120,dt=1/60,joints:{a:string;b:string;distance:number;stiffness:number}[]=[]){const state=bodies.map(body=>({...body,position:[...body.position] as V3,velocity:[...body.velocity] as V3,rotation:quatNormalize(body.rotation),angularVelocity:[...body.angularVelocity] as V3,mass:Math.max(.001,body.mass),friction:clamp(body.friction,0,1),restitution:clamp(body.restitution,0,1)})),events:{type:string;a:string;b:string}[]=[];for(let step=0;step<clamp(steps,1,2400);step++){for(const body of state){if(body.static)continue;body.velocity[1]-=9.81*dt;body.position=add(body.position,scale(body.velocity,dt));const av=body.angularVelocity,q=body.rotation;body.rotation=quatNormalize([q[0]+.5*(av[0]*q[3]+av[1]*q[2]-av[2]*q[1])*dt,q[1]+.5*(-av[0]*q[2]+av[1]*q[3]+av[2]*q[0])*dt,q[2]+.5*(av[0]*q[1]-av[1]*q[0]+av[2]*q[3])*dt,q[3]+.5*(-av[0]*q[0]-av[1]*q[1]-av[2]*q[2])*dt]);if(body.position[1]<body.halfExtents[1]){body.position[1]=body.halfExtents[1];body.velocity[1]=Math.abs(body.velocity[1])*body.restitution;body.velocity[0]*=1-body.friction*dt*10;body.velocity[2]*=1-body.friction*dt*10}}
 for(const[i,j]of this.broadphase(state)){const a=state[i],b=state[j],hit=this.overlap(a,b);if(!hit)continue;if(a.trigger||b.trigger){events.push({type:'trigger',a:a.id,b:b.id});continue}const invA=a.static?0:1/a.mass,invB=b.static?0:1/b.mass,total=invA+invB;if(!total)continue;const correction=scale(hit.normal,hit.depth/total*.8);if(!a.static)a.position=add(a.position,scale(correction,invA));if(!b.static)b.position=sub(b.position,scale(correction,invB));const relative=dot(sub(a.velocity,b.velocity),hit.normal);if(relative<0){const impulse=-(1+Math.min(a.restitution,b.restitution))*relative/total;if(!a.static)a.velocity=add(a.velocity,scale(hit.normal,impulse*invA));if(!b.static)b.velocity=sub(b.velocity,scale(hit.normal,impulse*invB))}events.push({type:'collision',a:a.id,b:b.id})}
 for(const joint of joints){const a=state.find(x=>x.id===joint.a),b=state.find(x=>x.id===joint.b);if(!a||!b)continue;const delta=sub(b.position,a.position),distance=length(delta),error=distance-joint.distance,normal=normalize(delta),correction=scale(normal,error*clamp(joint.stiffness,0,1)*.5);if(!a.static)a.position=add(a.position,correction);if(!b.static)b.position=sub(b.position,correction)}}return{format:'ues-advanced-physics-v1',bodies:state,events:events.slice(-1000),verification:{finite:state.every(body=>[...body.position,...body.velocity,...body.rotation,...body.angularVelocity].every(Number.isFinite)),normalizedRotations:state.every(body=>Math.abs(Math.hypot(...body.rotation)-1)<1e-6),candidatePairs:this.broadphase(state).length}}}
 raycast(origin:V3,direction:V3,bodies:AdvancedBody[],maxDistance=100){const d=normalize(direction),hits=[];for(const body of bodies){let tMin=0,tMax=maxDistance;for(let axis=0;axis<3;axis++){const min=body.position[axis]-body.halfExtents[axis],max=body.position[axis]+body.halfExtents[axis];if(Math.abs(d[axis])<1e-9){if(origin[axis]<min||origin[axis]>max){tMin=Infinity;break}}else{let t1=(min-origin[axis])/d[axis],t2=(max-origin[axis])/d[axis];if(t1>t2)[t1,t2]=[t2,t1];tMin=Math.max(tMin,t1);tMax=Math.min(tMax,t2);if(tMin>tMax){tMin=Infinity;break}}}if(Number.isFinite(tMin))hits.push({bodyId:body.id,distance:tMin,point:add(origin,scale(d,tMin))})}return hits.sort((a,b)=>a.distance-b.distance)}
 forwardKinematics(bones:SkeletonBone[]){const world=new Map<string,{position:V3;rotation:Q4}>();for(const bone of bones){const parent=bone.parent?world.get(bone.parent):undefined;world.set(bone.id,{position:parent?add(parent.position,bone.position):bone.position,rotation:quatNormalize(bone.rotation)})}return Object.fromEntries(world)}
 solveCcd(points:V3[],target:V3,iterations=12){const chain=points.map(point=>[...point] as V3),lengths=chain.slice(1).map((point,i)=>length(sub(point,chain[i])));for(let iteration=0;iteration<iterations;iteration++){chain[chain.length-1]=target;for(let i=chain.length-2;i>=0;i--)chain[i]=add(chain[i+1],scale(normalize(sub(chain[i],chain[i+1])),lengths[i]));const root=points[0];chain[0]=root;for(let i=1;i<chain.length;i++)chain[i]=add(chain[i-1],scale(normalize(sub(chain[i],chain[i-1])),lengths[i-1]));if(length(sub(chain.at(-1)!,target))<1e-4)break}return{points:chain,error:length(sub(chain.at(-1)!,target)),verification:{segmentLengthsPreserved:lengths.every((value,i)=>Math.abs(length(sub(chain[i+1],chain[i]))-value)<1e-5)}}}
 retarget(source:{name:string;rotation:Q4}[],targetBones:string[],map:Record<string,string>){const sourceMap=new Map(source.map(pose=>[pose.name,pose.rotation])),pose=targetBones.map(name=>({name,rotation:quatNormalize(sourceMap.get(Object.entries(map).find(([,target])=>target===name)?.[0]??name)??[0,0,0,1])}));return{format:'ues-retarget-v1',pose,verification:{complete:pose.length===targetBones.length,normalized:pose.every(item=>Math.abs(Math.hypot(...item.rotation)-1)<1e-6)}}}
 lod(mesh:{vertices:V3[];triangles:[number,number,number][]},levels=[.02,.08,.2]){return levels.map((precision,index)=>{const key=(v:V3)=>v.map(value=>Math.round(value/precision)).join(','),map=new Map<string,number>(),vertices:V3[]=[],remap=mesh.vertices.map(v=>{const k=key(v),found=map.get(k);if(found!==undefined)return found;map.set(k,vertices.length);vertices.push(v);return vertices.length-1}),triangles=mesh.triangles.map(face=>face.map(i=>remap[i]) as [number,number,number]).filter(face=>new Set(face).size===3);return{level:index,precision,vertices,triangles}})}
 critics(input:{mesh:ReturnType<UesAdvancedPipeline['parametricMesh']>;physics:ReturnType<UesAdvancedPipeline['simulate']>;ik:ReturnType<UesAdvancedPipeline['solveCcd']>;lod:ReturnType<UesAdvancedPipeline['lod']>}){const findings:{critic:string;severity:'error'|'warning';message:string;correctable:boolean}[]=[];if(!input.mesh.verification.valid)findings.push({critic:'Topology Critic',severity:'error',message:'Mesh integrity failed',correctable:false});if(!input.physics.verification.finite)findings.push({critic:'Physics Critic',severity:'error',message:'Non-finite simulation state',correctable:false});if(input.ik.error>.05)findings.push({critic:'Animation Critic',severity:'warning',message:`IK contact error ${input.ik.error.toFixed(4)}`,correctable:true});for(let i=1;i<input.lod.length;i++)if(input.lod[i].triangles.length>input.lod[i-1].triangles.length)findings.push({critic:'Performance Critic',severity:'error',message:'LOD triangle count increased',correctable:true});return{findings,passed:!findings.some(f=>f.severity==='error'),critics:['Topology Critic','Physics Critic','Animation Critic','Performance Critic','Consistency Critic']}}
 qualityLoop(input:{points:V3[];target:V3;mesh:ReturnType<UesAdvancedPipeline['parametricMesh']>;physics:ReturnType<UesAdvancedPipeline['simulate']>;lod:ReturnType<UesAdvancedPipeline['lod']>}){const passes:{pass:number;findings:ReturnType<UesAdvancedPipeline['critics']>['findings'];action:string}[]=[],budgets=[8,24,64];let ik=this.solveCcd(input.points,input.target,budgets[0]);for(let pass=0;pass<budgets.length;pass++){const report=this.critics({mesh:input.mesh,physics:input.physics,ik,lod:input.lod}),action=report.findings.some(f=>f.critic==='Animation Critic'&&f.correctable)&&pass<budgets.length-1?'increase IK solve budget':'accept verified result';passes.push({pass:pass+1,findings:report.findings,action});if(action==='accept verified result')return{ik,report,passes,correctionAttempted:passes.length>1};ik=this.solveCcd(input.points,input.target,budgets[pass+1])}const report=this.critics({mesh:input.mesh,physics:input.physics,ik,lod:input.lod});return{ik,report,passes,correctionAttempted:true}}
 async build(userId:string,input:{projectId:string;name:string;prompt:string}){this.store.getProject(input.projectId,userId);const semantic=this.semanticObject(input.prompt),mesh=this.parametricMesh(semantic),bodies:AdvancedBody[]=[{id:'dynamic',position:[0,2,0],velocity:[.3,0,0],rotation:[0,0,0,1],angularVelocity:[0,.5,0],halfExtents:[.5,.5,.5],mass:1,friction:.6,restitution:.2},{id:'trigger',position:[.4,.5,0],velocity:[0,0,0],rotation:[0,0,0,1],angularVelocity:[0,0,0],halfExtents:[1,.5,1],mass:1,friction:0,restitution:0,static:true,trigger:true}],physics=this.simulate(bodies),raycast=this.raycast([0,5,0],[0,-1,0],physics.bodies),ikPoints:[[number,number,number],[number,number,number],[number,number,number]]=[[0,0,0],[0,1,0],[0,2,0]],ikTarget:V3=[.7,1.7,0],fk=this.forwardKinematics([{id:'root',parent:null,position:[0,0,0],rotation:[0,0,0,1],length:1},{id:'child',parent:'root',position:[0,1,0],rotation:[0,0,0,1],length:1}]),retarget=this.retarget([{name:'hip',rotation:[0,.2,0,.98]}],['pelvis'],{hip:'pelvis'}),lod=this.lod(mesh),qualityLoop=this.qualityLoop({points:ikPoints,target:ikTarget,mesh,physics,lod}),ik=qualityLoop.ik,quality=qualityLoop.report,bundle={format:'ues-advanced-production-v1',createdAt:now(),semantic,mesh,physics,raycast,animation:{ik,fk,retarget},lod,quality:{...quality,loop:{passes:qualityLoop.passes,correctionAttempted:qualityLoop.correctionAttempted}},capabilities:this.capabilities()},bytes=Buffer.from(JSON.stringify(bundle,null,2)),dir=join(this.root,userId);await mkdir(dir,{recursive:true});const fileId=id('file'),safe=input.name.replace(/[^a-zA-Z0-9._-]/g,'_'),storagePath=join(dir,`${fileId}-${safe}-advanced-ues.json`);await writeFile(storagePath,bytes,{flag:'wx'});const file:FileAsset={id:fileId,userId,projectId:input.projectId,name:`${safe}-advanced-ues.json`,mimeType:'application/vnd.snb.ues-advanced+json',size:bytes.length,checksum:createHash('sha256').update(bytes).digest('hex'),storagePath,createdAt:now()};this.store.createFile(file);const verification={valid:semantic.verification.uniqueParts&&semantic.verification.allParentsExist&&mesh.verification.valid&&physics.verification.finite&&physics.verification.normalizedRotations&&ik.verification.segmentLengthsPreserved&&retarget.verification.complete&&quality.passed,semantic:semantic.verification,mesh:mesh.verification,physics:physics.verification,ik:{error:ik.error,...ik.verification},retarget:retarget.verification,quality};const artifact=this.artifacts.register(userId,{projectId:input.projectId,fileId:file.id,type:'production.ues-advanced',producer:'ues.advanced-pipeline',verification,metadata:{internal:true,providerExecution:false,systems:Object.keys(this.capabilities().systems)},license:'Apache-2.0'});return{file:{...file,storagePath:undefined},artifact,verification,summary:{parts:semantic.parts.length,vertices:mesh.vertices.length,triangles:mesh.triangles.length,lodLevels:lod.length,physicsEvents:physics.events.length,criticFindings:quality.findings.length}}}
}
