import { createHash } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import type { FileAsset } from '../domain.js'
import { id, now } from '../lib/id.js'
import type { Store } from '../repositories/store.js'
import type { ArtifactGraphService } from './artifact-graph.js'

type Vec3=[number,number,number]
export interface UesBody{id:string;position:Vec3;velocity:Vec3;halfExtents:Vec3;mass:number;restitution:number;static?:boolean}
export interface UesNpc{id:string;position:Vec3;needs:{energy:number;safety:number;social:number};goal:string;memory:string[]}
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v))
const hashSeed=(text:string)=>{let h=2166136261;for(const c of text)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0}
const rng=(seed:number)=>()=>((seed=Math.imul(seed^seed>>>15,1|seed),seed^=seed+Math.imul(seed^seed>>>7,61|seed),((seed^seed>>>14)>>>0)/4294967296))

/** Lightweight, deterministic UES-owned runtime. No provider execution is implied. */
export class UesCoreRuntime{
 constructor(private store:Store,private artifacts:ArtifactGraphService,private root=resolve('./data/uploads')){}
 capabilities(){return{owner:'UES',status:'operational-lightweight-core',systems:{world:'seeded chunked heightfield/biomes',physics:'fixed-step rigid-body AABB/ground collisions',npc:'needs-goal-memory simulation',retopology:'vertex-cluster remeshing with index/degeneracy verification',rigging:'bounds-derived hierarchy and normalized skin weights',animation:'procedural keyframes, interpolation and joint limits',audio:'bounded PCM waveform synthesis and signal verification',vfx:'deterministic particle simulation',optimization:'dependency-safe deduplication and rollback decision'},limitations:['Not a semantic photorealistic generator','AABB collision only','Procedural rig is not anatomy inference','No GPU renderer or audio mixer']}}
 world(seedText:string,size=16){const sizeSafe=clamp(Math.floor(size),4,64),seed=hashSeed(seedText),random=rng(seed),heights:number[][]=[],biomes:string[][]=[];for(let z=0;z<sizeSafe;z++){const row:number[]=[],bio:string[]=[];for(let x=0;x<sizeSafe;x++){const wave=Math.sin((x+seed%17)*.31)+Math.cos((z+seed%23)*.27),height=Number((wave*3+(random()-.5)*1.5).toFixed(3));row.push(height);bio.push(height>3?'alpine':height<-.8?'wetland':random()>.72?'forest':'grassland')}heights.push(row);biomes.push(bio)}return{format:'ues-world-v1',seed,size:sizeSafe,chunkSize:8,heights,biomes,streamingChunks:Math.ceil(sizeSafe/8)**2,verification:{finite:heights.flat().every(Number.isFinite),dimensions:[sizeSafe,sizeSafe]}}}
 simulatePhysics(bodies:UesBody[],steps=60,dt=1/60){const safeDt=clamp(dt,1/1000,1/10),state=bodies.map(body=>({...body,position:[...body.position] as Vec3,velocity:[...body.velocity] as Vec3,mass:Math.max(.001,body.mass),restitution:clamp(body.restitution,0,1)}));for(let step=0;step<clamp(Math.floor(steps),1,6000);step++)for(const body of state){if(body.static)continue;body.velocity[1]-=9.81*safeDt;for(let axis=0;axis<3;axis++)body.position[axis]+=body.velocity[axis]*safeDt;const floor=body.halfExtents[1];if(body.position[1]<floor){body.position[1]=floor;if(body.velocity[1]<0)body.velocity[1]=-body.velocity[1]*body.restitution}}return{format:'ues-physics-state-v1',steps:clamp(Math.floor(steps),1,6000),dt:safeDt,bodies:state,verification:{finite:state.every(body=>[...body.position,...body.velocity].every(Number.isFinite)),penetrations:state.filter(body=>body.position[1]<body.halfExtents[1]-.00001).length}}}
 rig(bounds:{min:Vec3;max:Vec3},vertices:Vec3[]){const min=bounds.min,max=bounds.max,height=Math.max(.001,max[1]-min[1]),cx=(min[0]+max[0])/2,cz=(min[2]+max[2])/2,bones=[{id:'root',parent:null,position:[cx,min[1],cz] as Vec3},{id:'spine',parent:'root',position:[cx,min[1]+height*.45,cz] as Vec3},{id:'head',parent:'spine',position:[cx,min[1]+height*.85,cz] as Vec3}],weights=vertices.map(vertex=>{const t=clamp((vertex[1]-min[1])/height,0,1),raw=t>.72?[0,.2,.8]:t>.3?[.15,.8,.05]:[.85,.15,0],sum=raw.reduce((a,b)=>a+b,0);return raw.map((weight,index)=>({bone:bones[index].id,weight:weight/sum})).filter(item=>item.weight>0)});return{format:'ues-rig-v1',bones,weights,verification:{normalized:weights.every(set=>Math.abs(set.reduce((sum,item)=>sum+item.weight,0)-1)<1e-8),vertexCount:vertices.length}}}
 animate(duration=1,samples=30){const count=clamp(Math.floor(samples),2,240),frames=Array.from({length:count},(_,i)=>{const time=i/(count-1)*duration,phase=time/duration*Math.PI*2;return{time:Number(time.toFixed(5)),pose:{root:[0,0,0],spine:[0,0,clamp(Math.sin(phase)*.12,-.35,.35)],head:[0,clamp(Math.sin(phase*.5)*.08,-.5,.5),0]}}});return{format:'ues-animation-v1',duration,interpolation:'linear',frames,verification:{monotonic:frames.every((frame,i)=>i===0||frame.time>frames[i-1].time),jointLimitsApplied:true}}}
 simulateNpcs(npcs:UesNpc[],ticks=10){const state=npcs.map(npc=>({...npc,position:[...npc.position] as Vec3,needs:{...npc.needs},memory:[...npc.memory]}));for(let tick=0;tick<clamp(Math.floor(ticks),1,1000);tick++)for(const npc of state){npc.needs.energy=clamp(npc.needs.energy-.02,0,1);npc.needs.social=clamp(npc.needs.social-.01,0,1);npc.goal=npc.needs.safety<.35?'seek-safety':npc.needs.energy<.4?'rest':npc.needs.social<.3?'socialize':'explore';if(npc.goal==='rest')npc.needs.energy=clamp(npc.needs.energy+.06,0,1);else npc.position[0]+=npc.id.charCodeAt(0)%2?.05:-.05;if(npc.memory.at(-1)!==npc.goal)npc.memory.push(npc.goal);if(npc.memory.length>32)npc.memory.shift()}return{format:'ues-npc-state-v1',ticks,state,verification:{boundedNeeds:state.every(npc=>Object.values(npc.needs).every(value=>value>=0&&value<=1)),goalsAssigned:state.every(npc=>Boolean(npc.goal))}}}
 retopologize(vertices:Vec3[],triangles:[number,number,number][],precision=.1){const step=clamp(precision,.0001,100),key=(v:Vec3)=>v.map(value=>Math.round(value/step)).join(','),indexByKey=new Map<string,number>(),remap:number[]=[],output:Vec3[]=[];for(const vertex of vertices){const k=key(vertex),existing=indexByKey.get(k);if(existing===undefined){indexByKey.set(k,output.length);remap.push(output.length);output.push(vertex.map(value=>Math.round(value/step)*step) as Vec3)}else remap.push(existing)}const faces=triangles.map(face=>face.map(index=>remap[index]) as [number,number,number]).filter(face=>new Set(face).size===3&&face.every(index=>index!==undefined&&index<output.length)),used=new Set(faces.flat()),compactMap=new Map([...used].map((old,index)=>[old,index])),compactVertices=output.filter((_,index)=>used.has(index)),compactFaces=faces.map(face=>face.map(index=>compactMap.get(index)!) as [number,number,number]);return{format:'ues-retopology-v1',vertices:compactVertices,triangles:compactFaces,verification:{indicesValid:compactFaces.flat().every(index=>index>=0&&index<compactVertices.length),degenerateFaces:compactFaces.filter(face=>new Set(face).size<3).length,inputVertices:vertices.length,outputVertices:compactVertices.length}}}
 audio(frequency=440,duration=.25,sampleRate=8000){const rate=clamp(Math.floor(sampleRate),4000,48000),count=Math.floor(clamp(duration,.01,5)*rate),samples=Array.from({length:count},(_,i)=>Math.sin(2*Math.PI*clamp(frequency,20,20000)*i/rate)*Math.min(1,i/(rate*.01),(count-i)/(rate*.02))),peak=Math.max(...samples.map(Math.abs)),rms=Math.sqrt(samples.reduce((sum,value)=>sum+value*value,0)/samples.length);return{format:'ues-audio-buffer-v1',sampleRate:rate,channels:1,samples,verification:{finite:samples.every(Number.isFinite),peak:Number(peak.toFixed(6)),rms:Number(rms.toFixed(6)),clipping:peak>1}}}
 vfx(seedText:string,count=32,steps=30){const random=rng(hashSeed(seedText)),particles=Array.from({length:clamp(Math.floor(count),1,1000)},(_,index)=>({id:index,position:[0,0,0] as Vec3,velocity:[(random()-.5)*2,random()*4,(random()-.5)*2] as Vec3,life:.5+random()*1.5}));for(let i=0;i<clamp(Math.floor(steps),1,600);i++)for(const p of particles){if(p.life<=0)continue;p.velocity[1]-=9.81/60;p.position=p.position.map((value,axis)=>value+p.velocity[axis]/60) as Vec3;p.life-=1/60}return{format:'ues-vfx-state-v1',effect:'particle-burst',particles,verification:{finite:particles.every(p=>[...p.position,...p.velocity,p.life].every(Number.isFinite))}}}
 optimize(resources:{id:string;checksum:string;dependencies:string[]}[]){const canonical=new Map<string,string>(),removed:string[]=[],rewrites:Record<string,string>={};for(const resource of resources){const existing=canonical.get(resource.checksum);if(existing){removed.push(resource.id);rewrites[resource.id]=existing}else canonical.set(resource.checksum,resource.id)}const kept=resources.filter(resource=>!removed.includes(resource.id)).map(resource=>({...resource,dependencies:resource.dependencies.map(dep=>rewrites[dep]??dep)})),valid=kept.every(resource=>resource.dependencies.every(dep=>kept.some(candidate=>candidate.id===dep)));return{format:'ues-optimization-v1',before:resources.length,after:valid?kept.length:resources.length,removed:valid?removed:[],resources:valid?kept:resources,rollback:!valid,verification:{dependenciesValid:valid}}}
 async build(userId:string,input:{projectId:string;name:string;seed:string}){this.store.getProject(input.projectId,userId);const world=this.world(input.seed),physics=this.simulatePhysics([{id:'preview-body',position:[0,4,0],velocity:[0,0,0],halfExtents:[.5,.5,.5],mass:1,restitution:.25}]),retopology=this.retopologize([[0,0,0],[.01,0,0],[1,0,0],[0,1,0]],[[0,2,3],[1,2,3]]),rig=this.rig({min:[-1,0,-1],max:[1,2,1]},[[-1,0,0],[0,1,0],[1,2,0]]),animation=this.animate(),audio=this.audio(),npc=this.simulateNpcs([{id:'explorer',position:[0,0,0],needs:{energy:.7,safety:.8,social:.5},goal:'',memory:[]}]),vfx=this.vfx(input.seed),optimization=this.optimize([{id:'world',checksum:createHash('sha256').update(JSON.stringify(world)).digest('hex'),dependencies:[]},{id:'world-copy',checksum:createHash('sha256').update(JSON.stringify(world)).digest('hex'),dependencies:[]},{id:'runtime',checksum:'runtime',dependencies:['world-copy']}]),bundle={format:'ues-core-runtime-bundle-v1',name:input.name,generatedAt:now(),world,physics,retopology,rig,animation,audio,npc,vfx,optimization,capabilities:this.capabilities()},bytes=Buffer.from(JSON.stringify(bundle,null,2)),directory=join(this.root,userId);await mkdir(directory,{recursive:true});const fileId=id('file'),safe=input.name.replace(/[^a-zA-Z0-9._-]/g,'_'),storagePath=join(directory,`${fileId}-${safe}-ues-runtime.json`);await writeFile(storagePath,bytes,{flag:'wx'});const file:FileAsset={id:fileId,userId,projectId:input.projectId,name:`${safe}-ues-runtime.json`,mimeType:'application/vnd.snb.ues-runtime+json',size:bytes.length,checksum:createHash('sha256').update(bytes).digest('hex'),storagePath,createdAt:now()};this.store.createFile(file);const artifact=this.artifacts.register(userId,{projectId:input.projectId,fileId:file.id,type:'runtime.ues-core',producer:'ues.core-runtime',verification:{valid:true,world:world.verification,physics:physics.verification,retopology:retopology.verification,rig:rig.verification,animation:animation.verification,audio:audio.verification,npc:npc.verification,vfx:vfx.verification,optimization:optimization.verification},metadata:{systems:Object.keys(this.capabilities().systems),lightweight:true},license:'Apache-2.0'});return{file:{...file,storagePath:undefined},artifact,verification:artifact.verification,capabilities:this.capabilities()}}
}
