export type DomainSafety = 'standard' | 'high-stakes-informational' | 'authorized-only' | 'safety-review'
export interface CapabilityNode { id: string; index: number; name: string; domainId: string; status: 'planned' | 'foundation' | 'operational' }
export interface CapabilityDomain { id: string; name: string; safety: DomainSafety; capabilities: CapabilityNode[] }

const definitions: [string,string,DomainSafety,string[]][] = [
['science','Inteligência científica','safety-review',[
'Laboratório científico virtual','Descoberta automática de hipóteses','Geração de conjecturas matemáticas','Verificação automática de conjecturas','Simulação científica multimodal','Comparação de modelos científicos','Reconstrução de experimentos','Planejamento experimental','Análise automática de resultados','Reprodutibilidade científica','Busca científica profunda','Mapa mundial de conhecimento científico','Grafo de relações entre descobertas','Detector de contradições científicas','Sistema de revisão crítica','Comparador de artigos','Reconstrução de metodologias','Gerador de protocolos seguros','Simulador de cenários','Descoberta interdisciplinar']],
['health','Medicina e saúde responsável','high-stakes-informational',[
'Medical Knowledge Graph','Explicador de exames','Organizador de histórico fornecido pelo usuário','Comparador de evidências','Pesquisa de literatura médica','Sistema de sinais de alerta','Preparação para consultas','Educação farmacológica','Análise epidemiológica','Análise de dados biomédicos','Simulador educacional de anatomia','Atlas anatômico interativo','Laboratório médico virtual','Educação preventiva','Acompanhamento de informações de saúde fornecidas pelo usuário','Comparação de diretrizes','Detecção de inconsistências em informações médicas','Tradutor médico','Acessibilidade médica','Sistema de segunda análise informacional']],
['engineering','Engenharia universal','safety-review',[
'Engineering Core','Engenharia mecânica','Engenharia elétrica','Engenharia eletrônica','Engenharia civil','Engenharia química','Engenharia ambiental','Engenharia industrial','Engenharia de materiais','Engenharia aeroespacial','Engenharia naval','Mecatrônica','Engenharia de controle','Engenharia energética','Engenharia biomédica','Engenharia agrícola','Engenharia de software','Engenharia de sistemas','Engenharia reversa autorizada','Análise multidisciplinar de projetos']],
['mathematics','Matemática extrema','standard',[
'Math Core','Álgebra simbólica','Cálculo automático','Álgebra linear','Geometria computacional','Teoria dos números','Combinatória','Teoria dos grafos','Probabilidade','Estatística','Otimização','Equações diferenciais','Métodos numéricos','Demonstração automática','Verificação de demonstrações','Descoberta de padrões','Geração de conjecturas','Matemática visual','Matemática aplicada','Matemática para engenharia']],
['physics','Física','safety-review',[
'Physics Core','Mecânica clássica','Eletromagnetismo','Termodinâmica','Óptica','Acústica','Mecânica dos fluidos','Física estatística','Relatividade','Física quântica','Astrofísica','Cosmologia','Física computacional','Simulação de partículas','Simulação de materiais','Análise dimensional automática','Resolução física + matemática','Laboratório virtual','Visualização de fenômenos','Descoberta interdisciplinar em física']],
['chemistry','Química','safety-review',[
'Molecular Intelligence','Estrutura molecular','Estequiometria','Termodinâmica química','Cinética','Química orgânica','Química inorgânica','Química computacional','Materiais','Espectroscopia informacional','Propriedades moleculares','Análise de literatura','Modelagem molecular','Laboratório virtual seguro','Previsão de propriedades','Comparação de compostos','Química ambiental','Ciência dos materiais','Bioquímica','Interface química + engenharia']],
['biology','Biologia','safety-review',[
'Biology Core','Genética','Evolução','Ecologia','Microbiologia','Anatomia','Fisiologia','Biologia molecular','Bioinformática','Biologia computacional','Sistemas biológicos','Biodiversidade','Zoologia','Botânica','Biologia marinha','Biologia ambiental','Análise genética informacional','Modelagem de populações','Análise de literatura','Descoberta interdisciplinar']],
['agriculture','Agricultura','safety-review',[
'Agricultural Intelligence','Análise de solo','Planejamento de plantio','Agricultura de precisão','Análise visual de culturas','Irrigação inteligente','Planejamento hídrico','Previsão de produtividade','Gestão de estufas','Automação agrícola','Sensores agrícolas','Drones agrícolas','Análise climática','Detecção de problemas em plantas','Planejamento de colheita','Armazenamento','Logística agrícola','Sustentabilidade agrícola','Otimização de recursos','Simulador agrícola']],
['fabrication','Construção física e fabricação','safety-review',[
'Physical Construction Core','Fabricação manual','Marcenaria','Metalurgia','Eletrônica prática','Mecânica prática','Prototipagem','Impressão 3D','Fabricação digital','Ferramentas caseiras','Reutilização de materiais','Engenharia com sucata','Construção com papel','Construção com papelão','Protótipos educacionais','Máquinas didáticas','Mecanismos mecânicos','Transmissão de movimento','Estruturas','Análise de estabilidade']],
['robotics','Robótica','safety-review',[
'Robotics Core','Projeto de robôs','Cinemática','Dinâmica','Controle','Sensores','Atuadores','Visão robótica','Navegação','Planejamento de movimento','Simulação robótica','Digital twins','Robôs educacionais','Robótica doméstica','Robótica agrícola','Robótica industrial conceitual','Diagnóstico de robôs','Otimização mecânica','Geração de controladores','Integração hardware/software']],
['cybersecurity','Cybersegurança ética','authorized-only',[
'Security Core','Threat modeling','Análise de vulnerabilidades','Análise de código','Hardening','Segurança de APIs','Segurança web','Segurança mobile','Segurança de redes','Análise de logs','Detecção de anomalias','Resposta a incidentes','Sandbox','Forense digital','Análise de malware em ambiente controlado','Pentest autorizado','Auditoria de configuração','Segurança de identidade','Privacidade','Modelagem de ataques']],
['data-science','Ciência de dados','standard',[
'Data Intelligence Core','Limpeza automática','Exploração de datasets','Detecção de anomalias','Visualização automática','Descoberta de correlações','Análise estatística','Previsão','Clustering','Classificação','Análise temporal','Análise causal com ressalvas','Geração de dashboards','Explicação de modelos','Engenharia de dados','Pipelines automáticos','Análise multimodal','Comparação de datasets','Auditoria de dados','Data storytelling']],
['education','Educação','standard',[
'Universal Tutor','Professor adaptativo','Diagnóstico de conhecimento','Currículo dinâmico','Aulas multimodais','Exercícios personalizados','Avaliação adaptativa','Simuladores educacionais','Laboratório virtual','Tutor de programação','Tutor de matemática','Tutor científico','Tutor de idiomas','Explicação por múltiplas perspectivas','Detecção de lacunas','Recuperação de conteúdo antigo','Aprendizagem baseada em projetos','Professor + aluno + IA','Geração de material didático','Mapa de evolução do conhecimento']],
['architecture','Arquitetura e urbanismo','safety-review',[
'Architectural Intelligence','Geração de layouts','Análise espacial','Planejamento arquitetônico conceitual','Geração de ambientes 3D','Iluminação','Materiais','Acústica','Eficiência energética','Acessibilidade','Circulação','Urbanismo','Planejamento urbano','Análise ambiental','Simulação de ocupação','Visualização arquitetônica','Integração CAD/3D','Documentação','Análise de alternativas','Otimização de espaço']],
['logistics','Logística','standard',[
'Logistics Core','Otimização de rotas','Planejamento de frota','Estoque','Cadeia de suprimentos','Previsão de demanda','Distribuição','Armazenamento','Simulação logística','Análise de gargalos','Otimização multiobjetivo','Planejamento de contingência','Rastreamento','Gestão de recursos','Redução de desperdício','Planejamento de última milha','Análise de custos','Cenários hipotéticos','Previsão de interrupções','Logística sustentável']],
['sustainability','Sustentabilidade','standard',[
'Sustainability Core','Análise energética','Consumo de água','Análise de desperdício','Reciclagem','Reutilização','Materiais alternativos','Economia circular','Eficiência energética','Planejamento sustentável','Análise ambiental','Agricultura sustentável','Construção sustentável','Transporte sustentável','Otimização de recursos','Análise de ciclo de vida','Redução de resíduos','Recuperação de materiais','Design sustentável','Simulador de impacto']],
['computing','Computadores','safety-review',[
'PC Builder Intelligence','Compatibilidade de componentes','Montagem','Diagnóstico','Troubleshooting','Refrigeração','Energia','Armazenamento','Redes','Sistemas operacionais','Otimização','Benchmark','Diagnóstico automatizado','Planejamento de upgrades','Recuperação de sistemas','Configuração de software','Gerenciamento de arquivos','Virtualização','Servidores','Infraestrutura doméstica']],
['communication','Comunicação, música e linguagem','standard',[
'Communication Core','Tradução contextual','Interpretação de intenção','Comunicação técnica','Comunicação científica','Apresentação','Argumentação','Escrita profissional','Literatura','Roteiro','Composição musical','Arranjo','Teoria musical','Produção musical','Sound design','Áudio para jogos','Narração','Síntese de voz quando disponível','Análise linguística','Preservação de contexto cultural']],
['legal-business','Direito e administração','high-stakes-informational',[
'Legal Research Core','Pesquisa legislativa','Comparação de leis','Análise documental','Contratos informacionais','Jurisprudência','Organização de processos','Identificação de questões jurídicas','Comparação de versões','Explicação de linguagem jurídica','Business Intelligence','Gestão empresarial','Administração','Planejamento estratégico','Gestão de projetos','Processos','Indicadores','Análise operacional','Gestão de conhecimento','Documentação empresarial']],
]

let capabilityIndex = 0
export const capabilityDomains: CapabilityDomain[] = definitions.map(([id,name,safety,items]) => ({ id,name,safety,capabilities: items.map(item => { capabilityIndex++; return { id: `uc-${String(capabilityIndex).padStart(3,'0')}`, index: capabilityIndex, name:item, domainId:id, status:'planned' as const } }) }))
export const universalCapabilities = capabilityDomains.flatMap(domain => domain.capabilities)
export const emergingDomains = ['Geociências','Meteorologia','Oceanografia','Transporte','Aviação','Astronomia observacional','Preservação cultural','Tecnologias assistivas','Governança pública','Economia','Manutenção industrial','Design de produtos físicos','Gestão de emergências','Comunidades'].map((name,index)=>({id:`emerging-${String(index+1).padStart(2,'0')}`,name,status:'discovery' as const,requirements:['mapear conhecimento','identificar ferramentas','compor especialistas','criar benchmarks','validar taxonomia']}))
if (universalCapabilities.length !== 380) throw new Error(`Universal Capability Registry inválido: esperado 380, recebido ${universalCapabilities.length}.`)
if (emergingDomains.length !== 14) throw new Error('Emerging Domain Registry inválido.')
