import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { strFromU8, strToU8, unzipSync, zipSync } from 'fflate'
import type { FileAsset } from '../domain.js'
import { AppError } from '../lib/errors.js'
import { id, now } from '../lib/id.js'
import type { Store } from '../repositories/store.js'
import type { ArtifactGraphService } from './artifact-graph.js'

type DocumentFormat='pdf'|'docx'|'xlsx'|'pptx'|'markdown'|'csv'
const xml=(value:string)=>value.split('').filter(char=>{const code=char.charCodeAt(0);return code===9||code===10||code===13||code>=32}).join('').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[char]!))
const pdfText=(value:string)=>value.replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\x7E]/g,'?')
const contentTypes=(overrides:string[])=>`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/>${overrides.join('')}</Types>`
const rootRels=(target:string,type:string)=>`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="${type}" Target="${target}"/></Relationships>`
const zip=(files:Record<string,string>)=>Buffer.from(zipSync(Object.fromEntries(Object.entries(files).map(([name,value])=>[name,strToU8(value)])),{level:6}))

export class UniversalDocumentEngine{
 constructor(private store:Store,private artifacts:ArtifactGraphService,private root=resolve('./data/uploads')){}
 capabilities(){return{owner:'SNB',status:'operational-structured-documents-v1',formats:{pdf:'native PDF 1.4 text document',docx:'OOXML word-processing package',xlsx:'OOXML spreadsheet package',pptx:'OOXML presentation package',markdown:'UTF-8 Markdown',csv:'RFC 4180-style UTF-8 CSV'},verification:'format signatures, required package parts, XML parse-safe escaping, checksum and read-back',limitations:['Text/table/slide primitives only','No complex charts, formulas, embedded media or font shaping','PDF non-ASCII characters are conservatively replaced in the V1 writer']}}
 async create(userId:string,input:{projectId:string;name:string;title:string;paragraphs:string[];table?:string[][];formats:DocumentFormat[]}){this.store.getProject(input.projectId,userId);const formats=[...new Set(input.formats)],results=[];for(const format of formats){const bytes=this.generate(format,input),verification=this.verifyBytes(format,bytes);if(!verification.valid)throw new AppError(`Generated ${format} failed structural verification.`,500,'DOCUMENT_VERIFICATION_FAILED',verification);const file=await this.persist(userId,input.projectId,`${input.name}.${format}`,this.mime(format),bytes),artifact=this.artifacts.register(userId,{projectId:input.projectId,fileId:file.id,type:`document.${format}`,producer:'snb.universal-document-engine',verification,metadata:{title:input.title,paragraphs:input.paragraphs.length,rows:input.table?.length??0,format},license:'Apache-2.0'});results.push({file:{...file,storagePath:undefined},artifact,verification})}return{documents:results,summary:{requested:formats.length,verified:results.filter(result=>result.artifact.status==='verified').length,totalBytes:results.reduce((sum,result)=>sum+result.file.size,0)},capabilities:this.capabilities()}}
 async verifyFile(userId:string,fileId:string){const file=this.store.getFile(fileId,userId),format=file.name.split('.').at(-1) as DocumentFormat,bytes=await readFile(file.storagePath);if(!['pdf','docx','xlsx','pptx','markdown','csv'].includes(format))throw new AppError('Unsupported document format.',400,'DOCUMENT_FORMAT_UNSUPPORTED');return this.verifyBytes(format,bytes)}
 generate(format:DocumentFormat,input:{title:string;paragraphs:string[];table?:string[][]}){switch(format){case'pdf':return this.pdf(input.title,input.paragraphs);case'docx':return this.docx(input.title,input.paragraphs);case'xlsx':return this.xlsx(input.title,input.table??input.paragraphs.map(value=>[value]));case'pptx':return this.pptx(input.title,input.paragraphs);case'markdown':return Buffer.from(`# ${input.title}\n\n${input.paragraphs.join('\n\n')}\n`);case'csv':return Buffer.from((input.table??input.paragraphs.map(value=>[value])).map(row=>row.map(value=>`"${value.replace(/"/g,'""')}"`).join(',')).join('\r\n')+'\r\n')}}
 verifyBytes(format:DocumentFormat,bytes:Buffer){const checksum=createHash('sha256').update(bytes).digest('hex'),base={format,size:bytes.length,checksum,nonEmpty:bytes.length>0};if(format==='pdf'){const text=bytes.toString('latin1'),valid=text.startsWith('%PDF-1.4')&&text.includes('xref')&&text.includes('%%EOF')&&/\/Type\s*\/Page\b/.test(text);return{...base,valid,signature:'%PDF-1.4',pageCount:(text.match(/\/Type\s*\/Page\b/g)??[]).length}}if(['docx','xlsx','pptx'].includes(format)){try{const files=unzipSync(bytes),required=format==='docx'?['[Content_Types].xml','_rels/.rels','word/document.xml']:format==='xlsx'?['[Content_Types].xml','_rels/.rels','xl/workbook.xml','xl/worksheets/sheet1.xml']:['[Content_Types].xml','_rels/.rels','ppt/presentation.xml','ppt/slides/slide1.xml'],missing=required.filter(name=>!files[name]),xmlParts=Object.entries(files).filter(([name])=>name.endsWith('.xml')).map(([,data])=>strFromU8(data)),wellFormedEnvelope=xmlParts.every(value=>value.startsWith('<?xml')&&value.includes('>'));return{...base,valid:!missing.length&&wellFormedEnvelope,container:'ZIP/OOXML',partCount:Object.keys(files).length,missing}}catch(error){return{...base,valid:false,error:error instanceof Error?error.message:'Invalid ZIP'}}}const text=bytes.toString('utf8'),valid=text.length>0&&!text.includes('\u0000');return{...base,valid,encoding:'utf-8',lines:text.split(/\r?\n/).length}}
 private pdf(title:string,paragraphs:string[]){const lines=[title,...paragraphs.flatMap(value=>this.wrap(value,88))].slice(0,45),stream=`BT /F1 16 Tf 50 760 Td (${pdfText(lines[0]??'Document')}) Tj /F1 10 Tf 0 -24 Td ${lines.slice(1).map(line=>`(${pdfText(line)}) Tj 0 -14 Td`).join(' ')} ET`,objects=[`<< /Type /Catalog /Pages 2 0 R >>`,`<< /Type /Pages /Kids [3 0 R] /Count 1 >>`,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>`,`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`,`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`];let output='%PDF-1.4\n%SNB\n';const offsets=[0];objects.forEach((object,index)=>{offsets.push(Buffer.byteLength(output,'latin1'));output+=`${index+1} 0 obj\n${object}\nendobj\n`});const xref=Buffer.byteLength(output,'latin1');output+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(offset=>`${String(offset).padStart(10,'0')} 00000 n `).join('\n')}\ntrailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;return Buffer.from(output,'latin1')}
 private docx(title:string,paragraphs:string[]){const p=(value:string,style='')=>`<w:p>${style?`<w:pPr><w:pStyle w:val="${style}"/></w:pPr>`:''}<w:r><w:t xml:space="preserve">${xml(value)}</w:t></w:r></w:p>`,document=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${p(title,'Title')}${paragraphs.map(value=>p(value)).join('')}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/></w:sectPr></w:body></w:document>`;return zip({'[Content_Types].xml':contentTypes(['<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>']),'_rels/.rels':rootRels('word/document.xml','http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument'),'word/document.xml':document})}
 private xlsx(title:string,table:string[][]){const rows=[[title],...table].map((row,r)=>`<row r="${r+1}">${row.map((value,c)=>`<c r="${this.column(c)}${r+1}" t="inlineStr"><is><t>${xml(value)}</t></is></c>`).join('')}</row>`).join(''),sheet=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rows}</sheetData></worksheet>`,workbook='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="SNB Document" sheetId="1" r:id="rId1"/></sheets></workbook>',rels='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>';return zip({'[Content_Types].xml':contentTypes(['<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>','<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>']),'_rels/.rels':rootRels('xl/workbook.xml','http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument'),'xl/workbook.xml':workbook,'xl/_rels/workbook.xml.rels':rels,'xl/worksheets/sheet1.xml':sheet})}
 private pptx(title:string,paragraphs:string[]){const text=[title,...paragraphs.slice(0,8)].map((value,index)=>`<a:p><a:r><a:rPr lang="pt-BR" sz="${index?1800:2800}"/><a:t>${xml(value)}</a:t></a:r><a:endParaRPr lang="pt-BR"/></a:p>`).join(''),slide=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/><p:sp><p:nvSpPr><p:cNvPr id="2" name="Content"/><p:cNvSpPr txBox="1"/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="457200" y="457200"/><a:ext cx="8229600" cy="5943600"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/></p:spPr><p:txBody><a:bodyPr/><a:lstStyle/>${text}</p:txBody></p:sp></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>`,presentation='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:sldIdLst><p:sldId id="256" r:id="rId1"/></p:sldIdLst><p:sldSz cx="9144000" cy="6858000" type="screen4x3"/><p:notesSz cx="6858000" cy="9144000"/></p:presentation>',rels='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide1.xml"/></Relationships>';return zip({'[Content_Types].xml':contentTypes(['<Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>','<Override PartName="/ppt/slides/slide1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>']),'_rels/.rels':rootRels('ppt/presentation.xml','http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument'),'ppt/presentation.xml':presentation,'ppt/_rels/presentation.xml.rels':rels,'ppt/slides/slide1.xml':slide})}
 private async persist(userId:string,projectId:string,name:string,mimeType:string,bytes:Buffer){const directory=join(this.root,userId);await mkdir(directory,{recursive:true});const fileId=id('file'),safe=name.replace(/[^a-zA-Z0-9._-]/g,'_'),storagePath=join(directory,`${fileId}-${safe}`);await writeFile(storagePath,bytes,{flag:'wx'});const file:FileAsset={id:fileId,userId,projectId,name:safe,mimeType,size:bytes.length,checksum:createHash('sha256').update(bytes).digest('hex'),storagePath,createdAt:now()};this.store.createFile(file);return file}
 private mime(format:DocumentFormat){return({pdf:'application/pdf',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',pptx:'application/vnd.openxmlformats-officedocument.presentationml.presentation',markdown:'text/markdown',csv:'text/csv'} as const)[format]}
 private wrap(value:string,width:number){const words=value.trim().split(/\s+/),lines:string[]=[];let line='';for(const word of words){if(line&&`${line} ${word}`.length>width){lines.push(line);line=word}else line=line?`${line} ${word}`:word}if(line)lines.push(line);return lines}
 private column(index:number){let value='',current=index+1;while(current){current--;value=String.fromCharCode(65+current%26)+value;current=Math.floor(current/26)}return value}
}
