export type GapState='PARTIAL'|'ADAPTER_REQUIRED'|'INFRASTRUCTURE_REQUIRED'|'BLOCKED'|'PLANNED'
export interface V1Gap{id:string;area:'SNB'|'UES'|'DsOS'|'SNB Infrastructure';name:string;state:GapState;dependency:string;activation:string}
export const v1Gaps:V1Gap[]=[
{id:'snb-specialist-execution',area:'SNB',name:'End-to-end specialist model execution',state:'PARTIAL',dependency:'Canonical Puter specialist outputs now have persistent client-reported handoffs, independent-model reviews and HMAC receipts; automatic revision execution, multi-round consensus and final integration receipts remain',activation:'2–6 real specialist outputs → critique → correction → verified integrated artifact'},
{id:'snb-critic-correction',area:'SNB',name:'Autonomous multi-domain correction execution',state:'PARTIAL',dependency:'Revision findings now generate idempotent correction + independent re-review tasks and verified lineage receipts; automatic Puter invocation, artifact-level regression metrics and rollback remain',activation:'Autonomous finding → model/tool correction → artifact re-test → rollback/accept across domains'},
{id:'ues-semantic-3d',area:'UES',name:'Semantic text/image-to-3D',state:'PARTIAL',dependency:'UES Advanced now executes semantic part graphs and parametric meshes; specialist-derived arbitrary geometry, anatomy constraints and visual benchmarks remain',activation:'Arbitrary semantic corpus artifacts + geometry/anatomy critic benchmarks'},
{id:'ues-retopology',area:'UES',name:'Automatic retopology',state:'PARTIAL',dependency:'UES Core has verified vertex-cluster remeshing; semantic edge-flow constraints, manifold repair and deformation corpus remain',activation:'Topology verifier and deformation tests'},
{id:'ues-rigging',area:'UES',name:'Advanced semantic rigging and skinning',state:'PARTIAL',dependency:'UES Core has verified bounds-derived bones and normalized weights; anatomy inference and deformation quality remain',activation:'Skeleton/weights artifact verification'},
{id:'ues-motion',area:'UES',name:'Semantic animation and retargeting',state:'PARTIAL',dependency:'UES Advanced adds FK, iterative IK, segment preservation and mapped retargeting; joint constraints, foot locking, blending and motion corpus remain',activation:'Foot contact, limits and continuity tests'},
{id:'ues-world',area:'UES',name:'Advanced semantic world generation',state:'PARTIAL',dependency:'UES Core has deterministic heightfields, biomes and chunk metadata; semantic roads, cities, vegetation and runtime streaming remain',activation:'World graph artifacts and streaming tests'},
{id:'ues-physics',area:'UES',name:'Advanced physics runtime',state:'PARTIAL',dependency:'UES Advanced adds sweep-and-prune, AABB impulses, friction, quaternion angular integration, distance joints, triggers and raycasts; convex narrowphase, CCD and solver islands remain',activation:'Deterministic simulation tests'},
{id:'ues-npc',area:'UES',name:'Advanced NPC society runtime',state:'PARTIAL',dependency:'UES Core has needs, goals, bounded memory and deterministic ticks; navigation, relationships, economy and scale remain',activation:'Artificial-player/runtime benchmarks'},
{id:'ues-audio',area:'UES',name:'Audio generation and runtime',state:'PARTIAL',dependency:'UES Core has verified PCM waveform synthesis; mixer, spatial graph, event synchronization, asset codecs and loudness gates remain',activation:'Audio artifacts, loudness/loop/codec checks'},
{id:'ues-vfx',area:'UES',name:'Advanced VFX production/runtime',state:'PARTIAL',dependency:'UES Core has deterministic particle state simulation; renderer shaders, fluid/smoke models and performance gates remain',activation:'Effect artifacts and performance gates'},
{id:'ues-multiplayer',area:'UES',name:'Multiplayer runtime',state:'PARTIAL',dependency:'UES-owned authority, replication, reconciliation and adversarial network simulation are not yet implemented',activation:'Network simulation and security tests'},
{id:'ues-profiler',area:'UES',name:'CPU/GPU profiler',state:'PARTIAL',dependency:'Runtime metrics adapters',activation:'Measured frame/resource telemetry'},
{id:'ues-optimizer',area:'UES',name:'Quality-preserving optimization loop',state:'PARTIAL',dependency:'UES Advanced adds verified multi-LOD clustering and structured performance critics; measured renderer telemetry and perceptual regression remain',activation:'Before/after benchmark with rollback'},
{id:'ues-reference-ai',area:'UES',name:'Reference Intelligence',state:'PARTIAL',dependency:'Vision analysis and rights policy',activation:'Reference-derived constraint artifacts'},
{id:'ues-super-resolution',area:'UES',name:'SNB Super Resolution',state:'PARTIAL',dependency:'UES-owned reconstruction filters, motion/depth production and objective native-vs-reconstructed benchmarks remain',activation:'Native-vs-reconstructed benchmark'},
{id:'ues-frameflow',area:'UES',name:'SNB FrameFlow',state:'PARTIAL',dependency:'UES-owned motion/depth buffers, interpolation and measured frame-pacing implementation remain',activation:'Real/generated FPS and latency report'},
{id:'dsos-source',area:'DsOS',name:'Source checkout workspace',state:'ADAPTER_REQUIRED',dependency:'Isolated Git/source worker',activation:'Pinned source checksum and provenance'},
{id:'dsos-rootfs',area:'DsOS',name:'Reproducible Linux rootfs',state:'INFRASTRUCTURE_REQUIRED',dependency:'Linux toolchain/container worker',activation:'Image hash reproducibility'},
{id:'dsos-qemu',area:'DsOS',name:'QEMU boot test',state:'INFRASTRUCTURE_REQUIRED',dependency:'QEMU runtime and image',activation:'Boot/console health receipt'},
{id:'dsos-android',area:'DsOS',name:'DivineDroid build',state:'INFRASTRUCTURE_REQUIRED',dependency:'Android sources/toolchain/emulator/signing',activation:'Emulator launch and compliance report'},
{id:'dsos-wincompat',area:'DsOS',name:'DivineWin compatibility runtime',state:'ADAPTER_REQUIRED',dependency:'Legally reusable compatibility runtime',activation:'Win32 compatibility test corpus'},
{id:'dsos-driver',area:'DsOS',name:'Hardware/driver evidence graph',state:'PLANNED',dependency:'Hardware probes and driver metadata',activation:'Compatibility and rollback evidence'},
{id:'dsos-package',area:'DsOS',name:'Package trust network',state:'PLANNED',dependency:'Signatures, SBOM, licenses and vulnerability feeds',activation:'Package policy tests'},
]
if(v1Gaps.some(gap=>(gap as any).state==='ACTIVE'))throw new Error('V1 gap registry cannot contain ACTIVE items')
