export type GapState='PARTIAL'|'ADAPTER_REQUIRED'|'INFRASTRUCTURE_REQUIRED'|'BLOCKED'|'PLANNED'
export interface V1Gap{id:string;area:'UES'|'DsOS'|'SNB Infrastructure';name:string;state:GapState;dependency:string;activation:string}
export const v1Gaps:V1Gap[]=[
{id:'ues-semantic-3d',area:'UES',name:'Semantic text/image-to-3D',state:'ADAPTER_REQUIRED',dependency:'Licensed advanced 3D provider/toolchain',activation:'Adapter + artifact + geometry benchmarks'},
{id:'ues-retopology',area:'UES',name:'Automatic retopology',state:'ADAPTER_REQUIRED',dependency:'Mesh processing provider',activation:'Topology verifier and deformation tests'},
{id:'ues-rigging',area:'UES',name:'Character rigging and skinning',state:'ADAPTER_REQUIRED',dependency:'Rigging provider/tool',activation:'Skeleton/weights artifact verification'},
{id:'ues-motion',area:'UES',name:'Semantic animation and retargeting',state:'ADAPTER_REQUIRED',dependency:'Motion provider and rig',activation:'Foot contact, limits and continuity tests'},
{id:'ues-world',area:'UES',name:'Semantic world generation',state:'PARTIAL',dependency:'Terrain/scene/runtime capabilities',activation:'World graph artifacts and streaming tests'},
{id:'ues-physics',area:'UES',name:'Physics abstraction/runtime',state:'ADAPTER_REQUIRED',dependency:'Physics backend',activation:'Deterministic simulation tests'},
{id:'ues-npc',area:'UES',name:'NPC society runtime',state:'PLANNED',dependency:'Navigation, behavior and scalable simulation',activation:'Artificial-player/runtime benchmarks'},
{id:'ues-audio',area:'UES',name:'Audio generation and runtime',state:'ADAPTER_REQUIRED',dependency:'Audio providers and verifier',activation:'Audio artifacts, loudness/loop/codec checks'},
{id:'ues-vfx',area:'UES',name:'VFX production/runtime',state:'PLANNED',dependency:'Target runtime and GPU worker',activation:'Effect artifacts and performance gates'},
{id:'ues-multiplayer',area:'UES',name:'Multiplayer runtime',state:'PLANNED',dependency:'Server authority, replication and test workers',activation:'Network simulation and security tests'},
{id:'ues-engine-adapters',area:'UES',name:'Godot/Unity/Unreal/Roblox adapters',state:'INFRASTRUCTURE_REQUIRED',dependency:'Installed engines/plugins/licensed tooling',activation:'Import/build/launch integration tests'},
{id:'ues-gpu-workers',area:'UES',name:'Remote GPU compute fabric',state:'INFRASTRUCTURE_REQUIRED',dependency:'GPU workers/provider',activation:'Lease, receipt, artifact and cleanup tests'},
{id:'ues-profiler',area:'UES',name:'CPU/GPU profiler',state:'PARTIAL',dependency:'Runtime metrics adapters',activation:'Measured frame/resource telemetry'},
{id:'ues-optimizer',area:'UES',name:'Quality-preserving optimization loop',state:'PLANNED',dependency:'Profiler and visual quality metrics',activation:'Before/after benchmark with rollback'},
{id:'ues-build-matrix',area:'UES',name:'Multi-target build matrix',state:'ADAPTER_REQUIRED',dependency:'Target build workers',activation:'Reproducible build and launch receipts'},
{id:'ues-reference-ai',area:'UES',name:'Reference Intelligence',state:'PARTIAL',dependency:'Vision analysis and rights policy',activation:'Reference-derived constraint artifacts'},
{id:'ues-super-resolution',area:'UES',name:'SNB Super Resolution',state:'PLANNED',dependency:'Renderer, motion/depth buffers and GPU benchmarks',activation:'Native-vs-reconstructed benchmark'},
{id:'ues-frameflow',area:'UES',name:'SNB FrameFlow',state:'PLANNED',dependency:'Renderer motion/depth and frame pacing',activation:'Real/generated FPS and latency report'},
{id:'ues-hsds-av',area:'UES',name:'HSDS GPU audiovisual streaming',state:'INFRASTRUCTURE_REQUIRED',dependency:'GPU render worker, framebuffer/audio capture, AV1/VP9/H.264 + Opus encoders and WebRTC STUN/TURN',activation:'Framebuffer → encode → WebRTC playback → input → next-frame latency/quality test with provider receipt'},
{id:'dsos-source',area:'DsOS',name:'Source checkout workspace',state:'ADAPTER_REQUIRED',dependency:'Isolated Git/source worker',activation:'Pinned source checksum and provenance'},
{id:'dsos-rootfs',area:'DsOS',name:'Reproducible Linux rootfs',state:'INFRASTRUCTURE_REQUIRED',dependency:'Linux toolchain/container worker',activation:'Image hash reproducibility'},
{id:'dsos-qemu',area:'DsOS',name:'QEMU boot test',state:'INFRASTRUCTURE_REQUIRED',dependency:'QEMU runtime and image',activation:'Boot/console health receipt'},
{id:'dsos-android',area:'DsOS',name:'DivineDroid build',state:'INFRASTRUCTURE_REQUIRED',dependency:'Android sources/toolchain/emulator/signing',activation:'Emulator launch and compliance report'},
{id:'dsos-wincompat',area:'DsOS',name:'DivineWin compatibility runtime',state:'ADAPTER_REQUIRED',dependency:'Legally reusable compatibility runtime',activation:'Win32 compatibility test corpus'},
{id:'dsos-driver',area:'DsOS',name:'Hardware/driver evidence graph',state:'PLANNED',dependency:'Hardware probes and driver metadata',activation:'Compatibility and rollback evidence'},
{id:'dsos-package',area:'DsOS',name:'Package trust network',state:'PLANNED',dependency:'Signatures, SBOM, licenses and vulnerability feeds',activation:'Package policy tests'},
{id:'infra-https',area:'SNB Infrastructure',name:'Public HTTPS',state:'INFRASTRUCTURE_REQUIRED',dependency:'Domain, DNS, certificate and reverse proxy',activation:'Deployment TLS test'},
{id:'infra-email',area:'SNB Infrastructure',name:'Transactional e-mail',state:'INFRASTRUCTURE_REQUIRED',dependency:'SMTP/provider and domain',activation:'Delivery/bounce/rate-limit tests'},
{id:'infra-browser',area:'SNB Infrastructure',name:'Chromium E2E worker',state:'INFRASTRUCTURE_REQUIRED',dependency:'Browser binary/connected CI',activation:'Playwright suite and traces'},
{id:'infra-ssef',area:'SNB Infrastructure',name:'Secure arbitrary execution fabric',state:'INFRASTRUCTURE_REQUIRED',dependency:'Container/microVM isolation',activation:'Escape, network and resource-limit tests'},
{id:'infra-object-storage',area:'SNB Infrastructure',name:'Remote artifact storage',state:'ADAPTER_REQUIRED',dependency:'S3-compatible provider',activation:'Upload/download/hash/failure tests'},
]
if(v1Gaps.some(gap=>(gap as any).state==='ACTIVE'))throw new Error('V1 gap registry cannot contain ACTIVE items')
