import { useCallback, useEffect, useMemo, useState } from 'react'
import { api } from './lib/api'
import { runResearchSwarm } from './lib/web-research'
import {
  Activity, ArrowUpRight, Atom, BarChart3, Bot, Box, BrainCircuit, Check, CheckCircle2,
  ChevronDown, ChevronRight, Circle, Clock3, Code2, Compass, Copy, Database, Download,
  ExternalLink, Eye, FileText, Filter, GitFork, Globe2, Grid3X3, Heart, History, Image,
  Infinity as InfinityIcon, Layers3, Link2, Lock, MoreHorizontal, Network, Orbit, Pause,
  Play, Plus, Radio, RefreshCw, Rocket, Search, Share2, ShieldCheck, SlidersHorizontal,
  Sparkles, Star, TestTube2, Users, WandSparkles, Workflow, X, Zap, type LucideIcon
} from 'lucide-react'

type Props={id:string;notify:(message:string)=>void}
function Header({eyebrow,title,description,action,onAction}:{eyebrow:string;title:string;description:string;action?:string;onAction?:()=>void}){return <header className="workspace-header"><div><span className="kicker">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action&&<button className="primary-action" onClick={onAction}><Plus size={16}/>{action}</button>}</header>}

const sources=[
  {title:'Adaptive routing in compound AI systems',domain:'research.example.org',score:98,kind:'Paper'},
  {title:'State of autonomous software engineering',domain:'technology-review.example',score:96,kind:'Analysis'},
  {title:'Evaluating reliability in multi-agent workflows',domain:'institute.example.edu',score:94,kind:'Study'},
  {title:'Context engines and long-running AI projects',domain:'engineering.example.com',score:92,kind:'Technical'},
]
function Research({notify}:Pick<Props,'notify'>){
  const[query,setQuery]=useState(''),[running,setRunning]=useState(false),[progress,setProgress]=useState(''),[result,setResult]=useState<{answer:string;sources:{url:string;title?:string}[];researchers:{provider:string;modelId:string;citations:number}[];failures:{provider:string;modelId:string;error:string}[];eligibleTotal:number}>(),[graph,setGraph]=useState<{claims:any[];sources:any[];links:any[];summary:Record<string,number>}>({claims:[],sources:[],links:[],summary:{}})
  const load=useCallback(()=>api.evidenceGraph().then(setGraph).catch(error=>notify(error instanceof Error?error.message:'Falha ao carregar Evidence Graph')),[notify]);useEffect(()=>{void load()},[load])
  const start=async()=>{if(!query.trim())return;setRunning(true);setResult(undefined);try{const research=await runResearchSwarm(query.trim(),4,event=>setProgress(event.message));setResult(research);await load();notify(`Research Swarm concluído · ${research.researchers.length} modelos · ${research.sources.length} fontes`)}catch(error){notify(error instanceof Error?error.message:'Falha no Research Swarm')}finally{setRunning(false);setProgress('')}}
  return <div className="workspace-page research-page page-enter"><Header eyebrow="EVIDENCE INTELLIGENCE" title="Evidence & Research Engine" description="Research Swarm Puter: modelos explicitamente elegíveis pesquisam em paralelo, com deduplicação, contradições e síntese."/><div className="research-query"><Search size={18}/><textarea value={query} onChange={event=>setQuery(event.target.value)} rows={2} placeholder="Registre uma pergunta ou afirmação para investigação..."/><div><button><Layers3 size={14}/>Evidence Graph</button><button onClick={start} disabled={running||!query.trim()}>{running?<RefreshCw className="spin" size={15}/>:<ArrowUpRight size={15}/>}Pesquisar com swarm</button></div></div><div className="router-overview"><div><span className="router-pulse"><Globe2 size={23}/><i/></span><div><small>CLAIMS</small><strong>{graph.claims.length}</strong><p>estruturadas no workspace</p></div></div><div className="router-stat"><small>FONTES</small><strong>{graph.sources.length}</strong><span>adicionadas pelo usuário</span></div><div className="router-stat"><small>UNKNOWN</small><strong>{graph.summary.unknown??0}</strong><span>lacunas explícitas</span></div><div className="router-stat"><small>CONFLITOS</small><strong>{graph.summary.conflicting??0}</strong><span>não resolvidos por maioria</span></div></div><div className="research-layout"><main><div className="research-answer"><header><div><Sparkles size={15}/><strong>{running?'Research Swarm em execução':'Síntese e Claim Graph'}</strong><span>{progress||'Resultados são client-reported e fontes devem ser abertas pelo usuário'}</span></div></header>{result&&<section className="research-synthesis"><div className="confidence-banner"><ShieldCheck size={18}/><div><strong>{result.researchers.length} pesquisadores · {result.eligibleTotal} elegíveis · {result.failures.length} falhas</strong><span>Síntese crítica; não é verificação determinística.</span></div></div><p>{result.answer}</p></section>}{graph.claims.map(claim=><div className="confidence-banner" key={claim.id}><ShieldCheck size={18}/><div><strong>{claim.state} · confiança {claim.confidence}%</strong><span>{claim.statement}</span></div></div>)}{!graph.claims.length&&!running&&<div className="real-data-empty"><strong>Nenhuma claim registrada</strong><p>Inicie uma pesquisa; a pergunta será registrada no Unknown Map.</p></div>}</div></main><aside className="sources-panel"><header><div><strong>Fontes</strong><span>{graph.sources.length} registradas</span></div><Filter size={14}/></header>{graph.sources.map(source=><article key={source.id}><div><span className="source-kind">{source.status}</span></div><h3>{source.title}</h3><p><Globe2 size={11}/>{source.publisher??new URL(source.url).hostname}</p><button onClick={()=>window.open(source.url,'_blank','noopener')}><ExternalLink size={12}/></button></article>)}{!graph.sources.length&&<div className="real-data-empty"><strong>Sem fontes</strong></div>}</aside></div></div>
}

const marketplace=[
  {name:'Game Architect S++',author:'Bunker Labs',uses:'42.8k',rating:'4.9',icon:Box,color:'violet',tag:'Featured'},
  {name:'Scientific Core',author:'Open Research',uses:'28.2k',rating:'4.8',icon:Atom,color:'blue',tag:'Verified'},
  {name:'Cinematic Director',author:'Frame Collective',uses:'18.7k',rating:'4.9',icon:Eye,color:'gold',tag:'Trending'},
  {name:'Security Sentinel',author:'Safe Systems',uses:'31.1k',rating:'4.8',icon:ShieldCheck,color:'green',tag:'Verified'},
  {name:'Product Builder',author:'Venture Works',uses:'15.9k',rating:'4.7',icon:Rocket,color:'red',tag:'New'},
  {name:'Data Intelligence',author:'Pattern Labs',uses:'22.4k',rating:'4.9',icon:BarChart3,color:'cyan',tag:'Featured'},
]
function Marketplace({id,notify}:Props){const isFork=id==='forks';const[installed,setInstalled]=useState<string[]>(['Scientific Core']);const[query,setQuery]=useState('');const cards=marketplace.filter(x=>x.name.toLowerCase().includes(query.toLowerCase()));const toggle=(n:string)=>{setInstalled(a=>a.includes(n)?a.filter(x=>x!==n):[...a,n]);notify(installed.includes(n)?`${n} removido`:`${n} instalado no workspace`)};return <div className="workspace-page page-enter"><Header eyebrow="COMMUNITY INTELLIGENCE" title={isFork?'Forks of Singularity':'Agent Exchange'} description={isFork?'Versões especializadas da Singularity, construídas e verificadas pela comunidade.':'Descubra especialistas prontos para fazer parte das suas missões.'} action={isFork?'Criar fork':'Publicar agente'} onAction={()=>notify(isFork?'Fork Studio aberto':'Publicação de agente iniciada')}/><div className="market-hero"><div><span className="kicker">CURADORIA SINGULARITY</span><h2>{isFork?'Inteligências únicas. O mesmo Core confiável.':'Monte sua equipe impossível.'}</h2><p>Capacidades verificadas, permissões transparentes e isolamento seguro.</p><button onClick={()=>notify('Coleção em destaque aberta')}>Explorar coleção <ArrowUpRight size={13}/></button></div><div className="market-orbit"><span><Sparkles size={19}/></span><i/><i/><i/><b><Bot size={13}/></b><b><Code2 size={13}/></b><b><Globe2 size={13}/></b></div></div><div className="market-toolbar"><label><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar capacidades, criadores ou categorias"/></label><button><SlidersHorizontal size={14}/>Filtros</button><button>Mais usados <ChevronDown size={12}/></button></div><div className="market-grid">{cards.map((a,i)=>{const Icon=a.icon;const on=installed.includes(a.name);return <article key={a.name}><div className={`market-cover ${a.color}`}><div className="market-pattern"/><span className="market-icon"><Icon size={26}/></span><span className="market-tag">{a.tag}</span><button><Heart size={14}/></button></div><div className="market-info"><h3>{a.name}</h3><p>por <strong>{a.author}</strong><ShieldCheck size={11}/></p><div><span><Users size={11}/>{a.uses}</span><span><Star size={11}/>{a.rating}</span><span>v{2+i}.4</span></div><button className={on?'installed':''} onClick={()=>toggle(a.name)}>{on?<><Check size={13}/>Instalado</>:<><Plus size={13}/>Adicionar</>}</button></div></article>})}</div></div>}

const frontier:Record<string,{title:string;eyebrow:string;description:string;icon:LucideIcon,metric:string,unit:string,actions:string[]}>= {
  'digital-twin':{title:'Digital Twin',eyebrow:'PERSONAL INTELLIGENCE',description:'Um modelo operacional que aprende como você pensa, decide e cria.',icon:BrainCircuit,metric:'87',unit:'% alinhado',actions:['Calibrar com decisões','Simular minha abordagem','Revisar perfil cognitivo']},
  'time-machine':{title:'Time Machine',eyebrow:'TEMPORAL INTELLIGENCE',description:'Navegue por decisões passadas e simule futuros antes de se comprometer.',icon:History,metric:'42',unit:'linhas temporais',actions:['Criar cenário futuro','Comparar versões','Restaurar checkpoint']},
  'dreamspace':{title:'Dreamspace',eyebrow:'IMAGINATION ENGINE',description:'Um espaço generativo onde ideias abstratas se tornam mundos exploráveis.',icon:Orbit,metric:'18',unit:'mundos vivos',actions:['Gerar um mundo','Entrar em imersão','Fundir conceitos']},
  'consensus':{title:'Consensus Engine',eyebrow:'COLLECTIVE REASONING',description:'Especialistas independentes debatem, criticam e convergem em decisões melhores.',icon:Users,metric:'96.4',unit:'% consenso',actions:['Iniciar deliberação','Definir perspectivas','Auditar divergências']},
  'skill-foundry':{title:'Skill Foundry',eyebrow:'CAPABILITY FACTORY',description:'Ensine novas competências a agentes através de exemplos, testes e ferramentas.',icon:WandSparkles,metric:'128',unit:'skills ativos',actions:['Forjar nova skill','Importar exemplos','Executar avaliação']},
  'observatory':{title:'Data Observatory',eyebrow:'LIVING DATA',description:'Observe dados como sistemas vivos e descubra padrões antes invisíveis.',icon:BarChart3,metric:'2.8M',unit:'eventos analisados',actions:['Conectar dados','Descobrir anomalias','Criar observatório']},
  'reality-bridge':{title:'Reality Bridge',eyebrow:'DIGITAL TO PHYSICAL',description:'Conecte decisões inteligentes a dispositivos, robôs e operações reais.',icon:InfinityIcon,metric:'24',unit:'sistemas online',actions:['Conectar dispositivo','Criar protocolo','Abrir centro de segurança']},
  'simulacoes':{title:'Simulações',eyebrow:'POSSIBILITY ENGINE',description:'Modele sistemas, teste hipóteses e antecipe consequências com agentes.',icon:Atom,metric:'8.4k',unit:'cenários executados',actions:['Nova simulação','Importar sistema','Comparar resultados']},
}
function Frontier({id,notify}:Props){const f=frontier[id];const Icon=f.icon;const[running,setRunning]=useState(true);return <div className="workspace-page frontier-page page-enter"><Header eyebrow={f.eyebrow} title={f.title} description={f.description} action={f.actions[0]} onAction={()=>notify(`${f.actions[0]} iniciado`)}/><div className="frontier-console"><section className="frontier-visual"><div className="universe-grid"/><div className="core-rings"><span/><span/><span/><Icon size={35}/></div>{[0,1,2,3,4].map(i=><i className={`satellite s${i}`} key={i}><b/></i>)}<div className="frontier-live"><i/>SISTEMA {running?'ATIVO':'PAUSADO'}</div><div className="frontier-metric"><strong>{f.metric}</strong><span>{f.unit}</span></div></section><aside className="frontier-control"><header><div><Radio size={14}/><strong>Controle em tempo real</strong></div><button onClick={()=>setRunning(!running)}>{running?<Pause size={14}/>:<Play size={14}/>}</button></header><div className="frontier-stats"><div><span>Confiança</span><strong>94.8%</strong><i><b style={{width:'94.8%'}}/></i></div><div><span>Complexidade</span><strong>Alta</strong><i><b style={{width:'78%'}}/></i></div><div><span>Estabilidade</span><strong>99.2%</strong><i><b style={{width:'99.2%'}}/></i></div></div><span className="kicker">AÇÕES RECOMENDADAS</span>{f.actions.map((a,i)=><button className="frontier-action" onClick={()=>notify(`${a} aberto`)} key={a}><span className={`fa${i}`}>{i===0?<Sparkles size={15}/>:i===1?<Network size={15}/>:<ShieldCheck size={15}/>}</span><div><strong>{a}</strong><small>{i===0?'Ação principal sugerida':i===1?'Explorar possibilidades':'Controle e transparência'}</small></div><ChevronRight size={14}/></button>)}</aside></div><div className="frontier-bottom"><article><span className="kicker">ACTIVITY STREAM</span><h3>Operações recentes</h3>{['Contexto recalibrado com 14 novas decisões','Simulação convergiu após 8.240 iterações','Verifier confirmou estabilidade do resultado'].map((x,i)=><div key={x}><span className={`event-symbol e${i}`}>{i===2?<Check size={11}/>:<Activity size={11}/>}</span><p>{x}<small>há {i*4+2} min</small></p></div>)}</article><article><span className="kicker">INTELLIGENCE MAP</span><h3>Conexões ativas</h3><div className="mini-network"><span/><span/><span/><span/><span/><i/><i/><i/></div></article><article><span className="kicker">SAFETY LAYER</span><h3>Guardrails operacionais</h3><div className="safety-score"><ShieldCheck size={27}/><strong>Protegido</strong><span>Todos os limites ativos</span></div><button onClick={()=>notify('Políticas de segurança abertas')}>Ver políticas <ArrowUpRight size={12}/></button></article></div></div>}

export const platformIds=['deep-research','forks','agent-market','digital-twin','time-machine','dreamspace','consensus','skill-foundry','observatory','reality-bridge','simulacoes']
export default function PlatformView({id,notify}:Props){if(id==='deep-research')return <Research notify={notify}/>;if(id==='forks'||id==='agent-market')return <Marketplace id={id} notify={notify}/>;if(frontier[id])return <Frontier id={id} notify={notify}/>;return null}
