import type { LayerSpec } from './types.js'

export const realityLayers: LayerSpec[] = [
  { id: 0, key: 'meta', name: 'Meta-realidade', topics: ['regras', 'constantes', 'espaço', 'tempo', 'causalidade', 'informação', 'estado', 'leis'], typicalDescription: 'law', existing: ['clock', 'causality', 'spacetime'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 1, key: 'fundamental', name: 'Fundamental', topics: ['campos', 'partículas', 'antipartículas', 'interações', 'energia', 'momento', 'carga', 'spin', 'estados quânticos'], typicalDescription: 'law', existing: ['fields', 'charge', 'magnetism', 'energy'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 2, key: 'subatomic', name: 'Subatômica', topics: ['quarks', 'léptons', 'hádrons', 'núcleos', 'decaimentos'], typicalDescription: 'law', existing: ['substances'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 3, key: 'atomic', name: 'Atômica', topics: ['prótons', 'nêutrons', 'elétrons', 'isótopos', 'íons', 'estrutura eletrônica'], typicalDescription: 'statistical', existing: ['substances'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 4, key: 'molecular', name: 'Molecular', topics: ['ligações', 'moléculas', 'geometria', 'polaridade', 'interações'], typicalDescription: 'statistical', existing: ['substances', 'matter'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 5, key: 'chemistry', name: 'Química', topics: ['reações', 'cinética', 'equilíbrio', 'termoquímica', 'ácidos/bases', 'soluções'], typicalDescription: 'continuum', existing: ['chemistry', 'carbon-cycle', 'nitrogen-cycle'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 6, key: 'materials', name: 'Matéria e materiais', topics: ['sólidos', 'líquidos', 'gases', 'plasmas', 'cristais', 'metais', 'polímeros', 'propriedades'], typicalDescription: 'continuum', existing: ['matter', 'phase'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 7, key: 'macro-physics', name: 'Física macroscópica', topics: ['mecânica', 'gravidade', 'termodinâmica', 'fluidos', 'ondas', 'EM', 'óptica', 'acústica'], typicalDescription: 'continuum', existing: ['gravity', 'energy', 'mechanics', 'acoustics', 'optics'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 8, key: 'geology', name: 'Geologia / planetária', topics: ['minerais', 'rochas', 'solo', 'tectônica', 'vulcão', 'sismos', 'erosão', 'sedimento'], typicalDescription: 'continuum', existing: ['geology', 'tectonics', 'volcano', 'earthquake', 'erosion-step', 'sediment'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 9, key: 'atmosphere', name: 'Atmosfera e clima', topics: ['gases', 'pressão', 'temperatura', 'umidade', 'ventos', 'nuvens', 'chuvas', 'tempestades', 'clima'], typicalDescription: 'continuum', existing: ['atmosphere', 'weather', 'ozone', 'humidity', 'heatwave'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 10, key: 'hydrosphere', name: 'Hidrosfera', topics: ['água', 'oceanos', 'rios', 'gelo', 'marés', 'ciclo da água', 'química da água'], typicalDescription: 'continuum', existing: ['hydrology', 'groundwater', 'watershed', 'glacier', 'tide'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 11, key: 'prebiotic', name: 'Química pré-biótica', topics: ['moléculas orgânicas', 'auto-organização', 'membranas primitivas', 'replicação', 'metabolismo primitivo'], typicalDescription: 'law', existing: ['chemistry'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 12, key: 'bio-fundamental', name: 'Biologia fundamental', topics: ['DNA/RNA', 'proteínas', 'lipídios', 'carboidratos', 'membranas', 'metabolismo'], typicalDescription: 'statistical', existing: ['substances', 'diet'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 13, key: 'cell', name: 'Célula', topics: ['estrutura', 'transporte', 'comunicação', 'divisão', 'homeostase', 'mutação'], typicalDescription: 'statistical', existing: ['organism'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 14, key: 'organism', name: 'Organismos', topics: ['tecidos', 'órgãos', 'sistemas', 'crescimento', 'reprodução', 'nutrição', 'locomoção', 'saúde'], typicalDescription: 'discrete-body', existing: ['organism', 'growth', 'reproduction', 'health'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 15, key: 'evolution', name: 'Evolução', topics: ['mutação', 'seleção', 'deriva', 'competição', 'adaptação', 'especiação', 'extinção'], typicalDescription: 'statistical', existing: ['succession', 'carrying'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 16, key: 'ecology', name: 'Ecologia', topics: ['populações', 'predação', 'simbiose', 'cadeias alimentares', 'nichos', 'ciclos biogeoquímicos'], typicalDescription: 'statistical', existing: ['trophic', 'ecology', 'carbon-cycle'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 17, key: 'nervous', name: 'Sistema nervoso', topics: ['neurônios', 'sinapses', 'sensorial', 'motor', 'reflexos', 'aprendizado', 'memória'], typicalDescription: 'discrete-body', existing: ['perception', 'smell', 'taste', 'touch', 'pain-signal'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 18, key: 'cognition', name: 'Mente / cognição', topics: ['percepção', 'atenção', 'memória', 'motivação', 'raciocínio', 'decisão', 'consciência como modelo'], typicalDescription: 'law', existing: ['memory-trace', 'bind-needs'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 19, key: 'individual', name: 'Indivíduo', topics: ['corpo', 'necessidades', 'objetivos', 'comportamento', 'relações', 'história'], typicalDescription: 'discrete-body', existing: ['organism', 'bind-needs', 'nmn'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 20, key: 'communication', name: 'Comunicação e interação', topics: ['sinais', 'linguagem', 'cooperação', 'conflito', 'reputação', 'normas'], typicalDescription: 'discrete-body', existing: ['speech-knowledge', 'culture-claim', 'norms'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 21, key: 'society', name: 'Sociedade', topics: ['famílias', 'grupos', 'cultura', 'instituições', 'educação', 'organização'], typicalDescription: 'statistical', existing: ['society-bind', 'kinship', 'census-know'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 22, key: 'economy', name: 'Economia', topics: ['recursos', 'produção', 'trabalho', 'comércio', 'preços', 'distribuição'], typicalDescription: 'statistical', existing: ['labor', 'trade', 'gift', 'economy'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 23, key: 'politics', name: 'Política e governança', topics: ['poder', 'leis', 'governo', 'justiça', 'diplomacia', 'conflitos'], typicalDescription: 'law', existing: ['norms', 'territory', 'conflict-share'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 24, key: 'technology', name: 'Tecnologia', topics: ['ferramentas', 'máquinas', 'energia', 'computação', 'medicina', 'transporte'], typicalDescription: 'discrete-body', existing: ['tool-craft'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 25, key: 'civilization', name: 'Civilização', topics: ['aldeias', 'cidades', 'infraestrutura', 'indústria', 'ciência', 'história'], typicalDescription: 'statistical', existing: ['city-bind', 'structure', 'construction'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 26, key: 'biosphere', name: 'Biosfera / planeta', topics: ['atmosfera+hidro+geo', 'ecossistemas', 'clima', 'ciclos planetários', 'antropogênico'], typicalDescription: 'continuum', existing: ['bio-run', 'sphere-run'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 27, key: 'stellar', name: 'Sistema estelar', topics: ['estrelas', 'planetas', 'luas', 'asteroides', 'radiação', 'evolução do sistema'], typicalDescription: 'continuum', existing: ['astronomy', 'orbit', 'insolation'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 28, key: 'cosmic', name: 'Escala cósmica', topics: ['aglomerados', 'galáxias', 'meio interestelar', 'interações gravitacionais'], typicalDescription: 'law', existing: ['gravity', 'spacetime'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
  { id: 29, key: 'universe', name: 'Universo', topics: ['cosmologia', 'expansão', 'estrutura', 'evolução cósmica', 'cenários de longo prazo'], typicalDescription: 'law', existing: ['spacetime'], do15MayAbstract: true, do15MayDelete: false, consciousnessClaim: false },
]

export const layerById = (id: number) => realityLayers.find(item => item.id === id)

export const layerCount = realityLayers.length
